### ISSUE TITLE
Opening browser should use Start not Run

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1273]
http://golang.org/pkg/os/exec/#Cmd.Run
```
Run starts the specified command and waits for it to complete.
```
Causing us to get stuck in the syscall:
```
[monitor] 2015/01/19 18:17:26.830729 monitor.go:104: INFO: Starting syncthing
[WYS7E] 2015/01/19 18:17:27.445682 main.go:401: INFO: syncthing v0.10.20 (go1.4 linux-amd64 default) unknown-user@syncthing-builder 2015-01-13 16:27:47 UTC
[WYS7E] 2015/01/19 18:17:27.445835 main.go:402: INFO: My ID: WYS7ET3-BDOETQG-ESXWJQH-C6CNITM-AF5WSG4-Q53MRLD-OSIDSYB-AS6B2QG
[WYS7E] 2015/01/19 18:17:27.457852 progressemitter.go:99: DEBUG: progress emitter: updated interval 5s
[WYS7E] 2015/01/19 18:17:27.457922 main.go:654: INFO: Starting web GUI on http://127.0.0.1:8080/
[WYS7E] 2015/01/19 18:17:27.458967 progressemitter.go:66: DEBUG: progress emitter: timer - looking after 0
[WYS7E] 2015/01/19 18:17:27.458995 progressemitter.go:82: DEBUG: progress emitter: nothing new
SIGABRT: abort
PC=0x469801

goroutine 0 [idle]:
runtime.futex(0xd9ceb8, 0x0, 0x0, 0x0, 0x0, 0xd9c320, 0x1, 0x4368ef, 0x436b0e, 0xd9ceb8, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:277 +0x21
runtime.futexsleep(0xd9ceb8, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.c:49 +0x47
runtime.notesleep(0xd9ceb8)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xae
stopm()
	/usr/local/go/src/runtime/proc.c:1178 +0x119
findrunnable(0xc208013200)
	/usr/local/go/src/runtime/proc.c:1487 +0x562
schedule()
	/usr/local/go/src/runtime/proc.c:1575 +0x151
runtime.park_m(0xc2080017a0)
	/usr/local/go/src/runtime/proc.c:1654 +0x113
runtime.mcall(0x45ca34)
	/usr/local/go/src/runtime/asm_amd64.s:186 +0x5a

goroutine 1 [syscall]:
syscall.Syscall6(0x3d, 0x1124, 0xc2089f9c44, 0x0, 0xc20806a480, 0x0, 0x0, 0x7fc83be71000, 0x42ccc1, 0xc20809c140)
	/usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x1124, 0xc2089f9c44, 0x0, 0xc20806a480, 0x90, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x1124, 0xc2089f9c8c, 0x0, 0xc20806a480, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc2080a2f40, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc2080a2f40, 0xc2080a2a20, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc208054000, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:364 +0x23c
os/exec.(*Cmd).Run(0xc208054000, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:246 +0x71
main.openURL(0xc2080a2a00, 0x16, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/openurl_unix.go:36 +0x254
main.setupGUI(0xc208050480, 0xc20809be60)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:661 +0xa94
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:512 +0x19ab
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:365 +0x20ed

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0xc20801e680, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:179 +0x3bf
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0xc20802e040)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:215 +0x48
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:209 +0x1c4

goroutine 8 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:33 +0xec
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:26 +0x25

goroutine 10 [chan receive]:
github.com/syncthing/syncthing/internal/config.(*Wrapper).Serve(0xc208050480)
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:88 +0x75
created by github.com/syncthing/syncthing/internal/config.Wrap
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:63 +0x133

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080a40e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2080da000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc2080da000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc2080da000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x858
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2080da000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2080da000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 17 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0xc2080f7380)
	/go/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:57 +0x8b8
created by github.com/syncthing/syncthing/internal/model.NewModel
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:153 +0x6ba

goroutine 18 [sleep]:
github.com/syncthing/syncthing/internal/model.func·024()
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:26 +0x4a
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:44 +0xd6

goroutine 19 [sleep]:
github.com/syncthing/syncthing/internal/model.func·024()
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:26 +0x4a
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:44 +0xd6

goroutine 20 [sleep]:
github.com/syncthing/syncthing/internal/model.func·024()
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:26 +0x4a
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:44 +0xd6

goroutine 21 [IO wait]:
net.(*pollDesc).Wait(0xc208146140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208146140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2081460e0, 0x0, 0x7fc83be82d60, 0xc2089ec5c0)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080300c0, 0x7fc83be714b0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080300c0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
main.(*DowngradingListener).Accept(0xc2089f36c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:113 +0x85
net/http.(*Server).Serve(0xc20809c0c0, 0x7fc83be90650, 0xc2089f36c0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
main.func·001()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:190 +0x64
created by main.startGUI
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:194 +0x166e

goroutine 33 [IO wait]:
net.(*pollDesc).Wait(0xc208146370, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208146370, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208146310, 0xc20824a000, 0x1000, 0x1000, 0x0, 0x7fc83be82d60, 0xc2084482a8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208030308, 0xc20824a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).Read(0xc20809c180, 0xc20824a000, 0x1000, 0x1000, 0xffffffff, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:164 +0x13a
main.(*WrappedConnection).Read(0xc2080dc0e0, 0xc20824a000, 0x1000, 0x1000, 0x4000, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:137 +0x73
net/http.(*liveSwitchReader).Read(0xc20804e228, 0xc20824a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080dc100, 0xc20824a000, 0x1000, 0x1000, 0xc2084482b0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc208052360)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208052360, 0xc2089d640a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208052360, 0x0, 0x0, 0x0, 0xc207fb6f00, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2084902a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2084902a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc208052360, 0xc208033520, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20804e1e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20804e1e0)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 50 [IO wait]:
net.(*pollDesc).Wait(0xc208010ca0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010ca0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010c40, 0xc208281000, 0x1000, 0x1000, 0x0, 0x7fc83be82d60, 0xc2084488e0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2081bc008, 0xc208281000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).Read(0xc2081c0060, 0xc208281000, 0x1000, 0x1000, 0xffffffff, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:164 +0x13a
main.(*WrappedConnection).Read(0xc20801e980, 0xc208281000, 0x1000, 0x1000, 0xc2080b6210, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:137 +0x73
net/http.(*liveSwitchReader).Read(0xc20825c368, 0xc208281000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20801e9a0, 0xc208281000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2081c00c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2081c00c0, 0xc20827e10a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2081c00c0, 0x0, 0x0, 0x0, 0x61f200, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc208294120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc208294120, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2081c00c0, 0xc208033c70, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20825c320, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20825c320)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 51 [IO wait]:
net.(*pollDesc).Wait(0xc208010df0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010df0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010d90, 0xc208290000, 0x1000, 0x1000, 0x0, 0x7fc83be82d60, 0xc208448640)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2081bc010, 0xc208290000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).Read(0xc2081c0120, 0xc208290000, 0x1000, 0x1000, 0xffffffff, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:164 +0x13a
main.(*WrappedConnection).Read(0xc20801ea00, 0xc208290000, 0x1000, 0x1000, 0x9dfd00, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:137 +0x73
net/http.(*liveSwitchReader).Read(0xc20825c408, 0xc208290000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20801ea20, 0xc208290000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2081c0180)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2081c0180, 0xc20827e20a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2081c0180, 0x0, 0x0, 0x0, 0x61f200, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2084460f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2084460f0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2081c0180, 0xc2080335f0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20825c3c0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20825c3c0)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 34 [semacquire]:
sync.(*Cond).Wait(0xc20802e100)
	/usr/local/go/src/sync/cond.go:62 +0x9e
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).Since(0xc20802e040, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:240 +0xea
main.restGetEvents(0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:567 +0x221
net/http.HandlerFunc.ServeHTTP(0xb367c0, 0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20814d950, 0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/usr/local/go/src/net/http/server.go:1541 +0x17d
main.func·002(0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:202 +0xcc
net/http.HandlerFunc.ServeHTTP(0xc2089f38a0, 0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/usr/local/go/src/net/http/server.go:1265 +0x41
main.func·004(0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:231 +0xac
net/http.HandlerFunc.ServeHTTP(0xc20800b4e0, 0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
[monitor] 2015/01/19 18:17:45.634533 monitor.go:157: INFO: Syncthing exited: exit status 2
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20814da10, 0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/usr/local/go/src/net/http/server.go:1541 +0x17d
main.func·010(0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_csrf.go:62 +0x412
net/http.HandlerFunc.ServeHTTP(0xc2080a29a0, 0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/usr/local/go/src/net/http/server.go:1265 +0x41
main.func·005(0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:238 +0xae
net/http.HandlerFunc.ServeHTTP(0xc20800ae10, 0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc20809c0c0, 0x7fc83be908e0, 0xc20804e460, 0xc20836e820)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20804e640)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 65 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

rax     0xca
rbx     0xd9ceb8
rcx     0xffffffffffffffff
rdx     0x0
rdi     0xd9ceb8
rsi     0x0
rbp     0x1
rsp     0x7fffdacaaf78
r8      0x0
r9      0x0
r10     0x0
r11     0x286
r12     0x0
r13     0x1
r14     0x11
r15     0x13
rip     0x469801
rflags  0x286
cs      0x33
fs      0x0
gs      0x0
[monitor] 2015/01/19 18:17:46.634899 monitor.go:104: INFO: Starting syncthing
[WYS7E] 2015/01/19 18:17:47.255501 main.go:401: INFO: syncthing v0.10.20 (go1.4 linux-amd64 default) unknown-user@syncthing-builder 2015-01-13 16:27:47 UTC
[WYS7E] 2015/01/19 18:17:47.255659 main.go:402: INFO: My ID: WYS7ET3-BDOETQG-ESXWJQH-C6CNITM-AF5WSG4-Q53MRLD-OSIDSYB-AS6B2QG
[WYS7E] 2015/01/19 18:17:47.267645 progressemitter.go:99: DEBUG: progress emitter: updated interval 5s
[WYS7E] 2015/01/19 18:17:47.267723 main.go:654: INFO: Starting web GUI on http://127.0.0.1:8080/
[WYS7E] 2015/01/19 18:17:47.268751 progressemitter.go:66: DEBUG: progress emitter: timer - looking after 0
[WYS7E] 2015/01/19 18:17:47.268777 progressemitter.go:82: DEBUG: progress emitter: nothing new
[WYS7E] 2015/01/19 18:17:47.839881 upnp.go:106: INFO: Starting UPnP discovery...
[WYS7E] 2015/01/19 18:17:53.840835 upnp.go:133: INFO: UPnP discovery complete (found 0 devices).
[WYS7E] 2015/01/19 18:17:53.840911 main.go:1134: INFO: Starting local discovery announcements
[WYS7E] 2015/01/19 18:17:53.841169 main.go:1139: INFO: Starting global discovery announcements
[WYS7E] 2015/01/19 18:17:53.842205 main.go:575: INFO: Device WYS7ET3-BDOETQG-ESXWJQH-C6CNITM-AF5WSG4-Q53MRLD-OSIDSYB-AS6B2QG is "Apollo" at [dynamic]
[WYS7E] 2015/01/19 18:17:53.842295 usage_report.go:107: INFO: Starting usage reporting
```

**Comment by AudriusButkevicius** [comment]
Again, something @calmh needs to clarify, whether it was intentional, or just an oversight.

**Comment by calmh** [comment]
I don't understand this issue. :) When does it happen? Both `open` (mac) and `xdg-open` (linux) should return immediately, although I don't personally use the latter so maybe I'm misunderstood...

**Comment by AudriusButkevicius** [comment]
I don't think you even need to do `Wait()`. As far as I understand `Run()` blocks until the child exits, and I guess the only reason it works now is because the actual commnad you run forks off and disowns a child and returns, which doesn't always seems to be the case.

**Comment by kozec** [comment]
> I don't understand this issue. :) When does it happen? Both open (mac) and xdg-open (linux) should return immediately

Ahem... xdg-open will not return until program that is used for opening exits. It may even run multiple executables in sequence, if first one exits with return code != 0.

But calling browser executable when same browser is already running will block only until executable makes RPC call to original instance. That may be reason why noone spotted problem before :)

**Comment by calmh** [comment]
Right. So this should be Start() + Wait(). We do need Wait() or we'll leave a zombie process around.

**Comment by AudriusButkevicius** [comment]
Yes, true, but given we fork of a routine anyway, we should just do `go openBrowser`.

**Comment by calmh** [comment]
Yes, that's simpler. :)
