### ISSUE TITLE
Crash while replacing directory with a file

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1302]
We should check that it's actually a file we currently have in the database at:
https://github.com/syncthing/syncthing/blob/master/internal/model/puller.go#L376

**Comment by AudriusButkevicius** [comment]
(v0.10.21)
```
panic: runtime error: index out of range
goroutine 103 [running]:
 github.com/syncthing/syncthing/internal/model.(*Puller).pullerIteration(0xc20966afc0, xc20968a000, 0x3)
     /go/src/github.com/syncthing/syncthing/internal/model/puller.go:377 +0x14a3
 github.com/syncthing/syncthing/internal/model.(*Puller).Serve(0xc20966afc0)
     /go/src/github.com/syncthing/syncthing/internal/model/puller.go:162 +0xb80
 created by github.com/syncthing/syncthing/internal/model.(*Model).StartFolderRW
     /go/src/github.com/syncthing/syncthing/internal/model/model.go:210 +0x748
```

Not sure how this is happening, as the file change integration tests are passing.
