### ISSUE TITLE
Fatal out of memory

### ISSUE THREAD

**Issue by redoranges** [syncthing/syncthing#1372]
I just switched from btsync to Syncthing.
Running v0.10.20 installed from PPA on ubuntu 14.10
server is 64bit with 6GB ram, laptop is 32bit with 4GB ram

I am trying to share my photos repo locally
The server is folder master, while the laptop is not

repo is 35481 items, ~143 GB
After the server settled down scaning RAM utilization is at 58MiB

On the laptop I can't get the full repo, it runs for a bit growing memory to about 60% system ram then restarts (web site claims around 2.2GB RAM usage)

running wth debug i see
```
[{192.168.1.11:22000 2015-02-21 15:15:56.478072 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:15:56.477163 -0500 EST}]
runtime: memory allocated by OS (0xb0b93000) not in usable range [0x18600000,0x98600000)
fatal error: out of memory
[monitor] 2015/02/21 15:16:03.441833 :0: WARNING: Panic detected, writing to "/home/power/.config/syncthing/panic-20150221-151603.log"
[monitor] 2015/02/21 15:16:03.441900 :0: WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 2015/02/21 15:16:03.639955 :0: INFO: Syncthing exited: exit status 3
```

the panic log is below

```
[3GABB] 2015/02/21 15:11:03.341900 main.go:401: INFO: syncthing v0.10.20 (xgcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1 linux-386 default) niklas@Niklas-Netbook 2015-01-13 16:27:47 UTC
[3GABB] 2015/02/21 15:11:03.342724 main.go:402: INFO: My ID: 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:11:06.539233 main.go:654: INFO: Starting web GUI on https://127.0.0.1:8080/
[3GABB] 2015/02/21 15:11:21.777983 main.go:1134: INFO: Starting local discovery announcements
[3GABB] 2015/02/21 15:11:21.778411 main.go:1139: INFO: Starting global discovery announcements
[3GABB] 2015/02/21 15:11:22.016592 main.go:559: OK: Ready to synchronize Photos (read-write)
[3GABB] 2015/02/21 15:11:22.016703 :0: DEBUG: listening on 0.0.0.0:22000
[3GABB] 2015/02/21 15:11:22.017030 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:11:22.023998 :0: DEBUG: discover udp4://announce.syncthing.net:22026: broadcast: Sending self announcement to 194.126.249.5:22026
[3GABB] 2015/02/21 15:11:23.670437 :0: DEBUG: discover udp4://announce.syncthing.net:22026: Lookup(3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF) result: [76.10.134.115:22000]
...
[3GABB] 2015/02/21 15:11:23.670527 :0: DEBUG: discover udp4://announce.syncthing.net:22026: broadcast: Self-lookup returned: [76.10.134.115:22000]
[3GABB] 2015/02/21 15:11:24.870293 main.go:575: INFO: Device 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF is "RedDell" at [dynamic]
[3GABB] 2015/02/21 15:11:24.870585 main.go:575: INFO: Device IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 is "big" at [dynamic]
[3GABB] 2015/02/21 15:11:24.870672 main.go:609: INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
[3GABB] 2015/02/21 15:11:24.871246 usage_report.go:107: INFO: Starting usage reporting
[3GABB] 2015/02/21 15:11:25.404924 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.11:21025 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:11:25.405187 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:11:25.40499 -0500 EST}]
[3GABB] 2015/02/21 15:11:25.411459 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:11:25.809216 discover.go:308: DEBUG: discover: Received local announcement from [fe80::16da:e9ff:fe44:de77]:21026 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:11:25.809487 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:11:25.40499 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:11:25.809277 -0500 EST}]
[3GABB] 2015/02/21 15:11:25.920399 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:11:26.678464 :0: INFO: Completed initial scan (rw) of folder Photos
[3GABB] 2015/02/21 15:11:29.405084 :0: DEBUG: dial IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 192.168.1.11:22000
[3GABB] 2015/02/21 15:11:30.031779 :0: INFO: Established secure connection to IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 at 192.168.1.12:46976-192.168.1.11:22000
[3GABB] 2015/02/21 15:11:30.031840 :0: DEBUG: cipher suite C02F
[3GABB] 2015/02/21 15:11:30.039535 :0: INFO: Device IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 client is "syncthing v0.10.20"
[3GABB] 2015/02/21 15:11:30.039811 :0: INFO: Device IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 name is "big"
[3GABB] 2015/02/21 15:11:52.645936 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:11:55.190129 discover.go:308: DEBUG: discover: Received local announcement from [fe80::16da:e9ff:fe44:de77]:21026 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:11:55.190404 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:11:25.40499 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:11:55.190175 -0500 EST}]
[3GABB] 2015/02/21 15:11:55.686282 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.11:21025 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:11:55.686831 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:11:55.686577 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:11:55.190175 -0500 EST}]
[3GABB] 2015/02/21 15:12:23.793859 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:12:30.075942 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.11:21025 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:12:30.076222 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:12:30.075988 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:11:55.190175 -0500 EST}]
[3GABB] 2015/02/21 15:12:30.076441 discover.go:308: DEBUG: discover: Received local announcement from [fe80::16da:e9ff:fe44:de77]:21026 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:12:30.076880 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:12:30.075988 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:12:30.076472 -0500 EST}]
[3GABB] 2015/02/21 15:12:53.013771 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:12:55.194930 discover.go:308: DEBUG: discover: Received local announcement from [fe80::16da:e9ff:fe44:de77]:21026 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:12:55.195221 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:12:30.075988 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:12:55.195003 -0500 EST}]
[3GABB] 2015/02/21 15:12:56.877326 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.11:21025 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:12:56.877581 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:12:56.877372 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:12:55.195003 -0500 EST}]
[3GABB] 2015/02/21 15:13:23.213953 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:13:25.353226 discover.go:308: DEBUG: discover: Received local announcement from [fe80::16da:e9ff:fe44:de77]:21026 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:13:25.353528 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:12:56.877372 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:13:25.353312 -0500 EST}]
[3GABB] 2015/02/21 15:13:25.465953 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.11:21025 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:13:25.466225 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:13:25.466004 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:13:25.353312 -0500 EST}]
[3GABB] 2015/02/21 15:13:54.408398 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:13:56.276834 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.11:21025 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:13:56.277111 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:13:56.276896 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:13:25.353312 -0500 EST}]
[3GABB] 2015/02/21 15:13:56.277350 discover.go:308: DEBUG: discover: Received local announcement from [fe80::16da:e9ff:fe44:de77]:21026 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:13:56.277584 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:13:56.276896 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:13:56.277382 -0500 EST}]
[3GABB] 2015/02/21 15:14:22.571650 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:14:25.172341 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.11:21025 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:14:25.172669 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:14:25.172419 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:13:56.277382 -0500 EST}]
[3GABB] 2015/02/21 15:14:26.668843 discover.go:308: DEBUG: discover: Received local announcement from [fe80::16da:e9ff:fe44:de77]:21026 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:14:26.669250 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:14:25.172419 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:14:26.668976 -0500 EST}]
[3GABB] 2015/02/21 15:14:51.780268 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.12:21025 for 3GABBM2-3VSVSCX-3NCRKU6-3YPWTXU-BIGDRRT-FWGYHO4-U3T26V6-MOBFKAF
[3GABB] 2015/02/21 15:14:56.260530 discover.go:308: DEBUG: discover: Received local announcement from 192.168.1.11:21025 for IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7
[3GABB] 2015/02/21 15:15:56.478312 discover.go:358: DEBUG: discover: Caching IZKLNJ4-TVBF6HD-FFQ3LLO-LNMVIYD-L64REVU-EQUKC7I-RABG2SU-5W4IHQ7 addresses: [{192.168.1.11:22000 2015-02-21 15:15:56.478072 -0500 EST} {[fe80::16da:e9ff:fe44:de77]:22000 2015-02-21 15:15:56.477163 -0500 EST}]
Panic at 2015-02-21T15:16:03-05:00
fatal error: out of memory

goroutine 13 [running]:

	:0

	:0

	:0

	:0
github_com_syndtr_gosnappy_snappy.Encode
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/gosnappy/snappy/encode.go:104
github_com_syndtr_goleveldb_leveldb_table.writeBlock.pN48_github_com_syndtr_goleveldb_leveldb_table.Writer
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:171
github_com_syndtr_goleveldb_leveldb_table.finishBlock.pN48_github_com_syndtr_goleveldb_leveldb_table.Writer
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:225
github_com_syndtr_goleveldb_leveldb_table.Append.pN48_github_com_syndtr_goleveldb_leveldb_table.Writer
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:258
github_com_syndtr_goleveldb_leveldb.append.pN43_github_com_syndtr_goleveldb_leveldb.tWriter
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:481
github_com_syndtr_goleveldb_leveldb.createFrom.pN40_github_com_syndtr_goleveldb_leveldb.tOps
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:324
github_com_syndtr_goleveldb_leveldb.flush.pN40_github_com_syndtr_goleveldb_leveldb.cMem
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:81
leveldb.$nested12
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:323
github_com_syndtr_goleveldb_leveldb.run.pN58_github_com_syndtr_goleveldb_leveldb.compactionTransactFunc
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:271
github_com_syndtr_goleveldb_leveldb.compactionTransact.pN38_github_com_syndtr_goleveldb_leveldb.DB
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:215
github_com_syndtr_goleveldb_leveldb.compactionTransactFunc.pN38_github_com_syndtr_goleveldb_leveldb.DB
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:282
github_com_syndtr_goleveldb_leveldb.memCompaction.pN38_github_com_syndtr_goleveldb_leveldb.DB
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:320
github_com_syndtr_goleveldb_leveldb.mCompaction.pN38_github_com_syndtr_goleveldb_leveldb.DB
	/build/buildd/syncthing-0.10.20/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:763

	:0

	:0

	:0

	:0
panic during panic
```

**Comment by AudriusButkevicius** [comment]
So first of all, I suggest you try an official release, as yours seems to be compiled using xgcc.
Secondly, on the device in question, you might want to remove the index directory and try again.

I know that 32bit systems are limited to 512MB of RAM in the go runtime, but that should be enough.
Perhaps you should also not use the UI while it's performing the initial sync, as that swallows up quite a bit of RAM too.

**Comment by redoranges** [comment]
ok i ditched the PPA, cleared my index and ran w/o GUI and so far so good 
I dont see the same memory climb i did last time
aulthough my transfer rate is only around 8MB/s and neither CPU is maxed out.
But that is anohter issue, i guess this bug is irrelavant unless trying to use the PPA

**Comment by calmh** [comment]
Yeah, not sure what the compilation did there, but it seems nothing good.
