### ISSUE TITLE
panic: interface conversion: *iterator.emptyIterator is not iterator.ErrorCallbackSetter: missing method SetErrorCallback

### ISSUE THREAD

**Issue by terxw** [syncthing/syncthing#1414]
I cannot get my syncthing running, after i runn it i get this:
```
[M4FOU] 15:48:33 INFO: syncthing v0.10.24 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-03-01 20:51:56 UTC
[M4FOU] 15:48:33 INFO: My ID:
...
Panic at 2015-03-07T15:48:34+01:00
panic: interface conversion: *iterator.emptyIterator is not iterator.ErrorCallbackSetter: missing method SetErrorCallback

goroutine 1 [running]:
```
when i try ubuntu14.04/LM 17 version 0.10.20-3 I get:
```
syncthing --logflags="31"                                                                                                                                              
[monitor] 2015/03/07 16:04:56.980766 monitor.go:104: INFO: Starting syncthing
[M4FOU] 2015/03/07 16:04:59.174949 main.go:401: INFO: syncthing v0.10.20 (xgcc (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2 linux-amd64 default) niklas@Niklas-Netbook 2015-01-13
 16:27:47 UTC
[M4FOU] 2015/03/07 16:04:59.175384 main.go:402: INFO: My ID: 
[M4FOU] 2015/03/07 16:04:59.179310 main.go:494: FATAL: Cannot open database: file missing [file=MANIFEST-000000] - Is another copy of Syncthing already running?
[monitor] 2015/03/07 16:04:59.181190 monitor.go:157: INFO: Syncthing exited: exit status 1
[monitor] 2015/03/07 16:05:00.181671 monitor.go:104: INFO: Starting syncthing
[M4FOU] 2015/03/07 16:05:02.519873 main.go:401: INFO: syncthing v0.10.20 (xgcc (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2 linux-amd64 default) niklas@Niklas-Netbook 2015-01-13
 16:27:47 UTC
[M4FOU] 2015/03/07 16:05:02.520632 main.go:402: INFO: My ID: 
[M4FOU] 2015/03/07 16:05:02.524107 main.go:494: FATAL: Cannot open database: file missing [file=MANIFEST-000000] - Is another copy of Syncthing already running?
[monitor] 2015/03/07 16:05:02.525567 monitor.go:157: INFO: Syncthing exited: exit status 1
[monitor] 2015/03/07 16:05:03.525888 monitor.go:104: INFO: Starting syncthing
[M4FOU] 2015/03/07 16:05:05.731751 main.go:401: INFO: syncthing v0.10.20 (xgcc (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2 linux-amd64 default) niklas@Niklas-Netbook 2015-01-13
 16:27:47 UTC
[M4FOU] 2015/03/07 16:05:05.732217 main.go:402: INFO:
[M4FOU] 2015/03/07 16:05:05.736053 main.go:494: FATAL: Cannot open database: file missing [file=MANIFEST-000000] - Is another copy of Syncthing already running?
[monitor] 2015/03/07 16:05:05.737808 monitor.go:157: INFO: Syncthing exited: exit status 1
[monitor] 2015/03/07 16:05:06.738112 monitor.go:104: INFO: Starting syncthing
[M4FOU] 2015/03/07 16:05:08.963944 main.go:401: INFO: syncthing v0.10.20 (xgcc (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2 linux-amd64 default) niklas@Niklas-Netbook 2015-01-13
 16:27:47 UTC
[M4FOU] 2015/03/07 16:05:08.964452 main.go:402: INFO: My ID:
[M4FOU] 2015/03/07 16:05:08.969905 main.go:494: FATAL: Cannot open database: file missing [file=MANIFEST-000000] - Is another copy of Syncthing already running?
[monitor] 2015/03/07 16:05:08.971597 monitor.go:157: INFO: Syncthing exited: exit status 1
[monitor] 2015/03/07 16:05:09.971834 monitor.go:85: WARNING: 4 restarts in 12.991094s; not retrying further
```
and no, no other copy of syncthing is running

**Comment by AudriusButkevicius** [comment]
Can you provide the larger portion of the stack trace, in order to understand where this is happening?
(Whatever followed after goroutine 1)

**Comment by terxw** [comment]
Here is info with STTRACE="all"
```
STTRACE="all" && export STTRACE && syncthing
17:57:49 DEBUG: subscribe Unknown
[monitor] 2015/03/07 17:57:49.191447 monitor.go:104: INFO: Starting syncthing
[monitor] 2015/03/07 17:57:49.193298 events.go:178: DEBUG: poll 1m0s
17:57:49 DEBUG: subscribe Unknown
2015/03/07 17:57:49.201998 events.go:178: DEBUG: poll 1m0s
2015/03/07 17:57:49.202180 events.go:126: DEBUG: log 1 Starting map[home:$HOME/.config/syncthing]
2015/03/07 17:57:49.202261 events.go:178: DEBUG: poll 1m0s
[M4FOU] 2015/03/07 17:57:50.092792 main.go:404: INFO: syncthing v0.10.24 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-03-01 20:51:56 UTC    [5/524]
[M4FOU] 2015/03/07 17:57:50.092908 main.go:405: INFO: My ID: 
panic: interface conversion: *iterator.emptyIterator is not iterator.ErrorCallbackSetter: missing method SetErrorCallback
[monitor] 2015/03/07 17:57:50.303004 monitor.go:182: WARNING: Panic detected, writing to "$HOME/.config/syncthing/panic-20150307-175750.log"
[monitor] 2015/03/07 17:57:50.303044 monitor.go:183: WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 2015/03/07 17:57:50.304249 monitor.go:157: INFO: Syncthing exited: exit status 2
[monitor] 2015/03/07 17:57:51.304529 monitor.go:104: INFO: Starting syncthing
17:57:51 DEBUG: subscribe Unknown
2015/03/07 17:57:51.316325 events.go:178: DEBUG: poll 1m0s
2015/03/07 17:57:51.316413 events.go:126: DEBUG: log 1 Starting map[home:$HOME/.config/syncthing]
2015/03/07 17:57:51.316500 events.go:178: DEBUG: poll 1m0s
[M4FOU] 2015/03/07 17:57:52.213567 main.go:404: INFO: syncthing v0.10.24 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-03-01 20:51:56 UTC
[M4FOU] 2015/03/07 17:57:52.213699 main.go:405: INFO: My ID: 
panic: interface conversion: *iterator.emptyIterator is not iterator.ErrorCallbackSetter: missing method SetErrorCallback
[monitor] 2015/03/07 17:57:52.455135 monitor.go:182: WARNING: Panic detected, writing to "$HOME/.config/syncthing/panic-20150307-175752.log"
[monitor] 2015/03/07 17:57:52.455173 monitor.go:183: WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 2015/03/07 17:57:52.456060 monitor.go:157: INFO: Syncthing exited: exit status 2
[monitor] 2015/03/07 17:57:53.456270 monitor.go:104: INFO: Starting syncthing
17:57:53 DEBUG: subscribe Unknown
2015/03/07 17:57:53.463674 events.go:126: DEBUG: log 1 Starting map[home:$HOME/.config/syncthing]
2015/03/07 17:57:53.463832 events.go:178: DEBUG: poll 1m0s
2015/03/07 17:57:53.463881 events.go:178: DEBUG: poll 1m0s
[M4FOU] 2015/03/07 17:57:54.276520 main.go:404: INFO: syncthing v0.10.24 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-03-01 20:51:56 UTC
[M4FOU] 2015/03/07 17:57:54.276670 main.go:405: INFO: My ID: 
panic: interface conversion: *iterator.emptyIterator is not iterator.ErrorCallbackSetter: missing method SetErrorCallback
[monitor] 2015/03/07 17:57:54.504261 monitor.go:182: WARNING: Panic detected, writing to "$HOME/.config/syncthing/panic-20150307-175754.log"
[monitor] 2015/03/07 17:57:54.504292 monitor.go:183: WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 2015/03/07 17:57:54.505309 monitor.go:157: INFO: Syncthing exited: exit status 2
[monitor] 2015/03/07 17:57:55.505535 monitor.go:104: INFO: Starting syncthing
17:57:55 DEBUG: subscribe Unknown
2015/03/07 17:57:55.517034 events.go:178: DEBUG: poll 1m0s
2015/03/07 17:57:55.517178 events.go:126: DEBUG: log 1 Starting map[home:$HOME/.config/syncthing]
2015/03/07 17:57:55.517500 events.go:178: DEBUG: poll 1m0s
[M4FOU] 2015/03/07 17:57:56.352335 main.go:404: INFO: syncthing v0.10.24 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-03-01 20:51:56 UTC
[M4FOU] 2015/03/07 17:57:56.352473 main.go:405: INFO: My ID: 
panic: interface conversion: *iterator.emptyIterator is not iterator.ErrorCallbackSetter: missing method SetErrorCallback
[monitor] 2015/03/07 17:57:56.564335 monitor.go:182: WARNING: Panic detected, writing to "$HOME/.config/syncthing/panic-20150307-175756.log"
[monitor] 2015/03/07 17:57:56.564371 monitor.go:183: WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 2015/03/07 17:57:56.565660 monitor.go:157: INFO: Syncthing exited: exit status 2

```

**Comment by calmh** [comment]
https://github.com/syndtr/goleveldb/issues/101

However, the root cause seems to be your index has been corrupted. Removing this and starting over would most likely resolv it, although it may be good if you keep a copy (for future troubleshooting if this needs to be narrowed down), and if you know something weird happened that would have caused the corruption to start with (i.e. machine crashed, power outage, ...)?

**Comment by terxw** [comment]
Thank you, the problem disapeared!
