### ISSUE TITLE
Version 0.10.29 panic: leveldb/table: corruption on data-block

### ISSUE THREAD

**Issue by Krixvar** [syncthing/syncthing#1517]
It crashed and spit out a handful of logs, then did the same thing when I tried restarting it. Here's the most recent: 

[ZD35Z] 23:43:04 INFO: syncthing v0.10.29 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-03-22 14:09:14 UTC
[ZD35Z] 23:43:04 INFO: My ID: ZD35Z6Y-FDD7LNI-B4ZLRSU-ECXXMST-WTL6V3D-67JYJSC-E2TIY4F-OBALUA5
...
Panic at 2015-03-23T23:43:05-04:00
panic: leveldb/table: corruption on data-block (pos=1572979): checksum mismatch, want=0x79246780 got=0xd7413194 [file=009416.ldb]

goroutine 1 [running]:
github.com/syncthing/syncthing/internal/db.ldbCheckGlobals(0xc208104160, 0xc208f54428, 0x5, 0x8)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb.go:1030 +0xd46
github.com/syncthing/syncthing/internal/db.NewFileSet(0xc208102480, 0x5, 0xc208104160, 0xc208971e70)
	/go/src/github.com/syncthing/syncthing/internal/db/set.go:56 +0x1be
github.com/syncthing/syncthing/internal/model.(*Model).AddFolder(0xc208c62a80, 0xc208102480, 0x5, 0xc208061860, 0x1c, 0xc2080758c0, 0x2, 0x4, 0x0, 0x12c, ...)
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:1046 +0x19e
main.sanityCheckFolders(0xc208050b40, 0xc208c62a80)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:686 +0x173
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:519 +0x1a95
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:362 +0x20ed

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0xc20801e680, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:173 +0x3bf
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0xc20802e340)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:209 +0x48
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:203 +0x1c4

goroutine 8 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·3
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 10 [chan receive]:
github.com/syncthing/syncthing/internal/config.(*Wrapper).Serve(0xc208050b40)
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:79 +0x75
created by github.com/syncthing/syncthing/internal/config.Wrap
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:54 +0x133

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc20806e0e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc208104160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc208104160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 14 [syscall]:
syscall.Syscall(0x4a, 0x10, 0x0, 0x0, 0x201065, 0x4de4, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.Fsync(0x10, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:503 +0x55
os.(*File).Sync(0xc2092c42f8, 0x0, 0x0)
	/usr/local/go/src/os/file_posix.go:129 +0x6a
github.com/syndtr/goleveldb/leveldb/storage.fileWrap.Sync(0xc2092c42f8, 0xc20925c160, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:347 +0x3a
github.com/syndtr/goleveldb/leveldb/storage.(*fileWrap).Sync(0xc208102300, 0x0, 0x0)
	<autogenerated>:46 +0xb1
github.com/syndtr/goleveldb/leveldb.(*tWriter).finish(0xc209038240, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:504 +0x106
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).flush(0xc208fbe000, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:420 +0x55
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).run(0xc208fbe000, 0xc2081021e0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:481 +0x986
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0xc208104160, 0xa508f0, 0xb, 0x7fe90471eb00, 0xc208fbe000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:215 +0x277
github.com/syndtr/goleveldb/leveldb.(*DB).tableCompaction(0xc208104160, 0xc2082d6800, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:596 +0x10d4
github.com/syndtr/goleveldb/leveldb.(*DB).tableAutoCompaction(0xc208104160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:641 +0x50
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc208104160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:833 +0x3a0
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc208104160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc208104160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 19 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0xc208f5c030)
	/go/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:48 +0x8b8
created by github.com/syncthing/syncthing/internal/model.NewModel
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:117 +0x60c

goroutine 20 [sleep]:
github.com/syncthing/syncthing/internal/model.func·029()
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x4a
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0xd6

goroutine 21 [sleep]:
github.com/syncthing/syncthing/internal/model.func·029()
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x4a
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0xd6

goroutine 22 [select]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0xc208eca0a0, 0x68c61714000)
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153 +0x1b9
created by github.com/syncthing/syncthing/internal/ignore.New
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0xc6

goroutine 23 [select]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0xc2090072c0, 0x68c61714000)
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153 +0x1b9
created by github.com/syncthing/syncthing/internal/ignore.New
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0xc6

goroutine 24 [select]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0xc20935ceb0, 0x68c61714000)
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153 +0x1b9
created by github.com/syncthing/syncthing/internal/ignore.New
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0xc6

goroutine 25 [select]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0xc208361040, 0x68c61714000)
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153 +0x1b9
created by github.com/syncthing/syncthing/internal/ignore.New
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0xc6

**Comment by Krixvar** [comment]
Forgot to search before blindly following the console message saying to upload a log - this is probably a duplicate unless there's something else useful here.
