### ISSUE TITLE
Approximately daily crashes followed by "permission denied" mkdir tries

### ISSUE THREAD

**Issue by I3ck** [syncthing/syncthing#1571]
On one of my linux machines syncthing keeps crashing. 
```
/go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:287 +0x4c
created by github.com/syncthing/syncthing/internal/model.(*rwFolder).pullerIteration
       /go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:289 +0x720

goroutine 4767 [sleep, 15 minutes]:
github.com/syncthing/syncthing/internal/model.func·028()
       /go/src/github.com/syncthing/syncthing/internal/model/util.go:27 +0x33
created by github.com/syncthing/syncthing/internal/model.func·029
       /go/src/github.com/syncthing/syncthing/internal/model/util.go:29 +0x18f

goroutine 4918 [chan receive]:
github.com/syncthing/syncthing/internal/model.(*rwFolder).pullerRoutine(0xc208d12000, 0xc208632000, 0xc208632180)
       /go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:887 +0x7d
github.com/syncthing/syncthing/internal/model.func·015()
       /go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:287 +0x4c
created by github.com/syncthing/syncthing/internal/model.(*rwFolder).pullerIteration
       /go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:289 +0x720

goroutine 4920 [chan receive]:
github.com/syncthing/syncthing/internal/model.(*rwFolder).pullerRoutine(0xc208d12000, 0xc208632000, 0xc208632180)
       /go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:887 +0x7d
github.com/syncthing/syncthing/internal/model.func·015()
       /go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:287 +0x4c
created by github.com/syncthing/syncthing/internal/model.(*rwFolder).pullerIteration
       /go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:289 +0x720
[monitor] 01:03:58 INFO: Syncthing exited: exit status 2
[monitor] 01:03:59 INFO: Starting syncthing
01:03:59 FATAL: mkdir /home/USERNAME/.config: permission denied
[monitor] 01:03:59 INFO: Syncthing exited: exit status 1
[monitor] 01:04:00 INFO: Starting syncthing
01:04:00 FATAL: mkdir /home/USERNAME/.config: permission denied
[monitor] 01:04:00 INFO: Syncthing exited: exit status 1
[monitor] 01:04:01 INFO: Starting syncthing
01:04:01 FATAL: mkdir /home/USERNAME/.config: permission denied
[monitor] 01:04:01 INFO: Syncthing exited: exit status 1
[monitor] 01:04:02 INFO: Starting syncthing
01:04:02 FATAL: mkdir /home/USERNAME/.config: permission denied
[monitor] 01:04:02 INFO: Syncthing exited: exit status 1
[monitor] 01:04:03 WARNING: 4 restarts in 4.078084357s; not retrying further
```

`.config` is owned by the user running syncthing  
syncthing is running in its own `screen`, tho  
this happened with pretty much any version (up until 0.10.30)

**Comment by AudriusButkevicius** [comment]
That'd not the full crash log so that doesn't help. 

Also, I am not familliar with screen, but just to double check, can you provide output of `ps auxwwf | grep syncthing` and `ls -la /home/<user>/.config` when syncthing starts crashing.

**Comment by calmh** [comment]
Lacks information.
