### ISSUE TITLE
panic: runtime error: slice bounds out of range with v0.11.0-beta4

### ISSUE THREAD

**Issue by kozec** [syncthing/syncthing#1606]
Hi,

I managed to crash syncthing 8-)

<a href="http://pastebin.com/bY7wxRf4">panic log</a>

Windows 7 64bit, syncthing v0.11.0-beta4 (go1.4.2 windows-386 default)
~~Probably caused by calling /rest/system/config~~
... or not, it happens every time when I start daemon, right after connection to ~~older daemon~~ is initiated.

edit no2: And did I mentioned that it connects to _itself_?
```
[WEVFD] 09:29:08 INFO: Established secure connection to XXX-XX-XXX at 10.148.1.55:61618-ip:22000
```

where `10.148.1.55` is address of this very machine that has daemon crashing. There is no other ST daemon running around.

**Comment by calmh** [comment]
Neat... Looks like a bug in the XDR package.

```
Panic at 2015-04-08T09:29:08+02:00
panic: runtime error: slice bounds out of range
 
goroutine 81 [running]:
github.com/calmh/xdr.(*Reader).ReadBytesMaxInto(0x13570480, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/calmh/xdr/reader.go:79 +0x58b
github.com/calmh/xdr.(*Reader).ReadStringMax(0x13570480, 0x40, 0x0, 0x0)
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/calmh/xdr/reader.go:41 +0x58
github.com/syncthing/protocol.(*Option).DecodeXDRFrom(0x12aec600, 0x13570480, 0x0, 0x0)
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:951 +0x40
github.com/syncthing/protocol.(*Device).DecodeXDRFrom(0x134a6b40, 0x13570480, 0x0, 0x0)
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:870 +0x195
github.com/syncthing/protocol.(*Folder).DecodeXDRFrom(0x1345a140, 0x13570480, 0x0, 0x0)
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:755 +0x11e
github.com/syncthing/protocol.(*ClusterConfigMessage).DecodeXDRFrom(0x12dabd9c, 0x13570480, 0x0, 0x0)
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:638 +0x164
github.com/syncthing/protocol.(*ClusterConfigMessage).UnmarshalXDR(0x12dabd9c, 0x12b4c900, 0x204, 0x204, 0x0, 0x0)
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:629 +0x117
github.com/syncthing/protocol.(*rawConnection).readMessage(0x13850000, 0x0, 0x1, 0x0, 0x7301, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go:450 +0xb8b
github.com/syncthing/protocol.(*rawConnection).readerLoop(0x13850000, 0x0, 0x0)
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go:295 +0x116
created by github.com/syncthing/protocol.NewConnection
        /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go:167 +0x283
```

**Comment by calmh** [comment]
Ah. I think this is a 32 bit only bug, caused by talking to a v0.10 syncthing on the other side.

**Comment by calmh** [comment]
Also,

> Windows 7 64bit, syncthing v0.11.0-beta4 (go1.4.2 windows-386 default)

Don't run the 386 build on 64 bit Windows. That sucks. :)

**Comment by kozec** [comment]
> Don't run the 386 build on 64 bit Windows. That sucks. :)

I just needed to check renamed API calls and didn't actually cared which version will I grab :)

**Comment by calmh** [comment]
And in this case it nailed a bug, so that's something. :)
