### ISSUE TITLE
SIGILL during shutdown

### ISSUE THREAD

**Issue by domkun** [syncthing/syncthing#1876]
I get a SIGILL when shutting down syncthing with CTRL+C or strangely when hitting Exit in the Android App running on a different System.

syncthing runs on an ARM v5 CPU on a NAS. 

When stopping syncthing with CTRL+C I get the SIGILL. When I connect my Android Phone with the Android App and tap on "Exit" in the App the syncthing instance running on the NAS gets also the SIGILL.

Here is the output:
```
[monitor] 23:56:06 INFO: Starting syncthing
[CJN7V] 23:56:47 INFO: syncthing v0.11.6+8-gd220522 (go1.4.2 linux-arm default) unknown-user@syncthing-builder 2015-05-26 14:27:26 UTC
[CJN7V] 23:56:47 INFO: My ID: CJN7VA3-TL4Y7NB-GBR4DGA-FUECZCC-YLTHBE3-BVUJLGI-6AMWLKI-542WQQP
[CJN7V] 23:56:47 INFO: Database block cache capacity 8192 KiB
[CJN7V] 23:56:47 INFO: Starting deadlock detector with 20m0s timeout
[CJN7V] 23:56:47 INFO: Starting local discovery announcements
[CJN7V] 23:56:47 INFO: Local discovery over IPv6 unavailable
[CJN7V] 23:56:47 OK: Ready to synchronize default (read-write)
[CJN7V] 23:56:47 OK: Ready to synchronize test (read-write)
[CJN7V] 23:56:47 INFO: Device CJN7VA3-XXXXXXX-GBR4DGA-FUECZCC-YLTHBE3-BVUJLGI-6AMWLKI-542WQQP is "HS-DHGL914" at [dynamic]
[CJN7V] 23:56:47 INFO: Device ES6KVCG-47VPGAI-A2BB3QT-GYF4UUS-XXXXXXX-HGKK2LE-YCZGUWW-ECHBJQN is "Nexus 4" at [dynamic]
[CJN7V] 23:56:47 INFO: No automatic upgrades; v0.11.6+8-gd220522 is not a release version.
[CJN7V] 23:56:48 INFO: Completed initial scan (rw) of folder default
[CJN7V] 23:56:48 INFO: Completed initial scan (rw) of folder test
SIGILL: illegal instruction
PC=0xffff0514

goroutine 8 [syscall]:
runtime.notetsleepg(0x826534, 0x3a6f07b8, 0x0, 0x0)
        /usr/local/go/src/runtime/lock_futex.go:201 +0x58 fp=0x10a15f8c sp=0x10a15f74
runtime.timerproc()
        /usr/local/go/src/runtime/time.go:207 +0x144 fp=0x10a15fec sp=0x10a15f8c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:1322 +0x4 fp=0x10a15fec sp=0x10a15fec
created by runtime.addtimerLocked
        /usr/local/go/src/runtime/time.go:113 +0x230

goroutine 1 [select]:
main.monitorMain()
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:115 +0x1920
main.main()
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:266 +0x1ca0

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1c
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x40

goroutine 7 [chan receive]:
main.trackCPUUsage()
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x120
created by main.init·2
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x34

goroutine 9 [syscall]:
syscall.Syscall(0x3, 0x4, 0x10aee000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_arm.s:17 +0x8
syscall.read(0x4, 0x10aee000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_arm.go:867 +0x80
syscall.Read(0x4, 0x10aee000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:136 +0x54
os.(*File).read(0x10a0a6e0, 0x10aee000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:191 +0x5c
os.(*File).Read(0x10a0a6e0, 0x10aee000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x80
bufio.(*Reader).fill(0x10a30990)
        /usr/local/go/src/bufio/bufio.go:97 +0x1d8
bufio.(*Reader).ReadSlice(0x10a30990, 0x442e0a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:295 +0x2a4
bufio.(*Reader).ReadBytes(0x10a30990, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:374 +0x88
bufio.(*Reader).ReadString(0x10a30990, 0x10a0a60a, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:414 +0x4c
main.copyStderr(0x40011c88, 0x10a0a6e0, 0x40011be8, 0x10a0a0e0)
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:169 +0x58
main.func·012()
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:113 +0x88
created by main.monitorMain
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:115 +0x1084

goroutine 10 [syscall]:
syscall.Syscall(0x3, 0x6, 0x10aef000, 0x1000, 0x42, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_arm.s:17 +0x8
syscall.read(0x6, 0x10aef000, 0x1000, 0x1000, 0x42, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_arm.go:867 +0x80
syscall.Read(0x6, 0x10aef000, 0x1000, 0x1000, 0x42, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:136 +0x54
os.(*File).read(0x10a0a708, 0x10aef000, 0x1000, 0x1000, 0x50, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:191 +0x5c
os.(*File).Read(0x10a0a708, 0x10aef000, 0x1000, 0x1000, 0x4000412c, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x80
bufio.(*Reader).fill(0x10a309c0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1d8
bufio.(*Reader).ReadSlice(0x10a309c0, 0x4fc0a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:295 +0x2a4
bufio.(*Reader).ReadBytes(0x10a309c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:374 +0x88
bufio.(*Reader).ReadString(0x10a309c0, 0x10a1050a, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:414 +0x4c
main.copyStdout(0x40011c88, 0x10a0a708, 0x40011be8, 0x10a0a0e0)
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:210 +0x48
main.func·013()
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:119 +0x88
created by main.monitorMain
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:115 +0x1188

goroutine 11 [semacquire]:
sync.(*WaitGroup).Wait(0x10a378a0)
        /usr/local/go/src/sync/waitgroup.go:132 +0x194
main.func·014()
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:126 +0x54
created by main.monitorMain
        /go/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:115 +0x12a4

trap    0x0
error   0x9000ad
oldmask 0xfffbfef7
r0      0x1
r1      0x1
r2      0x1
r3      0x0
r4      0x10a005a0
r5      0x2
r6      0x803de8
r7      0xad
r8      0x826bd8
r9      0x0
r10     0x10a005a0
fp      0x82d37c
ip      0x0
sp      0x10a09f00
lr      0x77158
pc      0xffff0514
cpsr    0x20000010
fault   0x0
```

CPU Info:

````
root@HS-DHGL914:~# cat /proc/cpuinfo 
Processor       : ARM926EJ-Sid(wb) rev 0 (v5l)
BogoMIPS        : 266.24
Features        : swp half thumb fastmult edsp java 
CPU implementer : 0x41
CPU architecture: 5TEJ
CPU variant     : 0x0
CPU part        : 0x926
CPU revision    : 0
Cache type      : write-back
Cache clean     : cp15 c7 ops
Cache lockdown  : format C
Cache format    : Harvard
I size          : 32768
I assoc         : 1
I line length   : 32
I sets          : 1024
D size          : 32768
D assoc         : 1
D line length   : 32
D sets          : 1024

Hardware        : MV-88fxx81
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by Zillode** [comment]
Dup of https://github.com/syncthing/syncthing/issues/1132, will be fixed in the next release of syncthing-android.

**Comment by calmh** [comment]
unknown-user@syncthing-builder sounds like our build image though, not the android one? Or does that one identify the same?

**Comment by domkun** [comment]
Yes, its the official ARM download from syncthing.net. As stated, I have got 2 instances up, one on the NAS (ARM download from syncthing.net) and the Android App (from App Store) on my Phone.



Now what happens is, that every time I hit "Exit" in the Android App the syncthing instance on the NAS gets the SIGILL, also when I restart the Android syncthing instance, the instance on the NAS gets the SIGILL.

Also when I press CTRL+C in the console on the NAS I get the SIGILL, as well when pressing the "Restart" button in the Web UI.

**Comment by Zillode** [comment]
(tag is `unknown-user@android.syncthing.net` for android)

**Comment by calmh** [comment]
Can you run syncthing on your nas with `GOTRACEBACK=crash`, cause the crash, and upload the resulting core file (toghether with the actual binary used) somewhere?

**Comment by domkun** [comment]
This happened with the latest build from jenkins (http://build.syncthing.net/job/syncthing/lastSuccessfulBuild/artifact/syncthing-linux-arm-v0.11.6+8-gd220522.tar.gz) and with the latest release version (https://github.com/syncthing/syncthing/releases/download/v0.11.6/syncthing-linux-arm-v0.11.6.tar.gz).

Will upload the core file when I am back from work.

**Comment by domkun** [comment]
OK, all I got is this: https://drive.google.com/file/d/0BxKPfveF80s0S1o3UkVnTkdldE0/view?usp=sharing

**Comment by calmh** [comment]
I couldn't find the issue, and the Go compiler has changed quite a lot in the meantime. If the problem persists, someone with an ARM device will need to look at it and see if it can be reproduced.
