### ISSUE TITLE
Verbose logging fails after a while

### ISSUE THREAD

**Issue by alex2108** [syncthing/syncthing#1921]
Version: syncthing v0.11.8 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-06-07 10:57:26 UTC

at the beginning it worked like you can see on the first part and failed service repeats until I stop syncthing.
```
[TT3PO] 14:19:27 VERBOSE: Completion for folder "cloud" on device S44AE6E-CZKCLXU-RVUTU3Z-NKYABMC-3EWI5JZ-NZOZJZ4-3QL3VX7-J4LTBQW is 100%
[TT3PO] 14:19:27 VERBOSE: Folder "PIA" is now syncing
[TT3PO] 14:19:27 VERBOSE: Device AQ32RMC-RD2L36J-WOZJR6B-GSWUONM-OJ5GYW2-JUYJF5R-G26MTSD-42GJSQX sent an index update for "pia-solardata" with 1 items
[TT3PO] 14:19:27 VERBOSE: Started syncing "PIA" / "MATLAB/PIA_control/log/log-2015-06-08.txt" (update file)
[TT3PO] 14:19:27 INFO: Failed service '&main.verboseSvc{stop:(chan struct {})(0xc208066480), started:(chan struct {})(0xc208066540)}' (1.000000 failures of 5.000000), restarting: true, error: runtime error: invalid memory address or nil pointer dereference, stacktrace: goroutine 10 [running]:
github.com/thejerf/suture.func·006()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:510 +0xc4
main.(*verboseSvc).formatEvent(0xc20802afe0, 0x8b, 0xecd077f4f, 0x36ea3498, 0xe0b140, 0x400, 0x88ebe0, 0xc20e942510, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:109 +0x18de
main.(*verboseSvc).Serve(0xc20802afe0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:40 +0x15c
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

[TT3PO] 14:19:27 INFO: Failed service '&main.verboseSvc{stop:(chan struct {})(0xc208066480), started:(chan struct {})(0xc208066540)}' (1.999838 failures of 5.000000), restarting: true, error: "close of closed channel", stacktrace: goroutine 277 [running]:
github.com/thejerf/suture.func·006()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:510 +0xc4
main.(*verboseSvc).Serve(0xc20802afe0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:35 +0x87
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

[TT3PO] 14:19:27 INFO: Failed service '&main.verboseSvc{stop:(chan struct {})(0xc208066480), started:(chan struct {})(0xc208066540)}' (2.999833 failures of 5.000000), restarting: true, error: "close of closed channel", stacktrace: goroutine 278 [running]:
github.com/thejerf/suture.func·006()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:510 +0xc4
main.(*verboseSvc).Serve(0xc20802afe0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:35 +0x87
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

[TT3PO] 14:19:27 INFO: Failed service '&main.verboseSvc{stop:(chan struct {})(0xc208066480), started:(chan struct {})(0xc208066540)}' (3.999343 failures of 5.000000), restarting: true, error: "close of closed channel", stacktrace: goroutine 279 [running]:
github.com/thejerf/suture.func·006()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:510 +0xc4
main.(*verboseSvc).Serve(0xc20802afe0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:35 +0x87
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

[TT3PO] 14:19:27 INFO: Failed service '&main.verboseSvc{stop:(chan struct {})(0xc208066480), started:(chan struct {})(0xc208066540)}' (4.999335 failures of 5.000000), restarting: true, error: "close of closed channel", stacktrace: goroutine 280 [running]:
github.com/thejerf/suture.func·006()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:510 +0xc4
main.(*verboseSvc).Serve(0xc20802afe0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:35 +0x87
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

[TT3PO] 14:19:27 INFO: Entering the backoff state.
```

**Comment by calmh** [comment]
Woops
