### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by Albirew** [syncthing/syncthing#2052]
I don't know when but one of my syncthing servers stopped working, and starting it manually give me this error: **panic: runtime error: makeslice: len out of range**

_uname -a: Linux vanaheim 4.0.0-2-686-pae #1 SMP Debian 4.0.4-1 (2015-05-26) i686 GNU/Linux_

Here the full panic log:
```log
[KUAXV] 15:56:31 INFO: syncthing v0.11.13 (go1.4.2 linux-386 default) unknown-user@syncthing-builder 2015-07-05 17:44:55 UTC
[KUAXV] 15:56:31 INFO: My ID: ******
[KUAXV] 15:56:31 INFO: Database block cache capacity 8192 KiB
...
Panic at 2015-07-11T15:56:31+02:00
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/syncthing/protocol.(*Vector).DecodeXDRFrom(0x18a10a80, 0xb77a83d0, 0x1952a560, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/vector_xdr.go:31 +0x62
github.com/syncthing/syncthing/internal/db.(*fileVersion).DecodeXDRFrom(0x18a10a80, 0x1952a560, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb_xdr.go:85 +0x6e
github.com/syncthing/syncthing/internal/db.(*versionList).DecodeXDRFrom(0x18a26df0, 0x1952a560, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb_xdr.go:164 +0x10d
github.com/syncthing/syncthing/internal/db.(*versionList).UnmarshalXDR(0x18a26df0, 0x18ec5a00, 0xdc, 0x100, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb_xdr.go:154 +0x117
github.com/syncthing/syncthing/internal/db.ldbCheckGlobals(0x18aa8e00, 0x18e1e8e0, 0xa, 0x10)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb.go:1031 +0x4fc
github.com/syncthing/syncthing/internal/db.NewFileSet(0x18ac49f0, 0xa, 0x18aa8e00, 0x18a2711c)
	/go/src/github.com/syncthing/syncthing/internal/db/set.go:55 +0x1fe
github.com/syncthing/syncthing/internal/model.(*Model).AddFolder(0x18c810e0, 0x18ac49f0, 0xa, 0x18ac3a60, 0x1f, 0x18af1080, 0x4, 0x4, 0x0, 0x3c, ...)
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:1170 +0x14d
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:621 +0x1f5f
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:383 +0x1c04

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x34

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x11a
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 8 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0x18ad8180)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:411 +0xcfe
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x2f

goroutine 10 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0x18a38e00, 0xf8475800, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:186 +0x2ee
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0x18a409f0)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:223 +0x44
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:217 +0x20d

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x18aac2c0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x1c5
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x1bb

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x18aa8e00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x4c0
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x6da

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x18aa8e00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x11d
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x6ef

goroutine 14 [runnable]:
os.epipecheck(0x194045e0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:58
os.(*File).Write(0x194045e0, 0x1964c000, 0x4e4, 0x67e5, 0x4e4, 0x0, 0x0)
	/usr/local/go/src/os/file.go:147 +0xc9
github.com/syndtr/goleveldb/leveldb/table.(*Writer).writeBlock(0x18aa0200, 0x18aa022c, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:190 +0x35a
github.com/syndtr/goleveldb/leveldb/table.(*Writer).finishBlock(0x18aa0200, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:225 +0x72
github.com/syndtr/goleveldb/leveldb/table.(*Writer).Append(0x18aa0200, 0x194bc120, 0xf2, 0x120, 0x196a0fde, 0xbc, 0x944, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:258 +0x2f0
github.com/syndtr/goleveldb/leveldb.(*tWriter).append(0x18f07fb0, 0x194bc120, 0xf2, 0x120, 0x196a0fde, 0xbc, 0x944, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:485 +0x25f
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).appendKV(0x18aa6a80, 0x194bc120, 0xf2, 0x120, 0x196a0fde, 0xbc, 0x944, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:368 +0x1bb
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).run(0x18aa6a80, 0x18aaa448, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:486 +0x6bd
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0x18aa8e00, 0x85352f8, 0xb, 0xb77a8780, 0x18aa6a80)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:164 +0x212
github.com/syndtr/goleveldb/leveldb.(*DB).tableCompaction(0x18aa8e00, 0x194185a0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:552 +0xe02
github.com/syndtr/goleveldb/leveldb.(*DB).tableAutoCompaction(0x18aa8e00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:597 +0x4a
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x18aa8e00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:789 +0x2e4
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x89d

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x18aa8e00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x221
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x8b2

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x18aa8e00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x153
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x8c7

goroutine 18 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0x18d57ac0)
	/go/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:52 +0x6e2
created by github.com/syncthing/syncthing/internal/model.NewModel
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:144 +0xa5d
```

**Comment by calmh** [comment]
Interesting. Database seems corrupt, or at least the data we get back from it. But that should be caught by the leveldb checksums, I think. 

Removing the index-v0.11.0.db dir in the config dir is your workaround to get back up and running.

**Comment by Albirew** [comment]
This indeed works now, thanks for the workaround.
