### ISSUE TITLE
Removing and re-adding the same folder panics

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#2262]

**Comment by calmh** [comment]
For the record:

```
2015/09/11 14:13:17 http: panic serving 127.0.0.1:60104: cannot start already running folder s12
goroutine 117 [running]:
net/http.(*conn).serve.func1(0xc8205604d0, 0x19abb20, 0xc8204cc760)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/syncthing/syncthing/lib/model.(*Model).StartFolderRW(0xc820082120, 0xc8204f7e50, 0x3)
	/Users/jb/src/github.com/syncthing/syncthing/lib/model/model.go:170 +0x271
github.com/syncthing/syncthing/lib/model.(*Model).CommitConfiguration(0xc820082120, 0xc, 0xc820188580, 0x2, 0x4, 0xc8201801a0, 0x3, 0x4, 0x1, 0xc820679420, ...)
	/Users/jb/src/github.com/syncthing/syncthing/lib/model/model.go:1809 +0x1f05
github.com/syncthing/syncthing/lib/config.(*Wrapper).replaceLocked(0xc82021e000, 0xc, 0xc82054a2c0, 0x3, 0x4, 0xc820ea0340, 0x3, 0x4, 0x1, 0xc8204eca70, ...)
	/Users/jb/src/github.com/syncthing/syncthing/lib/config/wrapper.go:166 +0x797
github.com/syncthing/syncthing/lib/config.(*Wrapper).Replace(0xc82021e000, 0xc, 0xc82054a2c0, 0x3, 0x4, 0xc820ea0340, 0x3, 0x4, 0x1, 0xc8204eca70, ...)
	/Users/jb/src/github.com/syncthing/syncthing/lib/config/wrapper.go:141 +0xf1
main.(*apiSvc).postSystemConfig(0xc820154180, 0x19abc78, 0xc82054d130, 0xc8204d4a80)
	/Users/jb/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:565 +0x535
main.(*apiSvc).(main.postSystemConfig)-fm(0x19abc78, 0xc82054d130, 0xc8204d4a80)
	/Users/jb/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:164 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc8200117d0, 0x19abc78, 0xc82054d130, 0xc8204d4a80)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
```

**Comment by marrie** [comment]
Kind of looks  like this issue I submitted [here](https://github.com/syncthing/syncthing/issues/2280) but not sure.  If not please disregard.

**Comment by calmh** [comment]
(This is at least partly user error, as removing a folder currently requires restart.)

**Comment by jpjp** [comment]
A crash can never be a user error...

**Comment by calmh** [comment]
It doesn't actually crash, it just prints a panic on the console. But yes, you're right. The change requires a restart, and it works after the restart.
