### ISSUE TITLE
syncthing fails to start due to data corruption

### ISSUE THREAD

**Issue by davidsblom** [syncthing/syncthing#2479]
version: syncthing v0.12.3
OS: Mac OS X 10.11.1
Started the executable in the terminal. 

log of syncthing:

```
[monitor] 11:37:38 INFO: Starting syncthing
[4GM3D] 11:37:39 INFO: syncthing v0.12.3 "Beryllium Bedbug" (go1.4.3 darwin-amd64 default) unknown-user@build2.syncthing.net 2015-11-15 17:15:10 UTC
[4GM3D] 11:37:39 INFO: My ID: 4GM3D6Y-WAGWPHJ-WEHSMNJ-PIZIKMG-TIARORW-VEKZ4OQ-3ZCQEMJ-MARUKQX
[4GM3D] 11:37:39 INFO: Single thread hash performance is ~182 MB/s
panic: leveldb/table: corruption on data-block (pos=1799293): checksum mismatch, want=0xd0149b1c got=0x374c90a1 [file=014483.ldb]
[monitor] 11:37:39 WARNING: Panic detected, writing to "/Users/davidblom/Library/Application Support/Syncthing/panic-20151117-113739.log"
[monitor] 11:37:39 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 11:37:39 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 11:37:39 INFO: Syncthing exited: exit status 2
[monitor] 11:37:40 INFO: Starting syncthing
[4GM3D] 11:37:41 INFO: syncthing v0.12.3 "Beryllium Bedbug" (go1.4.3 darwin-amd64 default) unknown-user@build2.syncthing.net 2015-11-15 17:15:10 UTC
[4GM3D] 11:37:41 INFO: My ID: 4GM3D6Y-WAGWPHJ-WEHSMNJ-PIZIKMG-TIARORW-VEKZ4OQ-3ZCQEMJ-MARUKQX
[4GM3D] 11:37:41 INFO: Single thread hash performance is ~129 MB/s
panic: leveldb/table: corruption on data-block (pos=1799293): checksum mismatch, want=0xd0149b1c got=0x374c90a1 [file=014483.ldb]
[monitor] 11:37:42 WARNING: Panic detected, writing to "/Users/davidblom/Library/Application Support/Syncthing/panic-20151117-113742.log"
[monitor] 11:37:42 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 11:37:42 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 11:37:42 INFO: Syncthing exited: exit status 2
[monitor] 11:37:43 INFO: Starting syncthing
[4GM3D] 11:37:43 INFO: syncthing v0.12.3 "Beryllium Bedbug" (go1.4.3 darwin-amd64 default) unknown-user@build2.syncthing.net 2015-11-15 17:15:10 UTC
[4GM3D] 11:37:43 INFO: My ID: 4GM3D6Y-WAGWPHJ-WEHSMNJ-PIZIKMG-TIARORW-VEKZ4OQ-3ZCQEMJ-MARUKQX
[4GM3D] 11:37:43 INFO: Single thread hash performance is ~179 MB/s
panic: leveldb/table: corruption on data-block (pos=1799293): checksum mismatch, want=0xd0149b1c got=0x374c90a1 [file=014483.ldb]
[monitor] 11:37:44 WARNING: Panic detected, writing to "/Users/davidblom/Library/Application Support/Syncthing/panic-20151117-113744.log"
[monitor] 11:37:44 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 11:37:44 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 11:37:44 INFO: Syncthing exited: exit status 2
[monitor] 11:37:45 INFO: Starting syncthing
[4GM3D] 11:37:45 INFO: syncthing v0.12.3 "Beryllium Bedbug" (go1.4.3 darwin-amd64 default) unknown-user@build2.syncthing.net 2015-11-15 17:15:10 UTC
[4GM3D] 11:37:45 INFO: My ID: 4GM3D6Y-WAGWPHJ-WEHSMNJ-PIZIKMG-TIARORW-VEKZ4OQ-3ZCQEMJ-MARUKQX
[4GM3D] 11:37:46 INFO: Single thread hash performance is ~142 MB/s
panic: leveldb/table: corruption on data-block (pos=1799293): checksum mismatch, want=0xd0149b1c got=0x374c90a1 [file=014483.ldb]
[monitor] 11:37:46 WARNING: Panic detected, writing to "/Users/davidblom/Library/Application Support/Syncthing/panic-20151117-113746.log"
[monitor] 11:37:46 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 11:37:46 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 11:37:46 INFO: Syncthing exited: exit status 2
[monitor] 11:37:47 WARNING: 4 restarts in 8.640383343s; not retrying further
```

panic log:

```
[4GM3D] 11:37:45 INFO: syncthing v0.12.3 "Beryllium Bedbug" (go1.4.3 darwin-amd64 default) unknown-user@build2.syncthing.net 2015-11-15 17:15:10 UTC
[4GM3D] 11:37:45 INFO: My ID: 4GM3D6Y-WAGWPHJ-WEHSMNJ-PIZIKMG-TIARORW-VEKZ4OQ-3ZCQEMJ-MARUKQX
[4GM3D] 11:37:46 INFO: Single thread hash performance is ~142 MB/s
...
Panic at 2015-11-17T11:37:46+01:00
panic: leveldb/table: corruption on data-block (pos=1799293): checksum mismatch, want=0xd0149b1c got=0x374c90a1 [file=014483.ldb]
        panic: leveldb/table: corruption on data-block (pos=1799293): checksum mismatch, want=0xd0149b1c got=0x374c90a1 [file=014483.ldb]

goroutine 1 [running]:
github.com/syncthing/syncthing/lib/db.readWriteTransaction.close(0xc208cbe600, 0xc20802c100, 0xc208e66e00)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:59 +0x82
github.com/syncthing/syncthing/lib/db.readWriteTransaction.checkFlush(0xc208cbe600, 0xc20802c100, 0xc208e66e00)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:67 +0x95
github.com/syncthing/syncthing/lib/db.(*Instance).genericReplace(0xc20802c100, 0xc208c0fa10, 0xe, 0x10, 0xc20805f320, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:160 +0xe2a
github.com/syncthing/syncthing/lib/db.(*Instance).replace(0xc20802c100, 0xc208c0fa10, 0xe, 0x10, 0xc20805f320, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:174 +0xe0
github.com/syncthing/syncthing/lib/db.(*FileSet).Replace(0xc209b7f500, 0x1e240d46c4ff5999, 0x939977eb09c57bb, 0x4b49509552e8485b, 0xdd9fea34a454e2be, 0x0, 0x0, 0x0)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:128 +0x3ce
github.com/syncthing/syncthing/lib/model.(*Model).Index(0xc209b62a20, 0x1e240d46c4ff5999, 0x939977eb09c57bb, 0x4b49509552e8485b, 0xdd9fea34a454e2be, 0xc20800b810, 0xe, 0x0, 0x0, 0x0, ...)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:548 +0xa9f
main.syncthingMain()
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:666 +0x4ffc
main.main()
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:399 +0x2645

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.trackCPUUsage()
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·3
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 9 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc208032f70)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:441 +0x1035
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:400 +0x32

goroutine 10 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0xc20801ebe0, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:206 +0x3bc
github.com/syncthing/syncthing/lib/events.(*BufferedSubscription).pollingLoop(0xc20802ea00)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:244 +0x48
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:238 +0x292

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080b00e0)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x242
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x24c

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2080f8160)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:102 +0x31c
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x7cc

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc2080f8160)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7e6

goroutine 19 [select]:
github.com/syncthing/syncthing/lib/ignore.(*Matcher).clean(0xc20899a3c0, 0x68c61714000)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:161 +0x1c9
created by github.com/syncthing/syncthing/lib/ignore.New
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:53 +0x170

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2080f8160)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x9e9

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2080f8160)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:148 +0xa03

goroutine 33 [select]:
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve(0xc209b7d000)
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:52 +0x8cb
created by github.com/syncthing/syncthing/lib/model.NewModel
        /home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:137 +0xa93
```

**Comment by wweich** [comment]
Please check the existing issues for this:
https://github.com/syncthing/syncthing/issues?utf8=%E2%9C%93&q=is%3Aissue+leveldb%2Ftable%3A+corruption+on+data-block

**Comment by davidsblom** [comment]
ah oke. never mind.
