### ISSUE TITLE
Syncthing switches off verbose logging after receiving sync event

### ISSUE THREAD

**Issue by ubershy** [syncthing/syncthing#2561]
Hello.

When I run Syncthing in verbose mode using the command ``syncthing -verbose``, it logs verbosely as expected until I change some files on my other device and syncing occurs.
So after a sync intiated by the other device, I stop seeing VERBOSE level messages in my terminal.
Only INFO level messages continue to appear.

This is my terminal output with obfuscated device IDs:
http://pastebin.com/dt5nvA6W
You can look at timestamps. When verbose mode was working normally, messages were coming very often, few times per second. Then a sync from my other device occured and verbose logging stopped. Only rare INFO messages were coming. "scanning" and "idle" events in web GUI were still observable, so Syncthing apparently hasn't stopped working, it just went into non-verbose output mode in terminal.

**Comment by calmh** [comment]
Probably the verbose logger is dying from an incorrect type assertion, and the error is swallowed...

**Comment by calmh** [comment]
Yeah;

```
[I6KAH] 2015/12/07 07:57:32.100664 main.go:470: DEBUG: main: Failed service '&main.verboseSvc{stop:(chan struct {})(0xc8200186c0), started:(chan struct {})(0xc820018720)}' (1.000000 failures of 5.000000), restarting: true, error: interface conversion: interface is map[string]string, not map[string]interface {}, stacktrace: goroutine 6 [running]:
github.com/thejerf/suture.(*Supervisor).runService.func1.1(0xc8201b8d00, 0x0)
	/Users/jb/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:550 +0xc0
main.(*verboseSvc).formatEvent(0xc82000fab0, 0x8e, 0xecdf724dc, 0x5f9b35e, 0xedbbc0, 0x800, 0x774ec0, 0xc820ad4ff0, 0x0, 0x0)
	/Users/jb/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:99 +0x1bb0
main.(*verboseSvc).Serve(0xc82000fab0)
	/Users/jb/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:41 +0x264
github.com/thejerf/suture.(*Supervisor).runService.func1(0xc8201b8d00, 0x0, 0x1ef05d0, 0xc82000fab0)
	/Users/jb/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:556 +0x6c
created by github.com/thejerf/suture.(*Supervisor).runService
	/Users/jb/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:559 +0x5f

[I6KAH] 2015/12/07 07:57:32.100963 main.go:470: DEBUG: main: Failed service '&main.verboseSvc{stop:(chan struct {})(0xc8200186c0), started:(chan struct {})(0xc820018720)}' (1.999992 failures of 5.000000), restarting: true, error: "close of closed channel", stacktrace: goroutine 935 [running]:
github.com/thejerf/suture.(*Supervisor).runService.func1.1(0xc8201b8d00, 0x0)
	/Users/jb/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:550 +0xc0
main.(*verboseSvc).Serve(0xc82000fab0)
	/Users/jb/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:36 +0xd8
github.com/thejerf/suture.(*Supervisor).runService.func1(0xc8201b8d00, 0xc800000000, 0x1ef05d0, 0xc82000fab0)
	/Users/jb/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:556 +0x6c
created by github.com/thejerf/suture.(*Supervisor).runService
	/Users/jb/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:559 +0x5f

...
```

**Comment by calmh** [comment]
Thanks for reporting it!

**Comment by ubershy** [comment]
Thank you very much for fixing this.
