### ISSUE TITLE
syncthing-linux-386-v0.12.7 immediately coredumps, illegal instruction

### ISSUE THREAD

**Issue by brycied00d** [syncthing/syncthing#2562]
Appears to be a repeat of #2187, down to an identical backtrace and disasm. Regression in the build environment when you went from Go 1.5.1 to 1.5.2 with the 0.12.7 release?

```
$ strace ./syncthing --help
execve("./syncthing", ["./syncthing", "--help"], [/* 33 vars */]) = 0
modify_ldt(1, {entry_number:7, base_addr:0x8a79bc4, limit:1048575, seg_32bit:1, contents:0, read_exec_only:0, limit_in_pages:1, seg_not_present:0, useable:1}, 16) = 0
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x80b5e83} ---
+++ killed by SIGILL (core dumped) +++
[1]    11832 illegal hardware instruction  strace ./syncthing --help
```

```
$ gdb ./syncthing core
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i586-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./syncthing...(no debugging symbols found)...done.
[New LWP 11835]
Core was generated by `./syncthing --help'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x080b5e83 in runtime.check ()
(gdb) bt
#0  0x080b5e83 in runtime.check ()
#1  0x00000000 in ?? ()
(gdb) quit
```
```
Dump of assembler code for function runtime.check:
   0x080b5e50 <+0>:     mov    %gs:0x0,%ecx
   0x080b5e57 <+7>:     mov    -0x4(%ecx),%ecx
   0x080b5e5d <+13>:    cmp    0x8(%ecx),%esp
   0x080b5e60 <+16>:    jbe    0x80b636b <runtime.check+1307>
   0x080b5e66 <+22>:    sub    $0x44,%esp
   0x080b5e69 <+25>:    movl   $0x0,0x28(%esp)
   0x080b5e71 <+33>:    xorps  %xmm0,%xmm0
   0x080b5e74 <+36>:    movss  %xmm0,0x24(%esp)
   0x080b5e7a <+42>:    movss  %xmm0,0x20(%esp)
   0x080b5e80 <+48>:    xorps  %xmm0,%xmm0
=> 0x080b5e83 <+51>:    movsd  %xmm0,0x34(%esp)
   0x080b5e89 <+57>:    movsd  %xmm0,0x2c(%esp)
   0x080b5e8f <+63>:    movl   $0x0,0x40(%esp)
   0x080b5e97 <+71>:    xor    %ebx,%ebx
   0x080b5e99 <+73>:    mov    %bl,0x1c(%esp)
   0x080b5e9d <+77>:    mov    %bl,0x1d(%esp)
   0x080b5ea1 <+81>:    mov    %bl,0x1e(%esp)
   0x080b5ea5 <+85>:    mov    %bl,0x1f(%esp)
   0x080b5ea9 <+89>:    xor    %ebx,%ebx
   0x080b5eab <+91>:    mov    %bl,0x15(%esp)
   0x080b5eaf <+95>:    xor    %ebx,%ebx
   0x080b5eb1 <+97>:    mov    %bl,0x16(%esp)
   0x080b5eb5 <+101>:   mov    %bl,0x17(%esp)
   0x080b5eb9 <+105>:   movl   $0x4b57ce31,(%esp)
   0x080b5ec0 <+112>:   movl   $0xb3a,0x4(%esp)
   0x080b5ec8 <+120>:   movl   $0x3b9aca00,0x8(%esp)
   0x080b5ed0 <+128>:   lea    0x28(%esp),%ebx
   0x080b5ed4 <+132>:   mov    %ebx,0xc(%esp)
   0x080b5ed8 <+136>:   call   0x80b6720 <runtime.timediv>
```

Debian Jessie 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) i686 GNU/Linux (same machine as in #2187, in fact.)

**Comment by brycied00d** [comment]
And on a second Debian Jessie machine too. 3.16.0-4-586 #1 Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) i686 GNU/Linux.
Syncthing 0.12.6 ran fine (as well as several versions before it), only started with 0.12.7.
```
$ ./syncthing --help
[1]    17067 illegal hardware instruction (core dumped)  ./syncthing --help
```

```
cat /proc/cpuinfo                                                                                                                                                                                                                                                                                                                                                                                                :(
processor       : 0
vendor_id       : CentaurHauls
cpu family      : 6
model           : 9
model name      : VIA Nehemiah
stepping        : 8
cpu MHz         : 999.870
cache size      : 64 KB
fdiv_bug        : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 1
wp              : yes
flags           : fpu vme de pse tsc msr cx8 sep mtrr pge cmov pat mmx fxsr sse rng rng_en ace ace_en
bogomips        : 1999.74
clflush size    : 32
cache_alignment : 32
address sizes   : 32 bits physical, 32 bits virtual
power management:
```

(Yes, I run old and somewhat eclectic hardware. And if Go ran on OpenBSD/sparc64 or OpenBSD/macppc, I'd be running Syncthing on those too!)

**Comment by calmh** [comment]
Yeah, I think I know what the issue is, it depends on what is run first on the build server after the upgrade of Go. I'm rebuilding it now, will see if that works better.

**Comment by CompuRoot** [comment]
The same happens on FreeBSD - "illegal instruction".
Tried http://build.syncthing.net/job/syncthing/1601/ without success.

Hardware Pentium-III. I believe new builds using  some instructions that works on Pentium 4 and above.
I know it pretty old CPU, but it is the only one that works on that particular bending CNC :( 

BTW, ARM build throw the same error - "illegal instruction" on Raspberry PI B/B+, but works Ok on Raspberry Pi 2. Personally, I think it is Ok since support for ARM6 ended on most OS, but there are still a lot of old devices based on ARM6 and debian is wheezy still alive, but from another point of view ARM7 instructions is much more efficient, so I can't see another way except to keep different builds for old architectures and new one to avoid sacrifice of efficiency in favor of supporting old hardware and give in the same time a choice to live a little longer for an "old" devices.

**Comment by calmh** [comment]
@CompuRoot Have you tried the link above that I suggest?

**Comment by CompuRoot** [comment]
Yes, I tried for FreeBSD this one:

http://build.syncthing.net/job/syncthing/1601/artifact/src/github.com/syncthing/syncthing/syncthing-freebsd-386-v0.12.7+3-g3318651.tar.gz

**Comment by brycied00d** [comment]
Still no-go, same backtrace and instruction.
```
$ ./syncthing -version
[1]    17599 illegal hardware instruction (core dumped)  ./syncthing -version
$ gdb ./syncthing core
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i586-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./syncthing...(no debugging symbols found)...done.
[New LWP 17599]
Core was generated by `./syncthing -version'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x080b5ff3 in runtime.check ()
(gdb) bt
#0  0x080b5ff3 in runtime.check ()
#1  0x00000000 in ?? ()
(gdb) disas
Dump of assembler code for function runtime.check:
   0x080b5fc0 <+0>:     mov    %gs:0x0,%ecx
   0x080b5fc7 <+7>:     mov    -0x4(%ecx),%ecx
   0x080b5fcd <+13>:    cmp    0x8(%ecx),%esp
   0x080b5fd0 <+16>:    jbe    0x80b64db <runtime.check+1307>
   0x080b5fd6 <+22>:    sub    $0x44,%esp
   0x080b5fd9 <+25>:    movl   $0x0,0x28(%esp)
   0x080b5fe1 <+33>:    xorps  %xmm0,%xmm0
   0x080b5fe4 <+36>:    movss  %xmm0,0x24(%esp)
   0x080b5fea <+42>:    movss  %xmm0,0x20(%esp)
   0x080b5ff0 <+48>:    xorps  %xmm0,%xmm0
=> 0x080b5ff3 <+51>:    movsd  %xmm0,0x34(%esp)
   0x080b5ff9 <+57>:    movsd  %xmm0,0x2c(%esp)
   0x080b5fff <+63>:    movl   $0x0,0x40(%esp)
   0x080b6007 <+71>:    xor    %ebx,%ebx
   0x080b6009 <+73>:    mov    %bl,0x1c(%esp)
   0x080b600d <+77>:    mov    %bl,0x1d(%esp)
   0x080b6011 <+81>:    mov    %bl,0x1e(%esp)
   0x080b6015 <+85>:    mov    %bl,0x1f(%esp)
   0x080b6019 <+89>:    xor    %ebx,%ebx
   0x080b601b <+91>:    mov    %bl,0x15(%esp)
```

**Comment by brycied00d** [comment]
For what it's worth, both the published release and this build work fine on my Raspberry Pi B (original)
```
$ ./syncthing -version
syncthing v0.12.7+3-g3318651 "Beryllium Bedbug" (go1.5.2 linux-arm default) jenkins@build2.syncthing.net 2015-12-07 07:04:09 UTC
```
```
$ cat /proc/cpuinfo 
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 847.52
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 000f
Serial          : 00000000913c2e27
```

**Comment by calmh** [comment]
OK let me wipe the installation and make sure it gets rebuilt the correct way...

**Comment by CompuRoot** [comment]
Thank you **brycied00d** for update on Raspberry Pi B. 
I tried a few versions ago and Pi choke on them with error "Illegal instruction", we just replaced them to Pi2 then. It good to know we can use new builds on old Pis.

**Comment by calmh** [comment]
This one is still cooking, but could you see if there's any difference in that one afterwards? It's supposed to be as baseline 386 and ARMv5 as I can make it...

http://build.syncthing.net/job/syncthing/1602/

**Comment by brycied00d** [comment]
@calmh I'll give it a try as soon as Jenkins posts the builds. (This build is taking longer than the last...)

**Comment by brycied00d** [comment]
Bingo, that seems to work.
```
$ ./syncthing -version                      
syncthing v0.12.7+3-g3318651 "Beryllium Bedbug" (go1.5.2 linux-386 default) jenkins@build2.syncthing.net 2015-12-07 07:04:09 UTC
```

**Comment by calmh** [comment]
Great. Then I know what the problem was, I think, and future builds should be fine.

**Comment by CompuRoot** [comment]
Confirm, FreeBSD i386 v0.12.7 is now working too !

Thank you !

**Comment by brycied00d** [comment]
Just wanted to mention that 0.12.8 worked fine as well, no regression.

**Comment by calmh** [comment]
Thanks
