### ISSUE TITLE
Null Pointer Error: unexpected fault address 0x0

### ISSUE THREAD

**Issue by Echsecutor** [syncthing/syncthing#2678]
After the automatic upgrade to
    syncthing v0.12.11 "Beryllium Bedbug" (go1.5.2 linux-amd64) unknown-user@build
I get the following error
    unexpected fault address 0x0
    fatal error: fault
immediately after
    INFO: Starting usage reporting

```
[VQPS6] 08:31:33 INFO: syncthing v0.12.11 "Beryllium Bedbug" (go1.5.2 linux-amd64) unknown-user@build2.syncthing.net 2016-01-03 08:56:33 UTC
[VQPS6] 08:31:33 INFO: My ID: [[removed]]
[VQPS6] 08:31:34 INFO: Single thread hash performance is ~151 MB/s
[VQPS6] 08:31:34 OK: Ready to synchronize Fotos2015 (read-write)
[VQPS6] 08:31:34 OK: Ready to synchronize default (read-write)
[VQPS6] 08:31:35 OK: Ready to synchronize mirror (read only; no external updates accepted)
[VQPS6] 08:31:35 INFO: Using discovery server https://discovery-v4-1.syncthing.net/?id=[[removed]]
[[...]]
[VQPS6] 08:31:35 INFO: Device [[removed]] is [[removed]] at [dynamic]
[[...]]
[VQPS6] 08:31:35 INFO: Starting usage reporting
Panic at 2016-01-09T08:31:35+01:00
fatal error: fault
unexpected fault address 0x0
[signal 0xb code=0x80 addr=0x0 pc=0x6cc820]

goroutine 71 [running]:
runtime.throw(0xb855d8, 0x5)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc8201b5330 sp=0xc8201b5318
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc8201b5380 sp=0xc8201b5330
github.com/syncthing/syncthing/lib/protocol.Vector.Update(0xc8202b6420, 0x1, 0x1, 0xac1f2f658171f35d, 0xc8202b6450, 0x1, 0x1)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/protocol/vector.go:20 fp=0xc8201b5388 sp=0xc8201b5380
github.com/syncthing/syncthing/lib/scanner.(*Walker).walkRegular(0xc820338000, 0xc82029243f, 0x38, 0x7f271b98fed8, 0xc820482640, 0xece02f455, 0x23fdafbf, 0x1068900, 0xc8202920c0, 0x0, ...)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/scanner/walk.go:314 +0x614 fp=0xc8201b58d0 sp=0xc8201b5388
github.com/syncthing/syncthing/lib/scanner.(*Walker).walkAndHashFiles.func1(0xc820292420, 0x57, 0x7f271b98fed8, 0xc820482640, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/scanner/walk.go:272 +0x14ca fp=0xc8201b5aa8 sp=0xc8201b58d0
path/filepath.walk(0xc820292420, 0x57, 0x7f271b98fed8, 0xc820482640, 0xc8219a0480, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:349 +0x80 fp=0xc8201b5be0 sp=0xc8201b5aa8
path/filepath.walk(0xc8219a0840, 0x39, 0x7f271b98fed8, 0xc8204825a0, 0xc8219a0480, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201b5d18 sp=0xc8201b5be0
path/filepath.walk(0xc82049b0a0, 0x1f, 0x7f271b98fed8, 0xc8204824b0, 0xc8219a0480, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201b5e50 sp=0xc8201b5d18
path/filepath.Walk(0xc82049b0a0, 0x1f, 0xc8219a0480, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:396 +0xe1 fp=0xc8201b5eb8 sp=0xc8201b5e50
github.com/syncthing/syncthing/lib/scanner.(*Walker).Walk.func1(0xc820338000, 0xc8202920c0, 0xc820292120)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/scanner/walk.go:115 +0xa6 fp=0xc8201b5f78 sp=0xc8201b5eb8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc8201b5f80 sp=0xc8201b5f78
created by github.com/syncthing/syncthing/lib/scanner.(*Walker).Walk
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/scanner/walk.go:122 +0x3a6
```

**Comment by Echsecutor** [comment]
I am running the downloaded executable (not using any apt repositories) on a laptop with Ubuntu 15.10

**Comment by calmh** [comment]
Not really sure what this is, except it not being a "regular" nil pointer - the "fatal error" is a problem internally in the runtime. Normally I'd suspect a broken binary, but it's the release version and the auto upgrade takes care to check it's signature... My next guess would be bad hardware or a bug in the runtime. Is this reproducible?

**Comment by Echsecutor** [comment]
Happens every time I try to start syncthing. 4 times in a row and then the launcher quits. I.e. I can currently not run syncthing on this machine

[monitor] 08:31:35 INFO: Syncthing exited: exit status 2
[monitor] 08:31:36 WARNING: 4 restarts in 8.869558342s; not retrying further

**Comment by Echsecutor** [comment]
You are right, seems to be an error with the (auto-downloaded) executable. I just exchanged it for the current one from git hub.

[VQPS6] 11:48:42 INFO: syncthing v0.12.11 "Beryllium Bedbug" (go1.5.2 linux-amd64) unknown-user@build2.syncthing.net 2016-01-03 08:56:33 UTC

same Version message but now it works again. Maybe a corrupted download was causing the error. Thanks for help!

**Comment by AudriusButkevicius** [comment]
We do signature verification though, which makes me suspicious.

**Comment by calmh** [comment]
And we even do it by writing the file first to a temporary name, then reading it back and verifying the signature, then renaming it to the final destination. I'm confused about how it could be corrupt, except if a disk block has literally developed bit rot after the fact (or the disk cache in memory, possibly...). Weird...
