### ISSUE TITLE
0.12.12 Windows: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#2694]
```
[UAL5T] 20:43:33 INFO: syncthing v0.12.12 "Beryllium Bedbug" (go1.6beta1 windows-amd64) WIN-P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ 2016-01-10 09:10:53 UTC
...
Computer went to sleep, woke up the next morning
...
[UAL5T] 08:17:31 INFO: Restarting
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x407440]
goroutine 2980 [running]:
main.(*apiService).Stop(0xc08376ae70)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:268 +0x50
github.com/thejerf/suture.(*Supervisor).removeService.func1.1(0x30e0840, 0xc08376ae70, 0xc0824286c0)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:569 +0x2e
created by github.com/thejerf/suture.(*Supervisor).removeService.func1
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:571 +0x80
```

**Comment by calmh** [comment]
Boom

**Comment by calmh** [comment]
What's your GUI listen address set to?

**Comment by calmh** [comment]
And do you have older log data, preferably all the way since it started?

**Comment by canton7** [comment]
The GUI listen address should be `https://localhost:8384`. I've got the full logs at home - I'll post them tonight / tomorrow morning.

**Comment by calmh** [comment]
The startup/shutdown handling is racy as fuck, which probably doesn't help

```
==================
WARNING: DATA RACE
Read by goroutine 27:
  github.com/syncthing/syncthing/cmd/syncthing.(*apiService).Stop()
      /Users/jb/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:271 +0x3a
  github.com/thejerf/suture.(*Supervisor).removeService.func1.1()
      /Users/jb/src/github.com/thejerf/suture/suture.go:569 +0x34

Previous write by goroutine 13:
  [failed to restore the stack]

Goroutine 27 (running) created at:
  github.com/thejerf/suture.(*Supervisor).removeService.func1()
      /Users/jb/src/github.com/thejerf/suture/suture.go:571 +0x89

Goroutine 13 (running) created at:
  github.com/thejerf/suture.(*Supervisor).runService()
      /Users/jb/src/github.com/thejerf/suture/suture.go:559 +0x5e
  github.com/thejerf/suture.(*Supervisor).Serve()
      /Users/jb/src/github.com/thejerf/suture/suture.go:435 +0x3c3
==================
```

**Comment by canton7** [comment]
Thanks! I'm going to assume you don't want those logs any more? :smile:

**Comment by calmh** [comment]
If it happens again despite this, I do. :)
