### ISSUE TITLE
Crash on folder removal

### ISSUE THREAD

**Issue by lfam** [syncthing/syncthing#2705]
I added a shared folder, located on a remote machine, to test transfer speeds to the local machine. So, only two nodes. After the local shared folder was ~5% completed, I removed the folder from the local machine through the web interface. When that happened, Syncthing crashed.

Here is some info about each Syncthing installation, followed by the panic trace.

Remote machine (Debian Jessie):
```
$ syncthing --version
syncthing v0.12.14 "Beryllium Bedbug" (go1.5.3 linux-amd64) unknown-user@build2.syncthing.net 2016-01-13 20:11:02 UTC
```

Local machine where Syncthing crashed (Debian Stretch):
```
$ syncthing --version
syncthing v0.12.13 "Beryllium Bedbug" (go1.5.3 linux-amd64) unknown-user@build2.syncthing.net 2016-01-13 20:11:02 UTC
```

Panic trace with sanitized hostnames. If you think the hostnames are related, I can provide them. They fit within ASCII.
```
Jan 16 15:15:57 local syncthing[22535]: [MQPBM] INFO: Puller: final: peers who had this file went away, or the file has changed while syncing. will retry later
Jan 16 15:15:57 local syncthing[22535]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 16 15:15:57 local syncthing[22535]: [signal 0xb code=0x1 addr=0x0 pc=0x6523df]
Jan 16 15:15:57 local syncthing[22535]: goroutine 2358 [running]:
Jan 16 15:15:57 local syncthing[22535]: github.com/syncthing/syncthing/lib/db.(*FileSet).Update(0x0, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc822684000, 0x25, 0x3e8)
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/db/set.go:140 +0xabf
Jan 16 15:15:57 local syncthing[22535]: github.com/syncthing/syncthing/lib/model.(*Model).updateLocals(0xc8210fa240, 0xc821593050, 0x9, 0xc822684000, 0x25, 0x3e8)
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/model/model.go:1171 +0x137
Jan 16 15:15:57 local syncthing[22535]: github.com/syncthing/syncthing/lib/model.(*rwFolder).dbUpdaterRoutine.func1()
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/model/rwfolder.go:1433 +0x268
Jan 16 15:15:57 local syncthing[22535]: github.com/syncthing/syncthing/lib/model.(*rwFolder).dbUpdaterRoutine(0xc8208d3b80)
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/model/rwfolder.go:1460 +0x359
Jan 16 15:15:57 local syncthing[22535]: github.com/syncthing/syncthing/lib/model.(*rwFolder).pullerIteration.func1(0xc8208d3b80, 0x7f96944a1930, 0xc8216bd660)
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/model/rwfolder.go:411 +0x21
Jan 16 15:15:57 local syncthing[22535]: created by github.com/syncthing/syncthing/lib/model.(*rwFolder).pullerIteration
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/model/rwfolder.go:413 +0x670
Jan 16 15:15:57 local syncthing[22535]: goroutine 1 [chan receive, 110 minutes]:
Jan 16 15:15:57 local syncthing[22535]: main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xb66548, 0x1, 0x0, 0x0, ...)
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:848 +0x3f59
Jan 16 15:15:57 local syncthing[22535]: main.main()
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:362 +0x943
Jan 16 15:15:57 local syncthing[22535]: goroutine 28 [select, 50 minutes]:
Jan 16 15:15:57 local syncthing[22535]: github.com/syncthing/syncthing/lib/ignore.(*Matcher).clean(0xc82023c5a0, 0x68c61714000)
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:161 +0x1ca
Jan 16 15:15:57 local syncthing[22535]: created by github.com/syncthing/syncthing/lib/ignore.New
Jan 16 15:15:57 local syncthing[22535]: /home/jenkins/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:53 +0x159
```

**Comment by lfam** [comment]
And if you were wondering, the shared folder was successfully removed from the local (crashy) node.

**Comment by calmh** [comment]
Thanks. The code doesn't like a folder being removed while it's syncing changes on it, I see the problem.
