### ISSUE TITLE
panic: leveldb/table: corruption on data-block

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing#2734]
One of my machines crashes on startup. This is the error:

```
[W4RYZ] 17:08:14 INFO: syncthing v0.12.16 "Beryllium Bedbug" (go1.6beta2 windows-amd64) WIN-P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ 2016-01-24 07:09:28 UTC
[W4RYZ] 17:08:14 INFO: My ID: W4RYZKF
[W4RYZ] 17:08:14 INFO: Single thread hash performance is ~148 MB/s
[W4RYZ] 17:08:16 INFO: Compacting database: leveldb/table: corruption on data-block (pos=2007062): checksum mismatch, want=0xf78f0353 got=0x4687f369 [file=18152769.ldb]
panic: leveldb/table: corruption on data-block (pos=2007062): checksum mismatch, want=0xf78f0353 got=0x4687f369 [file=18152769.ldb]
	panic: leveldb/table: corruption on data-block (pos=2007062): checksum mismatch, want=0xf78f0353 got=0x4687f369 [file=18152769.ldb]
goroutine 1 [running]:
github.com/syncthing/syncthing/lib/db.readWriteTransaction.close(0xc08283cea0, 0xc08281c078, 0xc083183780)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:59 +0x88
github.com/syncthing/syncthing/lib/db.readWriteTransaction.checkFlush(0xc08283cea0, 0xc08281c078, 0xc083183780)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:67 +0x9b
github.com/syncthing/syncthing/lib/db.(*Instance).genericReplace(0xc08281c078, 0xc083096f48, 0x6, 0x8, 0xc0827f0720, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:164 +0xe3f
github.com/syncthing/syncthing/lib/db.(*Instance).replace(0xc08281c078, 0xc083096f48, 0x6, 0x8, 0xc0827f0720, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:178 +0xdc
github.com/syncthing/syncthing/lib/db.(*FileSet).Replace(0xc083494680, 0x2b8e5e30604f1b33, 0xf97f497c09b2777b, 0x9726a2bcab30407d, 0x2a2a9a034482a7c2, 0x0, 0x0, 0x0)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/set.go:128 +0x410
github.com/syncthing/syncthing/lib/model.(*Model).Index(0xc08247e000, 0x2b8e5e30604f1b33, 0xf97f497c09b2777b, 0x9726a2bcab30407d, 0x2a2a9a034482a7c2, 0xc0822caa90, 0x6, 0x0, 0x0, 0x0, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/model/model.go:544 +0x993
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0821748c0, 0x47, 0x0, 0xc082005f8d, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:695 +0x4ce2
main.main()
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:362 +0x94f
[W4RYZ] 17:08:48 INFO: syncthing v0.12.16 "Beryllium Bedbug" (go1.6beta2 windows-amd64) WIN-P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ 2016-01-24 07:09:28 UTC
[W4RYZ] 17:08:48 INFO: My ID: W4RYZKF
[W4RYZ] 17:08:49 INFO: Single thread hash performance is ~169 MB/s
[W4RYZ] 17:08:51 INFO: Compacting database: leveldb: closed
panic: leveldb/table: corruption on data-block (pos=2007062): checksum mismatch, want=0xf78f0353 got=0x4687f369 [file=18152769.ldb]
	panic: leveldb/table: corruption on data-block (pos=2007062): checksum mismatch, want=0xf78f0353 got=0x4687f369 [file=18152769.ldb]
goroutine 1 [running]:
github.com/syncthing/syncthing/lib/db.readWriteTransaction.close(0xc082d03380, 0xc082026108, 0xc082d4bdc0)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:59 +0x88
github.com/syncthing/syncthing/lib/db.readWriteTransaction.checkFlush(0xc082d03380, 0xc082026108, 0xc082d4bdc0)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:67 +0x9b
github.com/syncthing/syncthing/lib/db.(*Instance).genericReplace(0xc082026108, 0xc0837f7330, 0x9, 0x10, 0xc082c78bc0, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:164 +0xe3f
github.com/syncthing/syncthing/lib/db.(*Instance).replace(0xc082026108, 0xc0837f7330, 0x9, 0x10, 0xc082c78bc0, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:178 +0xdc
github.com/syncthing/syncthing/lib/db.(*FileSet).Replace(0xc083600e00, 0x2b8e5e30604f1b33, 0xf97f497c09b2777b, 0x9726a2bcab30407d, 0x2a2a9a034482a7c2, 0x0, 0x0, 0x0)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/set.go:128 +0x410
github.com/syncthing/syncthing/lib/model.(*Model).Index(0xc0824e0ea0, 0x2b8e5e30604f1b33, 0xf97f497c09b2777b, 0x9726a2bcab30407d, 0x2a2a9a034482a7c2, 0xc082173fc0, 0x9, 0x0, 0x0, 0x0, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/model/model.go:544 +0x993
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0821745a0, 0x47, 0x0, 0xc082005f8d, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:695 +0x4ce2
main.main()
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:362 +0x94f
```

Should syncthing handle this? Should I do something manually?

**Comment by AudriusButkevicius** [comment]
The DB is corrupt for whatever reason (power outage, bad hardware, bad software).
There is no way to recover from this apart from nuking index directory in syncthings home directory (check -help).

Also, see forums or other closed tickets for more advice.

**Comment by fbreve** [comment]
Thank you.

I deleted only the corrupted file and it is working again.

**Comment by calmh** [comment]
While this solves your problem, you might need to worry about files actually being corrupted on your system. Our database is one of the (apparently) few things that actually does file checksum verification on consumer systems, so may be just the one thing that shows the symptoms of a larger problem.

**Comment by fbreve** [comment]
Thanks. I'm running IntelBurnTest now on all available RAM as corrupted files are usually related to bad memory.

**Comment by AudriusButkevicius** [comment]
Or bad disk.

**Comment by fbreve** [comment]
Indeed. But CrystalDiskInfo says both hard disks are ok, as far as S.M.A.R.T. is concerned. It used to have three disks until last week, one of them was in the alert state, but it died last week. :(

**Comment by simplypeachy** [comment]
OT, but SMART will tell you if a) a disk might be suspect or b) hasn't displayed suspect behaviour yet

**Comment by MyPod** [comment]
SMART failing means the disk is likely to fail soon, but it doesn't necessarily work the other way around too. Bad RAM would likely cause issues with other programs as well

**Comment by fbreve** [comment]
I'll run chkdsk too. But it is probably an isolated problem, maybe caused by some earlier system crash.

Bad RAM is not always easily detectable. Once I had a bad memory stick that would change one or two bytes on about 30% of every 700MB CD-R I recorded. The system itself would rarely crash. It took a while until I find out it was a RAM issue. Nowadays it is even worse, as some memory modules would pass every test (memtest86, prime95, IBT, etc.) and still fail eventually even when the system is idle.

**Comment by fbreve** [comment]
![img_20160127_182322017](https://cloud.githubusercontent.com/assets/7475908/12632145/e6dbfb26-c53c-11e5-9a6a-db5660bc0c78.jpg)

Problem found!
Corsair Dominator is expensive, but crap!

**Comment by skandragon** [comment]
I am also getting this error on SyncThing 0.12.19.  Disk storage is ZFS, memory is ECC.  I've verified with Memtest86 for a few days, and ZFS protects me against data loss otherwise.  So...  if it's not hardware...

**Comment by calmh** [comment]
@skandragon You'll be the first confirmed case of an actual good setup (ECC+ZFS) where we still see disk corruption in that case, so that's actually interesting. Do you have the actual panic trace around? Reproducible?

**Comment by skandragon** [comment]
It happens at some point after running for a few hours.  Let me see what I have, or can make.

**Comment by skandragon** [comment]
I withdraw my bug report.  Something is truly amiss on the box; I'll dig deeper later, but for now consider this yet another bad hardware setup.

**Comment by skandragon** [comment]
Turns out CPUs can go bad too.  Swapped the CPU, problem went away.

**Comment by calmh** [comment]
Huh. Thanks for letting is know :)

**Comment by nrolland** [comment]
same pb. how can one find synching index directory ?

**Comment by Deleetdk** [comment]
For those wondering where is the syncthing home directory and using Windows (so not so easy to just use `syncthing -paths`), it's in `C:\Users\USER\AppData\Local\Syncthing` on Windows 8.1.
