### ISSUE TITLE
Input/output error on compacting database

### ISSUE THREAD

**Issue by roggan87** [syncthing/syncthing#2796]
I'm running syncthing 0.12.19 ARM on a Raspberry Pi and I noticed I couldn't reach the WebUI anymore, so I restarted it. It keeps restarting itself due to panic. Any idea how to solve this?

### Version Information
Syncthing Version: v0.12.19
OS Version: Raspbian 4.1.13+

### Panic log

```
[2YV3A] 07:04:06 INFO: syncthing v0.12.19 "Beryllium Bedbug" (go1.5.3 linux-arm) unknown-user@build2.syncthing.net 2016-02-14 19:26:33 UTC
[2YV3A] 07:04:06 INFO: My ID: 2YV3A5O-HKXONDO-7I7EGYW-VMDEWQ7-HUKFUZV-LSEL3S4-XZNJNXQ-VSDRVQ4
[2YV3A] 07:04:06 INFO: Single thread hash performance is ~3.9 MB/s
[2YV3A] 07:04:20 INFO: Compacting database: read /home/pi/.config/syncthing/index-v0.11.0.db/000746.ldb: input/output error
[2YV3A] 07:04:43 OK: Ready to synchronize Dokument (read-write)
[2YV3A] 07:04:43 OK: Ready to synchronize default (read-write)
...
Panic at 2016-02-23T07:05:46Z
panic: read /home/pi/.config/syncthing/index-v0.11.0.db/000746.ldb: input/output error

goroutine 1 [running]:
github.com/syncthing/syncthing/lib/db.(*Instance).checkGlobals(0x10c0ac98, 0x123da550, 0x6, 0x8, 0x11257164)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:578 +0x598
github.com/syncthing/syncthing/lib/db.NewFileSet(0x10f8bc90, 0x6, 0x10c0ac98, 0x1150f3d4)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:104 +0x238
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0x10cbab00, 0x10f8bc90, 0x6, 0x1100a600, 0x11, 0x10f7e700, 0x2, 0x4, 0x0, 0x3c, ...)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:1211 +0xf8
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x608efc, 0x1, 0x0, ...)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:692 +0x1aa8
main.main()
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:364 +0x748

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x10f80a50)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x260
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x258

goroutine 12 [chan receive, 1 minutes]:
main.setupSignalHandling.func2(0x10c19980)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:889 +0x2c
created by main.setupSignalHandling
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:891 +0x230

goroutine 8 [syscall, 1 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 9 [chan receive]:
main.trackCPUUsage()
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x108
created by main.init.3
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x24

goroutine 10 [select, 1 minutes, locked to thread]:
runtime.gopark(0x7182b8, 0x10c1e78c, 0x6111a0, 0x6, 0x7d918, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x148
runtime.selectgoImpl(0x10c1e78c, 0x0, 0xc)
	/usr/local/go/src/runtime/select.go:392 +0x14d4
runtime.selectgo(0x10c1e78c)
	/usr/local/go/src/runtime/select.go:212 +0x10
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x428
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 11 [chan receive, 1 minutes]:
main.setupSignalHandling.func1(0x10c19880)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:879 +0x2c
created by main.setupSignalHandling
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:881 +0x104

goroutine 13 [select, 1 minutes]:
github.com/thejerf/suture.(*Supervisor).Serve(0x10c0d710)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:441 +0xdb8
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:400 +0x2c

goroutine 14 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0x10c0feb0, 0xf8475800, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:210 +0x3b0
github.com/syncthing/syncthing/lib/events.(*BufferedSubscription).pollingLoop(0x10c10ab0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:252 +0x38
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:246 +0x268

goroutine 18 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x110069a0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:85 +0x418
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x6c0

goroutine 19 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x110069a0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x11c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x6dc

goroutine 20 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0x110069a0, 0x641920, 0xb, 0xb6e4cd10, 0x10c16a80)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:204 +0x788
github.com/syndtr/goleveldb/leveldb.(*DB).tableCompaction(0x110069a0, 0x10c0c2d0, 0x0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:552 +0xdf0
github.com/syndtr/goleveldb/leveldb.(*DB).tableAutoCompaction(0x110069a0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:597 +0x48
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x110069a0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:789 +0x250
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x8cc

goroutine 21 [select, 1 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x110069a0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x20c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x8e8

goroutine 22 [select, 1 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x110069a0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x168
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x904

goroutine 24 [select, 1 minutes]:
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve(0x1102b0a0)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:52 +0x7a0
created by github.com/syncthing/syncthing/lib/model.NewModel
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:137 +0xb08

goroutine 26 [select, 1 minutes]:
github.com/syncthing/syncthing/lib/ignore.(*Matcher).clean(0x11ddecf0, 0x61714000, 0x68c)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:161 +0x1d0
created by github.com/syncthing/syncthing/lib/ignore.New
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:53 +0x178

goroutine 27 [select, 1 minutes]:
github.com/syncthing/syncthing/lib/ignore.(*Matcher).clean(0x11ddfdd0, 0x61714000, 0x68c)
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:161 +0x1d0
created by github.com/syncthing/syncthing/lib/ignore.New
	/home/jenkins/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:53 +0x178
```

**Comment by AudriusButkevicius** [comment]
Your storage on the pie is most likely toast.
