### ISSUE TITLE
Sudden database panic that I don't recognize from before...

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2872]
```
panic: unexpected EOF

goroutine 8840 [running]:
panic(0xadb420, 0xc82000a130)
        /usr/local/go/src/runtime/panic.go:464 +0x3ef fp=0xc838ed0c50 sp=0xc838ed0bd0
github.com/syncthing/syncthing/lib/db.readWriteTransaction.updateGlobal(0xc84e7757d0, 0xc82000e080, 0xc84c25e240, 0xc831ef4fa8, 0x7, 0x8, 0xc83a363260, 0x20, 0x20, 0xc8232a2170, ...)
        /home/jenkins/workspace/syncthing/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:106 +0x4ec fp=0xc838ed1200 sp=0xc838ed0c50
github.com/syncthing/syncthing/lib/db.(*Instance).genericReplace(0xc82000e080, 0xc831ef4fa8, 0x7, 0x8, 0xc83a363260, 0x20, 0x20, 0xc838c7e000, 0x3e8, 0x3e8, ...)
        /home/jenkins/workspace/syncthing/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:145 +0x1879 fp=0xc838ed15d8 sp=0xc838ed1200
github.com/syncthing/syncthing/lib/db.(*Instance).replace(0xc82000e080, 0xc831ef4fa8, 0x7, 0x8, 0xc83a363260, 0x20, 0x20, 0xc838c7e000, 0x3e8, 0x3e8, ...)
        /home/jenkins/workspace/syncthing/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:201 +0xd5 fp=0xc838ed1660 sp=0xc838ed15d8
github.com/syncthing/syncthing/lib/db.(*FileSet).Replace(0xc821fef580, 0xc7a34034fd19c7f8, 0xfdc965b617ce28bc, 0x9de315f22ff97ec9, 0x1f25db58bd15f992, 0xc838c7e000, 0x3e8, 0x3e8)
        /home/jenkins/workspace/syncthing/src/github.com/syncthing/syncthing/lib/db/set.go:128 +0x409 fp=0xc838ed1770 sp=0xc838ed1660
github.com/syncthing/syncthing/lib/model.(*Model).Index(0xc8200f05a0, 0xc7a34034fd19c7f8, 0xfdc965b617ce28bc, 0x9de315f22ff97ec9, 0x1f25db58bd15f992, 0xc8232a2004, 0x7, 0xc838c7e000, 0x3e8, 0x3e8, ...)
        /home/jenkins/workspace/syncthing/src/github.com/syncthing/syncthing/lib/model/model.go:545 +0x98c fp=0xc838ed1a80 sp=0xc838ed1770
github.com/syncthing/syncthing/lib/protocol.nativeModel.Index(0xfffffd7ffe9c2850, 0xc8200f05a0, 0xc7a34034fd19c7f8, 0xfdc965b617ce28bc, 0x9de315f22ff97ec9, 0x1f25db58bd15f992, 0xc8232a2004, 0x7, 0xc838c7e000, 0x3e8, ...)
        /home/jenkins/workspace/syncthing/src/github.com/syncthing/syncthing/lib/protocol/nativemodel_unix.go:14 +0xc3 fp=0xc838ed1b08 sp=0xc838ed1a80
github.com/syncthing/syncthing/lib/protocol.(*nativeModel).Index(0xc83a733ac0, 0xc7a34034fd19c7f8, 0xfdc965b617ce28bc, 0x9de315f22ff97ec9, 0x1f25db58bd15f992, 0xc8232a2004, 0x7, 0xc838c7e000, 0x3e8, 0x3e8, ...)
        <autogenerated>:81 +0x126 fp=0xc838ed1b88 sp=0xc838ed1b08
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).handleIndex(0xc8207d2000, 0xc8232a2004, 0x7, 0xc838c7e000, 0x3e8, 0x3e8, 0x0, 0x0, 0x0, 0x0)
        /home/jenkins/workspace/syncthing/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:492 +0x390 fp=0xc838ed1c58 sp=0xc838ed1b88
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).readerLoop(0xc8207d2000, 0x0, 0x0)
        /home/jenkins/workspace/syncthing/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:338 +0xf8b fp=0xc838ed1f58 sp=0xc838ed1c58
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc838ed1f60 sp=0xc838ed1f58
created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start
        /home/jenkins/workspace/syncthing/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:193 +0x39
```

### Version Information

syncthing v0.13.0-beta.0+147-g31362df "Copper Cockroach" (go1.6 solaris-amd64) unknown-user@lxslave.syncthing.net 2016-03-22 20:53:56 UTC

SunOS anto.nym.se 5.11 joyent_20160304T005100Z i86pc i386 i86pc

**Comment by AudriusButkevicius** [comment]
I had the same thing on Windows, on head, I suspect for an empty folder.
```
goroutine 193 [running]:
panic(0xb20580, 0xc082038030)
        C:/Go/src/runtime/panic.go:464 +0x3f4
github.com/syncthing/syncthing/lib/db.readWriteTransaction.updateGlobal(0xc082c1a8d0, 0xc0821b01e0, 0xc0828e6300, 0xc082c07350, 0x7, 0x8, 0xc082b74780, 0x20, 0x20, 0xc082c063ca, ...)
        C:/Go/bin/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:106 +0x4f3
github.com/syncthing/syncthing/lib/db.(*Instance).genericReplace(0xc0821b01e0, 0xc082c07350, 0x7, 0x8, 0xc082b74780, 0x20, 0x20, 0xc082c7a000, 0x9d, 0x9d, ...)
        C:/Go/bin/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:145 +0x1880
github.com/syncthing/syncthing/lib/db.(*Instance).replace(0xc0821b01e0, 0xc082c07350, 0x7, 0x8, 0xc082b74780, 0x20, 0x20, 0xc082c7a000, 0x9d, 0x9d, ...)
        C:/Go/bin/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:201 +0xdc
github.com/syncthing/syncthing/lib/db.(*FileSet).Replace(0xc082070880, 0x6ff5fcdb815ef42f, 0xc9968ddc40d85c84, 0x7c88bd1b47ca1f55, 0xa6988e9a64af8ec2, 0xc082c7a000, 0x9d, 0x9d)
        C:/Go/bin/src/github.com/syncthing/syncthing/lib/db/set.go:128 +0x410
github.com/syncthing/syncthing/lib/model.(*Model).Index(0xc0820de900, 0x6ff5fcdb815ef42f, 0xc9968ddc40d85c84, 0x7c88bd1b47ca1f55, 0xa6988e9a64af8ec2, 0xc082c062d0, 0x7, 0xc082c7a000, 0x9d, 0x9d, ...)
        C:/Go/bin/src/github.com/syncthing/syncthing/lib/model/model.go:550 +0x993
github.com/syncthing/syncthing/lib/protocol.nativeModel.Index(0x1542c40, 0xc0820de900, 0x6ff5fcdb815ef42f, 0xc9968ddc40d85c84, 0x7c88bd1b47ca1f55, 0xa6988e9a64af8ec2, 0xc082c062d0, 0x7, 0xc082c7a000, 0x9d, ...)
        C:/Go/bin/src/github.com/syncthing/syncthing/lib/protocol/nativemodel_windows.go:29 +0x10f
github.com/syncthing/syncthing/lib/protocol.(*nativeModel).Index(0xc082a17460, 0x6ff5fcdb815ef42f, 0xc9968ddc40d85c84, 0x7c88bd1b47ca1f55, 0xa6988e9a64af8ec2, 0xc082c062d0, 0x7, 0xc082c7a000, 0x9d, 0x9d, ...)
        <autogenerated>:85 +0x12d
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).handleIndex(0xc082b8e000, 0xc082c062d0, 0x7, 0xc082c7a000, 0x9d, 0x9d, 0x0, 0x0, 0x0, 0x0)
        C:/Go/bin/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:492 +0x397
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).readerLoop(0xc082b8e000, 0x0, 0x0)
        C:/Go/bin/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:338 +0xff3
created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start
        C:/Go/bin/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:193 +0x40
```

**Comment by AudriusButkevicius** [comment]
Can repro very reliably.

**Comment by AudriusButkevicius** [comment]
```diff
diff --git a/lib/db/leveldb_transactions.go b/lib/db/leveldb_transactions.go
index 5415f56..8eed730 100644
--- a/lib/db/leveldb_transactions.go
+++ b/lib/db/leveldb_transactions.go
@@ -103,6 +105,8 @@ func (t readWriteTransaction) updateGlobal(folder, device []byte, file protocol.
        if svl != nil {
                err = fl.UnmarshalXDR(svl)
                if err != nil {
+                       fmt.Printf("%#v %t", svl, svl == nil)
```

Prints
```
[]byte{} false
```
