### ISSUE TITLE
Panic/crash when relaysEnabled=false, localAnnounceEnabled=true

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2890]
Since the last refactor, we pass a nil relayService to the local discovery announcer, which it tries to call the Relays() method on.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x2a6f52]

goroutine 1 [running]:
panic(0x7273a0, 0xc820010140)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/syncthing/syncthing/lib/discover.NewLocal(0x641267a0a76257db, 0x8ab238bdf002e6f, 0xa6e5f4e8a9dcef4b, 0x1a08700b7787db7c, 0xc8204b6998, 0x6, 0x1e01d18, 0xc820430960, 0x0, 0x0, ...)
	/Users/jb/src/github.com/syncthing/syncthing/lib/discover/local.go:53 +0x272
main.syncthingMain(0x7fff5fbff9b0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x80fbc0, 0x1, 0x0, 0x0, ...)
	/Users/jb/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:768 +0x3142
main.main()
	/Users/jb/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:366 +0x95a
```

**Comment by AudriusButkevicius** [comment]
Wasn't that always the case?

**Comment by calmh** [comment]
I broke this in a492cfba13db36fae86b118eea4fb1d231eb9f13 by making the it an interface. Previously it was ok to call methods on the nil *relay.Service, but once it's an interface that's no longer the case.
