### ISSUE TITLE
Deadlock when connecting

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3066]
```
goroutine 67 [semacquire, 8 minutes]:
sync.runtime_Semacquire(0xc82041bb2c)
        /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*RWMutex).RLock(0xc82041bb20)
        /usr/local/go/src/sync/rwmutex.go:37 +0x58
github.com/syncthing/syncthing/lib/connections.(*Service).CommitConfiguration(0xc821aa3a40, 0xd, 0xc82002b800, 0x3, 0x4, 0xc820064000, 0x3, 0x4, 0x1, 0xc8204c5bc0, ...)
        /Users/jb/src/github.com/syncthing/syncthing/lib/connections/service.go:405 +0x2d4
github.com/syncthing/syncthing/lib/config.(*Wrapper).replaceLocked(0xc8200c3600, 0xd, 0xc821ec0600, 0x3, 0x3, 0xc821948b40, 0x3, 0x3, 0x1, 0xc8204c5bc0, ...)
        /Users/jb/src/github.com/syncthing/syncthing/lib/config/wrapper.go:153 +0x734
github.com/syncthing/syncthing/lib/config.(*Wrapper).SetDevice(0xc8200c3600, 0x22d33fe030900e17, 0xe217936a7da3cc8c, 0x554dd932a7e97d0a, 0x1c494e2220a0eadf, 0xc822f7ce88, 0x4, 0xc8201acb40, 0x1, 0x4, ...)
        /Users/jb/src/github.com/syncthing/syncthing/lib/config/wrapper.go:202 +0x31d
github.com/syncthing/syncthing/lib/model.(*Model).AddConnection(0xc8200883c0, 0xc820310000, 0x864210, 0xc, 0xa, 0x17145f0, 0xc822f7cf10, 0xc822f7ce88, 0x4, 0xc822f7ce90, ...)
        /Users/jb/src/github.com/syncthing/syncthing/lib/model/model.go:1053 +0xfe5
github.com/syncthing/syncthing/lib/connections.(*Service).handle(0xc821aa3a40)
        /Users/jb/src/github.com/syncthing/syncthing/lib/connections/service.go:226 +0x1d53
github.com/syncthing/syncthing/lib/connections.(*Service).(github.com/syncthing/syncthing/lib/connections.handle)-fm()
        /Users/jb/src/github.com/syncthing/syncthing/lib/connections/service.go:102 +0x20
github.com/syncthing/syncthing/lib/connections.serviceFunc.Serve(0xc8216f9750)
        /Users/jb/src/github.com/syncthing/syncthing/lib/connections/structs.go:73 +0x19
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1(0xc820855520, 0x1, 0x1709950, 0xc8216f9750)
        /Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/suture.go:556 +0x5e
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService
        /Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/suture.go:559 +0x51
```

Or, with words,

1. Connection service calls AddConnection while holding the connection service lock
1. AddConnection updates the device name and calls config.SetDevice
1. config.SetDevice calls CommitConfiguration everywhere
1. Connection service CommitConfiguration wants the lock

**Comment by AudriusButkevicius** [comment]
Wat, I though I fixed this, maybe before the conn refactor.
