### ISSUE TITLE
Toggling HTTP/HTTPS breaks GUI/API

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3136]
Toggling the setting and saving the config in the GUI results in the log line:

```
[SYNO4] 20:46:01 WARNING: API: accept tcp 127.0.0.1:8385: use of closed network connection
```

And then there is nothing listening on the GUI port any more.

v0.13.1

**Comment by calmh** [comment]
So now of course I can't reproduce this myself any more...

**Comment by norgeous** [comment]
I can get this same error / similar by rapidly setting `Use HTTPS for GUI` on and off or by rapidly switching between themes. It happens if you ignore the 'restart needed' warning message, and just keep saving settings.

**Comment by norgeous** [comment]
just got the following, using the above method. idk if helpful.
```log
[W6SBY] 01:00:36 WARNING: API: accept tcp 127.0.0.1:8384: use of closed network connection
2016/05/29 01:00:45 http: panic serving 127.0.0.1:58129: runtime error: invalid memory address or nil pointer dereference
goroutine 618 [running]:
net/http.(*conn).serve.func1(0xc0839e6000)
	c:/go/src/net/http/server.go:1389 +0xc8
panic(0xb792e0, 0xc082002070)
	c:/go/src/runtime/panic.go:443 +0x4f7
main.(*apiService).CommitConfiguration(0xc082053e00, 0xf, 0xc083bf0400, 0x1, 0x4, 0xc082037d40, 0x2, 0x4, 0x1, 0xc0843b9cb0, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:402 +0x145
github.com/syncthing/syncthing/lib/config.(*Wrapper).replaceLocked(0xc082001b80, 0xf, 0xc0848bcc00, 0x1, 0x4, 0xc0830501a0, 0x2, 0x4, 0x1, 0xc0826396e0, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/config/wrapper.go:153 +0x73b
github.com/syncthing/syncthing/lib/config.(*Wrapper).Replace(0xc082001b80, 0xf, 0xc0848bcc00, 0x1, 0x4, 0xc0830501a0, 0x2, 0x4, 0x1, 0xc0826396e0, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/config/wrapper.go:134 +0xfa
main.(*apiService).postSystemConfig(0xc082053e00, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:763 +0x52f
main.(*apiService).(main.postSystemConfig)-fm(0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:274 +0x45
net/http.HandlerFunc.ServeHTTP(0xc08401e8d0, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1618 +0x41
net/http.(*ServeMux).ServeHTTP(0xc082069dd0, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1910 +0x184
main.getPostHandler.func1(0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:425 +0x146
net/http.HandlerFunc.ServeHTTP(0xc082069e00, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1618 +0x41
main.metricsMiddleware.func1(0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:493 +0xd8
net/http.HandlerFunc.ServeHTTP(0xc083f99c20, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1618 +0x41
main.noCacheMiddleware.func1(0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:516 +0x1e3
net/http.HandlerFunc.ServeHTTP(0xc083f99c40, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1618 +0x41
net/http.(*ServeMux).ServeHTTP(0xc082069e60, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1910 +0x184
main.csrfMiddleware.func1(0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui_csrf.go:40 +0x14c
net/http.HandlerFunc.ServeHTTP(0xc084457c20, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1618 +0x41
main.withDetailsMiddleware.func1(0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:524 +0x12e
net/http.HandlerFunc.ServeHTTP(0xc0839a0180, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1618 +0x41
main.redirectToHTTPSMiddleware.func1(0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:506 +0x11c
net/http.HandlerFunc.ServeHTTP(0xc083ad42a0, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1618 +0x41
main.corsMiddleware.func1(0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:484 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc083ad42c0, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1618 +0x41
main.debugMiddleware.func1(0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:435 +0xa2
net/http.HandlerFunc.ServeHTTP(0xc083ad42e0, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:1618 +0x41
net/http.serverHandler.ServeHTTP(0xc08452fd80, 0x3228460, 0xc084c3b2b0, 0xc0827caa80)
	c:/go/src/net/http/server.go:2081 +0x1a5
net/http.(*conn).serve(0xc0839e6000)
	c:/go/src/net/http/server.go:1472 +0xf35
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:2137 +0x455
```

**Comment by canton7** [comment]
I can also reproduce this by toggling the theme and waiting for a few minutes. It clears after restarting Syncthing.

**Comment by canton7** [comment]
(Edited)

**Comment by canton7** [comment]
It's also worth noting that the issue comes and goes across page refreshes, until Syncthing is restarted.

**Comment by canton7** [comment]
Right, part of the issue is that we hit the return at the top of `Serve()` in `gui.go`:

```go
	if listener == nil {
		l.Warnln("No listener, so quitting");
		// Not much we can do here other than exit quickly. The supervisor
		// will log an error at some point.
		return
	}
```

Gives

```
[PFQTJ] 10:59:37 WARNING: API: accept tcp 127.0.0.1:8080: use of closed network connection
[PFQTJ] 10:59:37 WARNING: No listener, so quitting
[PFQTJ] 10:59:37 WARNING: No listener, so quitting
[PFQTJ] 10:59:37 WARNING: No listener, so quitting
[PFQTJ] 10:59:52 WARNING: No listener, so quitting
[PFQTJ] 10:59:52 WARNING: No listener, so quitting
[PFQTJ] 10:59:52 WARNING: No listener, so quitting
[PFQTJ] 10:59:52 WARNING: No listener, so quitting
[PFQTJ] 10:59:52 WARNING: No listener, so quitting
[PFQTJ] 10:59:52 WARNING: No listener, so quitting
[PFQTJ] 11:00:07 WARNING: No listener, so quitting
[PFQTJ] 11:00:07 WARNING: No listener, so quitting
[PFQTJ] 11:00:07 WARNING: No listener, so quitting
```
