### ISSUE TITLE
Panic in jackpal/gateway.DiscoverGateway

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3142]
Panic in gateway detection, as reported on irc:

```
02:28:26 <> it happens on 2 different setups (desktop and laptop)
02:28:46 <> and i'm pretty sure it happens every time after windows comes back from sleep
02:28:58 <> (and only then, as far as i can tell)
```

```
panic: runtime error: index out of range
goroutine 38788 [running]:
panic(0xb76840, 0xc082002020)
	c:/go/src/runtime/panic.go:481 +0x3f4
github.com/syncthing/syncthing/vendor/github.com/jackpal/gateway.DiscoverGateway(0x0, 0x0, 0x0, 0x0, 0x0)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/vendor/github.com/jackpal/gateway/gateway_windows.go:37 +0x4e6
github.com/syncthing/syncthing/lib/pmp.Discover(0x1a3185c5000, 0x2540be400, 0x0, 0x0, 0x0)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/pmp/pmp.go:25 +0x48
github.com/syncthing/syncthing/lib/nat.discoverAll.func1(0x1a3185c5000, 0x2540be400, 0xc082218cc0, 0x30e3218, 0xc082e7a740, 0xdd8aa0)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/nat/registry.go:32 +0x4c
created by github.com/syncthing/syncthing/lib/nat.discoverAll
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/nat/registry.go:36 +0x1bb
```

(v0.13.something, doesn't matter as this code is the same so far)

**Comment by calmh** [comment]
Solved in a PR on jackpal/gateway, I'll give it a day or so to see if it gets accepted before ugly-hacking something with our vendoring...
