### ISSUE TITLE
Panic when sending download progress message

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3145]
This happens when a file that we have sent download progress for fails (due to the final `rename` not being possible, for example):

```
[I6KAH] 16:52:34 INFO: Device MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC client is "syncthing v0.13.2+1-g709560e-dirty-remotecomp" named "s2"
[I6KAH] 16:52:56 INFO: Connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC closed: EOF
[I6KAH] 16:52:56 INFO: Puller (folder "default", file "file8"): pull: peers who had this file went away, or the file has changed while syncing. will retry later
[I6KAH] 16:52:56 INFO: Puller: final: peers who had this file went away, or the file has changed while syncing. will retry later
[I6KAH] 16:52:56 INFO: Puller (folder "default", file "file7"): pull: peers who had this file went away, or the file has changed while syncing. will retry later
[I6KAH] 17:05:34 INFO: Puller: final: rename /Users/jb/src/github.com/syncthing/syncthing/test/s1/locked/.syncthing.file6.tmp /Users/jb/src/github.com/syncthing/syncthing/test/s1/locked/file6: operation not permitted
Panic at 2016-05-22T17:05:39+09:00
panic: runtime error: slice bounds out of range

goroutine 55 [running]:
panic(0x765640, 0xc820010110)
        /Users/jb/go/src/runtime/panic.go:481 +0x3e6
github.com/syncthing/syncthing/lib/model.(*sentFolderDownloadState).update(0xc8202a8108, 0xc820b800f0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/jb/src/github.com/syncthing/syncthing/lib/model/sentdownloadstate.go:95 +0x102f
github.com/syncthing/syncthing/lib/model.(*sentDownloadState).update(0xc8202a80f8, 0xc8204a2070, 0x7, 0xc820b800f0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/jb/src/github.com/syncthing/syncthing/lib/model/sentdownloadstate.go:162 +0x186
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).sendDownloadProgressMessages(0xc82026a500)
        /Users/jb/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:137 +0x76f
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve(0xc82026a500)
        /Users/jb/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:79 +0x761
created by github.com/syncthing/syncthing/lib/model.NewModel
        /Users/jb/src/github.com/syncthing/syncthing/lib/model/model.go:150 +0xbec
```

**Comment by calmh** [comment]
I'm guessing what happens here is that the puller is torn down and a new one is created when we retry. The new puller has less blocks available because it hasn't checked the entire temp file yet. When the progress emitter polls everything and send it to the download progress tracker thingy, it sees a puller for a file it already knows about and assumes it must have made progress (the comment above the panicing line says as much). But that assumption doesn't hold as it's actually a *new* puller for the same file name.

**Comment by AudriusButkevicius** [comment]
Yes, writing a fix now.

**Comment by calmh** [comment]
I did

```diff
diff --git a/lib/model/sentdownloadstate.go b/lib/model/sentdownloadstate.go
index 9fd50b0..77651fa 100644
--- a/lib/model/sentdownloadstate.go
+++ b/lib/model/sentdownloadstate.go
@@ -70,7 +70,7 @@ func (s *sentFolderDownloadState) update(pullers []*sharedPullerState) []protoco
 			continue
 		}
 
-		if !pullerVersion.Equal(localFile.version) {
+		if !pullerVersion.Equal(localFile.version) || len(pullerBlockIndexes) < len(localFile.blockIndexes) {
 			// The version has changed, clean up whatever we had for the old
 			// file, and advertise the new file.
 			updates = append(updates, protocol.FileDownloadProgressUpdate{
```

which works, but I was going to add a test as well :)

**Comment by calmh** [comment]
Also, this was caused by us not reusing temp files properly in my test case, so should be fairly rare in reality when that is fixed.

**Comment by calmh** [comment]
And I still haven't reproduced the completion > 100% thing yet, even though I'm uncovering other interesting corner cases in the process...

**Comment by AudriusButkevicius** [comment]
This is not the right fix tho, as it's still possible to get a file pulled in a different order and able to pull more blocks than what we had before.
