### ISSUE TITLE
leveldb/table: corruption on data-block (checksum mismatch)

### ISSUE THREAD

**Issue by yeled** [syncthing/syncthing#3157]
panic on sync (download to fresh client)

### Version Information

Syncthing Version: v0.13.2
OS Version: Linux synology 3.10.77 #7321 SMP Mon Apr 25 15:58:40 CST 2016 x86_64 GNU/Linux synology_braswell_716+

```
[UFUQD] 18:41:18 INFO: syncthing v0.13.2 "Copper Cockroach" (go1.6.2 linux-amd64) unknown-user@9c88c96d5969 2016-05-21 13:49:37 UTC
[UFUQD] 18:41:18 INFO: My ID: UFUQD6E-7TUP2L7-ODIX7T3-4BB5VXZ-ANJQP7A-HYXY3N5-IUYNFBH-45GYGQZ
[UFUQD] 18:41:18 INFO: Single thread hash performance is ~55 MB/s
...
Panic at 2016-05-22T18:41:44+01:00
panic: leveldb/table: corruption on data-block (pos=223804): checksum mismatch, want=0x9c458748 got=0x1c2e6000 [file=002051.ldb]
	panic: leveldb/table: corruption on data-block (pos=223804): checksum mismatch, want=0x9c458748 got=0x1c2e6000 [file=002051.ldb]

goroutine 1 [running]:
panic(0xb2a1c0, 0xc820df6260)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/syncthing/syncthing/lib/db.readWriteTransaction.close(0xc820273b90, 0xc8201fc220, 0xc820ee1d00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:59 +0x81
panic(0xb2a1c0, 0xc820df6260)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/syncthing/syncthing/lib/db.readWriteTransaction.checkFlush(0xc820273b90, 0xc8201fc220, 0xc820ee1d00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:67 +0x94
github.com/syncthing/syncthing/lib/db.(*Instance).genericReplace(0xc8201fc220, 0xc82161f320, 0x8, 0x8, 0xc821da8500, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:183 +0xd0a
github.com/syncthing/syncthing/lib/db.(*Instance).replace(0xc8201fc220, 0xc82161f320, 0x8, 0x8, 0xc821da8500, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:197 +0xd5
github.com/syncthing/syncthing/lib/db.(*FileSet).Replace(0xc82014b080, 0x227e10f643999651, 0xae39db6e080844a3, 0xe7fa6b1e556f584a, 0xe6f43353fe0769f6, 0x0, 0x0, 0x0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:128 +0x409
github.com/syncthing/syncthing/lib/model.(*Model).Index(0xc821c1e000, 0x227e10f643999651, 0xae39db6e080844a3, 0xe7fa6b1e556f584a, 0xe6f43353fe0769f6, 0xc820483420, 0x8, 0x0, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:548 +0xb4b
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc53cd0, 0x1, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:686 +0x3d5d
main.main()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:362 +0x95a
```

**Comment by AudriusButkevicius** [comment]
Please search existing closed issues.

**Comment by 5chdn** [comment]
#2734 has the best fix description so far.

> There is no way to recover from this apart from nuking index directory in syncthings home directory (check -help).

And, the best snippet: 

> I deleted only the corrupted file and it is working again.

See also #987 #1853 #1949 #2479 and so on.
