### ISSUE TITLE
panic: creating temporary database: invalid argument

### ISSUE THREAD

**Issue by erikvanoosten** [syncthing/syncthing#3956]
I am trying to get syncthing running in a Ubuntu RKT image. Upon startup Syncthing generates the following panic file (all id's and ip's obscured/changed):

```
[HNNA3] 08:23:49 INFO: syncthing v0.14.21 "Dysprosium Dragonfly" (go1.8rc2 linux-amd64) jenkins@build.syncthing.net 2017-01-25 07:33:35 UTC
[HNNA3] 08:23:49 INFO: My ID: XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
[HNNA3] 08:23:50 INFO: Single thread SHA256 performance is 67 MB/s using minio/sha256-simd (56 MB/s using crypto/sha256).
[HNNA3] 08:23:52 INFO: Actual hashing performance is 52.24 MB/s
[HNNA3] 08:23:52 INFO: Ready to synchronize "xxxxx xxxxx" (xxxxx) (readwrite)
[HNNA3] 08:23:54 INFO: Ready to synchronize "xxxxx xxxxx" (xxxxx) (readwrite)
[HNNA3] 08:23:54 INFO: Ready to synchronize "xxxxx xxxxx" (xxxxx) (readwrite)
[HNNA3] 08:23:58 INFO: Ready to synchronize "xxxxx xxxxx" (xxxxx) (readwrite)
[HNNA3] 08:23:58 INFO: Ready to synchronize "xxxxx xxxxx" (xxxxx) (readwrite)
[HNNA3] 08:23:58 INFO: Send rate is unlimited, receive rate is unlimited
...
[HNNA3] 08:23:58 INFO: Rate limits do not apply to LAN connections
[HNNA3] 08:23:58 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
[HNNA3] 08:23:58 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
[HNNA3] 08:23:58 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
[HNNA3] 08:23:58 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
[HNNA3] 08:23:58 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
[HNNA3] 08:23:58 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
[HNNA3] 08:23:58 INFO: TCP listener ([::]:22000) starting
[HNNA3] 08:23:59 INFO: Device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX is "xxxxxx" at [tcp://192.168.1.1:22001]
[HNNA3] 08:23:59 INFO: Device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX is "xxxxxx" at [dynamic tcp://192.168.1.2:22002]
[HNNA3] 08:23:59 INFO: Device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX is "xxxxxx" at [dynamic]
[HNNA3] 08:23:59 INFO: Device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX is "xxxxxx" at [dynamic]
[HNNA3] 08:23:59 INFO: Device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX is "xxxxxx" at [dynamic]
[HNNA3] 08:23:59 INFO: Completed initial scan (rw) of "xxxxx xxxxx" (xxxxx)
[HNNA3] 08:23:59 INFO: GUI and API listening on [::]:1090
[HNNA3] 08:23:59 INFO: Access the GUI via the following URL: http://127.0.0.1:1090/
[HNNA3] 08:23:59 INFO: Completed initial scan (rw) of "xxxxx xxxxx" (xxxxx)
[HNNA3] 08:23:59 INFO: Cleaned away old file tmp-index-sorter.073918388
[HNNA3] 08:23:59 INFO: Completed initial scan (rw) of "xxxxx xxxxx" (xxxxx)
[HNNA3] 08:24:20 INFO: Established secure connection to XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX at 192.168.1.1:59534-192.168.1.1:22001 (tcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[HNNA3] 08:24:20 INFO: Device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX client is "syncthing v0.14.21" named "xxxxxx"
Panic at 2017-02-05T08:24:21+01:00
panic: creating temporary database: sync /srv/config/tmp-index-sorter.851219453: invalid argument

goroutine 378 [running]:
github.com/syncthing/syncthing/lib/model.newOnDiskIndexSorter(0xc42000a4a0, 0xb, 0x18)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/sorter.go:148 +0x33f
github.com/syncthing/syncthing/lib/model.(*autoSwitchingIndexSorter).Append(0xc420698000, 0xc4218708e0, 0x1d, 0x0, 0x3655, 0x1b0, 0x58833600, 0x306c9db2, 0x0, 0x10000, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/sorter.go:63 +0x143
github.com/syncthing/syncthing/lib/model.sendIndexTo.func1(0xfd4060, 0xc42264d710, 0xfd4060)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:1526 +0x14d
github.com/syncthing/syncthing/lib/db.nativeFileIterator.func1(0xfd4060, 0xc42264d680, 0x70)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:358 +0x21a
github.com/syncthing/syncthing/lib/db.(*Instance).withHave(0xc420166db0, 0xc421258950, 0xe, 0x10, 0xc420698020, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:267 +0x387
```

As the panic file can be written this excludes file access problems. After the panic syncthing restarts.

Note: `/srv/config` is a CIFS mount that does not support extended unix attributes. If I read mount.cifs documentation correctly, the volume allows attribute change commands, however, they should have no effect.

It is mounted as follows in `/etc/fstab`: `//nas/volume /media/cifsmount cifs credentials=/root/smbcredentials,iocharset=utf8,sec=ntlm,noperm,uid=0,gid=100 0 0`

### Version Information

Syncthing Version: v0.14.21
Host OS Version: Ubuntu 16.04
Guest OS Version: Ubuntu 16.04 (https://github.com/Blitznote/docker-ubuntu-debootstrap)
Rkt: 1.23.0

**Comment by calmh** [comment]
I expect there are issues around locking or similar on the CIFS mount. Is the regular index database also in /srv/config?

**Comment by erikvanoosten** [comment]
I think its in the same place. Syncthing is invoked as: `syncthing -home=/srv/config`. The data resides in another directory.

I tried to run the same image mounted to regular directories and that works fine.

**Comment by calmh** [comment]
Hmm. Looking closer at the error, it's apparently the `sync()` call that returns `invalid argument`. I'm surprised anything works at all, as it should fail in the same way when opening the "main" database. That said, the filesystem not supporting `sync()` is fundamentally unsafe and I'd recommend not doing what you do.

Maybe we should not panic, though. Leaving open to consider that for a while.

**Comment by erikvanoosten** [comment]
I am no FS expert but I am surprised sync is not supported on cifs. Thanks for looking, at least now I know running syntching over a cifs filesystem is not a good idea.

**Comment by calmh** [comment]
I'm surprised too, and I would think it is supported in the normal case. But perhaps not for directories, or not at the time this happened due to a network failure or something. Maybe the database only syncs directories at database creation time, and you moved the existing index db to /srv/config instead of having Syncthing create it there to start with? Who knows :)

**Comment by calmh** [comment]
In the end, the database needs certain things to work. If they don't, on CIFS, then that is not a supported config. Sorry.

**Comment by erikvanoosten** [comment]
I understand. But please consider failing with a more informative error message.
