### ISSUE TITLE
fatal error: sweep increased allocation count

### ISSUE THREAD

**Issue by zuf** [syncthing/syncthing#4013]
Syncthing reports about panic at start.
Maybe this issue related to some kind of database corruption.

panic.log:
```
...
Panic at 2017-03-01T12:35:01+03:00
fatal error: sweep increased allocation count

runtime stack:
runtime.throw(0xadc183, 0x20)
	/usr/bin/src/runtime/panic.go:566 +0x95
runtime.(*mspan).sweep(0x7f3bc030a288, 0x2300000000, 0xc400000201)
	/usr/bin/src/runtime/mgcsweep.go:287 +0x7ab
runtime.sweepone(0x46c2b6)
	/usr/bin/src/runtime/mgcsweep.go:112 +0xfe
runtime.gosweepone.func1()
	/usr/bin/src/runtime/mgcsweep.go:124 +0x2b
runtime.systemstack(0xc420023500)
	/usr/bin/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/bin/src/runtime/proc.go:1079

goroutine 3 [running]:
runtime.systemstack_switch()
	/usr/bin/src/runtime/asm_amd64.s:252 fp=0xc42002ef48 sp=0xc42002ef40
runtime.gosweepone(0x1)
	/usr/bin/src/runtime/mgcsweep.go:125 +0x53 fp=0xc42002ef78 sp=0xc42002ef48
runtime.bgsweep(0xc42005e000)
	/usr/bin/src/runtime/mgcsweep.go:66 +0xbb fp=0xc42002efb8 sp=0xc42002ef78
runtime.goexit()
	/usr/bin/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42002efc0 sp=0xc42002efb8
created by runtime.gcenable
	/usr/bin/src/runtime/mgc.go:195 +0x61

goroutine 1 [runnable]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table.(*block).seek.func1(0xbf, 0xc420032301)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:65
sort.Search(0x3ac, 0xc420c5f470, 0x47a1ab)
	/usr/bin/src/sort/search.go:66 +0x66
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table.(*block).seek(0xc4209e70c0, 0xf54800, 0xc42020eec0, 0x0, 0x3ac, 0xc420169810, 0xae, 0xae, 0xc420c5f538, 0x91041d, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:72 +0xc5
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table.(*blockIter).Seek(0xc420b2a1e0, 0xc420169810, 0xae, 0xae, 0x0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:232 +0xa5
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).find(0xc4214961a0, 0xc420169810, 0xae, 0xae, 0x463501, 0x0, 0x81a000, 0x0, 0x0, 0x0, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:833 +0x25d
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).Find(0xc4214961a0, 0xc420169810, 0xae, 0xae, 0x1, 0x0, 0xae, 0xffffffffffffffff, 0xc420c5f790, 0xc420c5f750, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:917 +0x7a
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*tOps).find(0xc42052a120, 0xc420016d20, 0xc420169810, 0xae, 0xae, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table.go:382 +0x1f1
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*version).get.func1(0x1, 0xc420016d20, 0xa6)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/version.go:176 +0x4f1
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*version).walkOverlapping(0xc4201f0140, 0x0, 0x0, 0x0, 0xc420169810, 0xae, 0xae, 0xc420c5fa10, 0xc420c5f9e0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/version.go:125 +0x49c
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*version).get(0xc4201f0140, 0x0, 0x0, 0x0, 0xc420169810, 0xae, 0xae, 0x0, 0x0, 0x0, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/version.go:230 +0x303
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).get(0xc42018cc00, 0x0, 0x0, 0x0, 0x0, 0xc4201de300, 0xa6, 0xfb, 0xd67f17, 0x0, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:776 +0x2af
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*Snapshot).Get(0xc4215a5b90, 0xc4201de300, 0xa6, 0xfb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_snapshot.go:113 +0x1a0
github.com/syncthing/syncthing/lib/db.(*Instance).checkGlobals(0xc420180f30, 0xc420829ed8, 0x6, 0x8, 0xc4204bd458)
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:595 +0x495
github.com/syncthing/syncthing/lib/db.NewFileSet(0xc420142f20, 0x6, 0xc420180f30, 0xc420c603c8)
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/db/set.go:125 +0x229
github.com/syncthing/syncthing/lib/model.(*Model).addFolderLocked(0xc4209ed7c0, 0xc420142f20, 0x6, 0x0, 0x0, 0xc4201ab960, 0x11, 0x0, 0xc4204fbd00, 0x3, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/model/model.go:315 +0xc2
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0xc4209ed7c0, 0xc420142f20, 0x6, 0x0, 0x0, 0xc4201ab960, 0x11, 0x0, 0xc4204fbd00, 0x3, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/model/model.go:309 +0x94
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xac3d74, 0x1, 0x0, 0x0, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:805 +0x2ad7
main.main()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:444 +0x4a5

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/bin/src/runtime/asm_amd64.s:2086 +0x1

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
	/usr/bin/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/bin/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/bin/src/os/signal/signal_unix.go:28 +0x41

goroutine 9 [chan receive]:
main.trackCPUUsage()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xf9
created by main.init.3
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x35

goroutine 10 [select, locked to thread]:
runtime.gopark(0xca4b58, 0x0, 0xac6d43, 0x6, 0x18, 0x2)
	/usr/bin/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42003ef20, 0x0, 0x18)
	/usr/bin/src/runtime/select.go:423 +0x1235
runtime.selectgo(0xc42003ef20)
	/usr/bin/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/bin/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/bin/src/runtime/asm_amd64.s:2086 +0x1

goroutine 11 [chan receive]:
main.setupSignalHandling.func1(0xc42001c960)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:959 +0x40
created by main.setupSignalHandling
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:961 +0xfa

goroutine 12 [chan receive]:
main.setupSignalHandling.func2(0xc42001cae0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:969 +0x40
created by main.setupSignalHandling
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:971 +0x1f5

goroutine 13 [select]:
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).Serve(0xc4200f8460)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:338 +0xe61
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).ServeBackground
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:297 +0x43

goroutine 14 [select]:
main.(*verboseService).Serve(0xc4201a6690)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/verboseservice.go:44 +0x2e1
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1(0xc4200f8460, 0x0, 0xf505c0, 0xc4201a6690)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:454 +0x63
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:457 +0x5b

goroutine 15 [chan receive]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0xc420017e50)
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/events/events.go:318 +0x83
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/events/events.go:313 +0x1d3

goroutine 16 [chan receive]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0xc420017ea0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/events/events.go:318 +0x83
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/events/events.go:313 +0x1d3

goroutine 50 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc4200f8000)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x247
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x1bc

goroutine 24 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc42018cc00)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x5e1
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x592

goroutine 25 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc42018cc00)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:96 +0x249
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x5b4

goroutine 26 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc42018cc00)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x83c
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x73a

goroutine 27 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc42018cc00)
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x263
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/build/syncthing/src/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x75c

goroutine 29 [select]:
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve(0xc420211ef0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:56 +0x586
created by github.com/syncthing/syncthing/lib/model.NewModel
	/build/syncthing/src/src/github.com/syncthing/syncthing/lib/model/model.go:166 +0x9ef
```

### Version Information

Syncthing Version: v0.14.23
OS Version: Arch Linux

**Comment by calmh** [comment]
You left out the beginning of the log that contains version information etc. Can has?

Is this reproducible?

**Comment by zuf** [comment]
I see this error every time, syncthing doesn't start.

Maybe this panic happend after my disk get full and some data inside syncting didn't write correctly.

Beginning of the log:

```
[AHLCK] 12:23:17 INFO: syncthing v0.14.23 "Dysprosium Dragonfly" (go1.7.5 linux-amd64) builduser@bpiotrowski 2017-02-07 21:49:19 UTC
[AHLCK] 12:23:17 INFO: My ID: AHLCKEB-A76A5LO-YD3PXYN-LF3G5SP-KXY63GT-3NDW3JY-NOFRM7T-J3G47QN
[AHLCK] 12:23:18 INFO: Single thread SHA256 performance is 209 MB/s using crypto/sha256 (48 MB/s using minio/sha256-simd).
[AHLCK] 12:23:18 INFO: Hashing performance with weak hash is 190.30 MB/s
[AHLCK] 12:23:18 INFO: Hashing performance without weak hash is 203.67 MB/s
[AHLCK] 12:23:18 VERBOSE: Starting up (/home/zuf/.config/syncthing)
[AHLCK] 12:23:18 INFO: Weak hash enabled, as it has an acceptable performance impact.
[AHLCK] 12:23:19 INFO: Ready to synchronize A6000 (readwrite)
```

**Comment by AudriusButkevicius** [comment]
Try using an official build.

**Comment by calmh** [comment]
Yeah. And if that behaves the same, if you could tar up the config dir and index data se and pass it over somehow, i'd like to see if I can debug it next week. (Exclude the .pem files from the archive)

**Comment by zuf** [comment]
With official build I got another panic:

```
2017/03/01 13:12:17 http: panic serving 127.0.0.1:47868: no versions?
goroutine 582 [running]:
net/http.(*conn).serve.func1(0xc422186820)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xa3c520, 0xc421e94360)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/syncthing/syncthing/lib/db.(*Instance).withNeed(0xc420678c30, 0xc421e94290, 0x5, 0x8, 0xc421b8d0b0, 0x20, 0x20, 0xc420658201, 0xc421e942b0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:449 +0x1718
github.com/syncthing/syncthing/lib/db.(*FileSet).WithNeedTruncated(0xc420079f40, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc421666e40)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:206 +0x1fb
github.com/syncthing/syncthing/lib/model.(*Model).NeedSize(0xc420170f00, 0xc421e254bb, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:604 +0x542
main.folderSummary(0xfdcbe0, 0xc4200a6000, 0xfdee20, 0xc420170f00, 0xc421e254bb, 0x5, 0x0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:642 +0x8c2
main.(*apiService).getDBStatus(0xc422222000, 0xfd7d80, 0xc4203df880, 0xc4205dcc00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:628 +0x78
main.(*apiService).(main.getDBStatus)-fm(0xfd7d80, 0xc4203df880, 0xc4205dcc00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:234 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420659470, 0xfd7d80, 0xc4203df880, 0xc4205dcc00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc421680f30, 0xfd7d80, 0xc4203df880, 0xc4205dcc00)
	/usr/local/go/src/net/http/server.go:2238 +0x130
main.getPostHandler.func1(0xfd7d80, 0xc4203df880, 0xc4205dcc00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:411 +0x11c
net/http.HandlerFunc.ServeHTTP(0xc421681050, 0xfd7d80, 0xc4203df880, 0xc4205dcc00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
main.metricsMiddleware.func1(0xfd7d80, 0xc4203df880, 0xc4205dcc00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:483 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc4202014a0, 0xfd7d80, 0xc4203df880, 0xc4205dcc00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
```

But after restart with `-reset-database -reset-deltas` flags things gone sane.
Looks like some weird issue related to my environment. Thank you for assistance!

**Comment by calmh** [comment]
The "no versions?" thing is a typical database corruption error, yes. We should maybe handle those more gracefully, but that's a different issue.
