### ISSUE TITLE
lib/sync: Spurious TestRWMutex failure on windows

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4213]
```
2017/06/14 12:10:49.898571 sync.go:106: DEBUG: Mutex held for 125.000001ms. Locked at sync\sync_test.go:87 unlocked at sync\sync_test.go:89
2017/06/14 12:10:49.900517 sync.go:158: DEBUG: RWMutex held for 125.000001ms. Locked at sync\sync_test.go:127 unlocked at sync\sync_test.go:129
--- FAIL: TestRWMutex (0.00s)
	sync_test.go:154: Unexpected message count
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 22 [running]:
testing.tRunner.func1(0xc042046ea0)
	c:/go/src/testing/testing.go:622 +0x566
panic(0x5e9160, 0x10a11e0)
	c:/go/src/runtime/panic.go:489 +0x2fe
github.com/syncthing/syncthing/lib/sync.TestRWMutex(0xc042046ea0)
	c:/jenkins/workspace/syncthing-pr-windows/src/github.com/syncthing/syncthing/lib/sync/sync_test.go:156 +0x7cd
testing.tRunner(0xc042046ea0, 0x61b3c8)
	c:/go/src/testing/testing.go:657 +0x10f
created by testing.(*T).Run
	c:/go/src/testing/testing.go:697 +0x54b
FAIL	github.com/syncthing/syncthing/lib/sync	0.053s
```

https://build.syncthing.net/job/syncthing-pr-windows/2520/console

**Comment by calmh** [comment]
Been a while
