### ISSUE TITLE
illegal hardware instruction on 0.14.33

### ISSUE THREAD

**Issue by brycied00d** [syncthing/syncthing#4285]
It's me, I'm back with another "illegal instruction" immediately on startup on Linux i386.

This started with 0.14.33, and exists in 0.14.34rc1 (https://github.com/syncthing/syncthing/releases/tag/v0.14.34-rc.1); the previous stable version 0.14.32 runs fine.

### Version Information

Syncthing Version: v0.14.33 (and above)
OS Version: Debian Stretch

### Platform:
```
% lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch

% cat /proc/cpuinfo
processor       : 0
vendor_id       : CentaurHauls
cpu family      : 6
model           : 9
model name      : VIA Nehemiah
stepping        : 8
cpu MHz         : 999.798
cache size      : 64 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fdiv_bug        : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 1
wp              : yes
flags           : fpu vme de pse tsc msr cx8 sep mtrr pge cmov pat mmx fxsr sse eagerfpu rng rng_en ace ace_en
bugs            :
bogomips        : 1999.59
clflush size    : 32
cache_alignment : 32
address sizes   : 32 bits physical, 32 bits virtual
power management:
```

### Syncthing 0.14.33 (Debian repo)
```
% syncthing -version
[1]    17435 illegal hardware instruction (core dumped)  syncthing -version

% gdb $(which syncthing) core
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/syncthing...(no debugging symbols found)...done.
[New LWP 17435]
Core was generated by `syncthing -version'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x0807b793 in runtime.check ()
(gdb) bt
#0  0x0807b793 in runtime.check ()
#1  0x00000000 in ?? ()
(gdb) disas
Dump of assembler code for function runtime.check:
   0x0807b760 <+0>:     mov    %gs:0x0,%ecx
   0x0807b767 <+7>:     mov    -0x4(%ecx),%ecx
   0x0807b76d <+13>:    cmp    0x8(%ecx),%esp
   0x0807b770 <+16>:    jbe    0x807bc5e <runtime.check+1278>
   0x0807b776 <+22>:    sub    $0x40,%esp
   0x0807b779 <+25>:    movl   $0x0,0x24(%esp)
   0x0807b781 <+33>:    xorps  %xmm0,%xmm0
   0x0807b784 <+36>:    movss  %xmm0,0x20(%esp)
   0x0807b78a <+42>:    movss  %xmm0,0x1c(%esp)
   0x0807b790 <+48>:    xorps  %xmm0,%xmm0
=> 0x0807b793 <+51>:    movsd  %xmm0,0x30(%esp)
   0x0807b799 <+57>:    movsd  %xmm0,0x28(%esp)
   0x0807b79f <+63>:    movl   $0x0,0x3c(%esp)
   0x0807b7a7 <+71>:    movl   $0x0,0x18(%esp)
   0x0807b7af <+79>:    movl   $0x4b57ce31,(%esp)
   0x0807b7b6 <+86>:    movl   $0xb3a,0x4(%esp)
   0x0807b7be <+94>:    movl   $0x3b9aca00,0x8(%esp)
   0x0807b7c6 <+102>:   lea    0x24(%esp),%eax
   0x0807b7ca <+106>:   mov    %eax,0xc(%esp)
   0x0807b7ce <+110>:   call   0x807c1f0 <runtime.timediv>
   0x0807b7d3 <+115>:   mov    0x10(%esp),%eax
   0x0807b7d7 <+119>:   cmp    $0x3039,%eax
   0x0807b7dc <+124>:   je     0x807b7f6 <runtime.check+150>
   0x0807b7de <+126>:   lea    0x864aee3,%eax
   0x0807b7e4 <+132>:   mov    %eax,(%esp)
   0x0807b7e7 <+135>:   movl   $0xb,0x4(%esp)
   0x0807b7ef <+143>:   call   0x806eb30 <runtime.throw>
   0x0807b7f4 <+148>:   ud2
   0x0807b7f6 <+150>:   mov    0x24(%esp),%eax
   0x0807b7fa <+154>:   cmp    $0xd431,%eax
   0x0807b7ff <+159>:   je     0x807b803 <runtime.check+163>
   0x0807b801 <+161>:   jmp    0x807b7de <runtime.check+126>
   0x0807b803 <+163>:   movl   $0x1,0x14(%esp)
   0x0807b80b <+171>:   lea    0x14(%esp),%eax
   0x0807b80f <+175>:   mov    %eax,(%esp)
   0x0807b812 <+178>:   movl   $0x1,0x4(%esp)
   0x0807b81a <+186>:   movl   $0x2,0x8(%esp)
   0x0807b822 <+194>:   call   0x80495c0 <runtime/internal/atomic.Cas>
   0x0807b827 <+199>:   movzbl 0xc(%esp),%eax
   0x0807b82c <+204>:   test   %al,%al
   0x0807b82e <+206>:   je     0x807bc46 <runtime.check+1254>
   0x0807b834 <+212>:   mov    0x14(%esp),%eax
   0x0807b838 <+216>:   cmp    $0x2,%eax
   0x0807b83b <+219>:   jne    0x807bc2e <runtime.check+1230>
   0x0807b841 <+225>:   movl   $0x4,0x14(%esp)
   0x0807b849 <+233>:   lea    0x14(%esp),%eax
```

### Downgrading to 0.14.32 and everything works once again.
```
INFO: syncthing v0.14.32 "Dysprosium Dragonfly" (go1.8.3 linux-386) deb@build.syncthing.net 2017-06-29 13:47:42 UTC [noupgrade]
```

### Tested with 0.14.34rc1, SIGILL again
```
% strace ./syncthing-linux-386-v0.14.34-rc.1/syncthing -version                                                                                                                                                         :(
execve("./syncthing-linux-386-v0.14.34-rc.1/syncthing", ["./syncthing-linux-386-v0.14.34-r"..., "-version"], [/* 34 vars */]) = 0
set_thread_area({entry_number:-1, base_addr:0x8b0ff5c, limit:1048575, seg_32bit:1, contents:0, read_exec_only:0, limit_in_pages:1, seg_not_present:0, useable:1}) = 0 (entry_number:6)
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x807b793} ---
+++ killed by SIGILL (core dumped) +++
[1]    18115 illegal hardware instruction  strace ./syncthing-linux-386-v0.14.34-rc.1/syncthing -version
```

May be related to my previous bug reports #2187 and #2562. (And yes this is the same system as https://github.com/syncthing/syncthing/issues/2562#issuecomment-162448147)

Edit: Edited to note that the 0.14.34rc1 build I tested was https://github.com/syncthing/syncthing/releases/tag/v0.14.34-rc.1

**Comment by brycied00d** [comment]
I just tried the latest Jenkins build (https://build.syncthing.net/job/syncthing/3034/) and it seems to be fixed. Excellent!

```
% ./syncthing-linux-386-v0.14.34-rc.1+1-g54155cb/syncthing -version
syncthing v0.14.34-rc.1+1-g54155cb "Dysprosium Dragonfly" (go1.8.3 linux-386) jenkins@build.syncthing.net 2017-07-27 17:31:14 UTC
```

**Comment by calmh** [comment]
Yeah, it's a lack of GO386=387 in those builds that will be fixed in the next release. Sorry about that.

**Comment by calmh** [comment]
But please double check against https://build2.syncthing.net/latest/ which is where the current builds will be coming from.

**Comment by brycied00d** [comment]
Oh sure. I didn't realize there was a new build host. Latest build from there works too
```
% curl -sSL https://build2.syncthing.net/guestAuth/app/rest/builds/id:9110/artifacts/content/syncthing-linux-386-v0.14.34-rc.1+1-g54155cb.tar.gz | tar -xzv syncthing-linux-386-v0.14.34-rc.1+1-g54155cb/syncthing
syncthing-linux-386-v0.14.34-rc.1+1-g54155cb/syncthing
% ./syncthing-linux-386-v0.14.34-rc.1+1-g54155cb/syncthing -version
syncthing v0.14.34-rc.1+1-g54155cb "Dysprosium Dragonfly" (go1.8.3 linux-386) teamcity@build.syncthing.net 2017-07-27 17:31:14 UTC
```
