### ISSUE TITLE
Regression: v0.14.37 crashes on ppc970 (PowerPC G5)

### ISSUE THREAD

**Issue by K1773R** [syncthing/syncthing#4372]
- what happened
Syncthing crashed due to an illegal instruction right at the start (no output to stdout at all)
 - what you expected to happen instead, and
Syncthing to start as before
 - any steps to reproduce the problem.
Run Syncthing version v0.14.37 on any PPC G5 Hardware (ppc 970 CPU)

### Version Information

Syncthing Version: v0.14.37
OS Version: Linux ppc64
Browser Version: not applicable

**Comment by calmh** [comment]
How about the actual crash output?

**Comment by K1773R** [comment]
```
$ gdb64 ./syncthing 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "powerpc64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./syncthing...(no debugging symbols found)...done.
(gdb) layout asm
   ┌───────────────────────────────────────────────────────────────────────────┐
   │0x4ae00 <runtime.check+480>     cmpd    r3,r4                              │
   │0x4ae04 <runtime.check+484>     bne     0x4b084 <runtime.check+1124>       │
   │0x4ae08 <runtime.check+488>     stw     r0,72(r1)                          │
   │0x4ae0c <runtime.check+492>     li      r3,1                               │
   │0x4ae10 <runtime.check+496>     stb     r3,72(r1)                          │
   │0x4ae14 <runtime.check+500>     stb     r3,73(r1)                          │
   │0x4ae18 <runtime.check+504>     stb     r3,74(r1)                          │
   │0x4ae1c <runtime.check+508>     stb     r3,75(r1)                          │
   │0x4ae20 <runtime.check+512>     addi    r4,r1,73                           │
   │0x4ae24 <runtime.check+516>     li      r5,-16                             │
   │0x4ae28 <runtime.check+520>     hwsync                                     │
  >│0x4ae2c <runtime.check+524>     lbarx   r31,0,r4                           │
   │0x4ae30 <runtime.check+528>     or      r31,r31,r5                         │
   │0x4ae34 <runtime.check+532>     stbcx.  r31,0,r4                           │
   │0x4ae38 <runtime.check+536>     bne     0x4ae2c <runtime.check+524>        │
   │0x4ae3c <runtime.check+540>     isync                                      │
   │0x4ae40 <runtime.check+544>     lbz     r5,72(r1)                          │
   │0x4ae44 <runtime.check+548>     cmpwi   r5,1                               │
   │0x4ae48 <runtime.check+552>     bne     0x4b068 <runtime.check+1096>       │
   │0x4ae4c <runtime.check+556>     lbz     r5,73(r1)                          │
   │0x4ae50 <runtime.check+560>     cmpwi   r5,241                             │
   │0x4ae54 <runtime.check+564>     bne     0x4b068 <runtime.check+1096>       │
   │0x4ae58 <runtime.check+568>     lbz     r5,74(r1)                          │
   │0x4ae5c <runtime.check+572>     cmpwi   r5,1                               │
   │0x4ae60 <runtime.check+576>     bne     0x4b068 <runtime.check+1096>       │
   └───────────────────────────────────────────────────────────────────────────┘
native process 6057 In: runtime.check                         L??   PC: 0x4ae2c 
(gdb) r
Starting program: /tmp/foo/syncthing

Program received signal SIGILL, Illegal instruction.
0x000000000004ae2c in runtime.check ()
(gdb) bt full
#0  0x000000000004ae2c in runtime.check ()
No symbol table info available.
#1  0x387f02c8f861fff9 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x4bfe28c14bfd134d
(gdb) 
```

**Comment by calmh** [comment]
As of Go 1.9 the compiled binaries require the POWER8 instruction set. I’m guessing the old G5 predates that. You will need to compile a Syncthing using an older Go compiler I think.

**Comment by calmh** [comment]
I’m sorry about this regression but it’s not something we will remedy in our binary releases.
