### ISSUE TITLE
panic in dialer

### ISSUE THREAD

**Issue by agriffis** [syncthing/syncthing#4379]
I just updated to 0.14.37 on Fedora 27 and getting the following stack trace in journalctl.

I'm new at Syncthing and Go so please let me know if there's more info you need.

```
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: [SBGGZ] INFO: connections.Service: Failed service '(connections.serviceFunc)(0x559acbf27990)' (5.999494 failures of 5.000000), restarting: false, error: reflect: call of reflect.Value.Int on zero Value, stacktrace: goroutine 1316 [running]:
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: github.com/thejerf/suture.(*Supervisor).runService.func1.1(0xc420114540, 0x559a00000000)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /usr/share/gocode/src/github.com/thejerf/suture/supervisor.go:448 +0xbe
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: panic(0x559acc6f9080, 0xc421503240)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /usr/lib/golang/src/runtime/panic.go:491 +0x287
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: reflect.Value.Int(0x0, 0x0, 0x0, 0x559acc031190)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /usr/lib/golang/src/reflect/value.go:908 +0x143
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: golang.org/x/net/internal/netreflect.socketOf(0x559accac4ea0, 0xc420ed0198, 0x9, 0x1, 0x0)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /usr/share/gocode/src/golang.org/x/net/internal/netreflect/socket_posix.go:26 +0x198
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: golang.org/x/net/internal/netreflect.SocketOf(0x559accac4ea0, 0xc420ed0198, 0xc42001e600, 0xc42001e670, 0xc42001e600)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /usr/share/gocode/src/golang.org/x/net/internal/netreflect/socket.go:23 +0x67
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: golang.org/x/net/ipv4.(*genericOpt).SetTOS(0xc4218d4d88, 0x0, 0x559acba690c8, 0x559accabdec8)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /usr/share/gocode/src/golang.org/x/net/ipv4/genericopt_posix.go:33 +0x53
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: github.com/syncthing/syncthing/lib/dialer.SetTrafficClass(0x559accac4ea0, 0xc420ed0198, 0x0, 0x1, 0xc4201f43e0)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/dialer/public.go:85 +0x152
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: github.com/syncthing/syncthing/lib/connections.(*tcpDialer).Dial(0xc421c76300, 0xf4eeb087eb28a4e0, 0x9cfd4652342ef076, 0xa78231fbdc4ad8d, 0xf7315d3e727f30ba, 0xc421c3ea80, 0x559accb138c0, 0x3, 0x1, 0xc4200896e0, ...)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/connections/tcp_dial.go:45 +0x2e3
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: github.com/syncthing/syncthing/lib/connections.(*Service).connect(0xc421a7e1e0)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/connections/service.go:401 +0x120f
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: github.com/syncthing/syncthing/lib/connections.(*Service).(github.com/syncthing/syncthing/lib/connections.connect)-fm()
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/connections/service.go:144 +0x2c
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: github.com/syncthing/syncthing/lib/connections.serviceFunc.Serve(0xc4201f42c0)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/connections/structs.go:133 +0x27
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: github.com/thejerf/suture.(*Supervisor).runService.func1(0xc420114540, 0x0, 0x559accabe260, 0xc4201f42c0)
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:         /usr/share/gocode/src/github.com/thejerf/suture/supervisor.go:454 +0x65
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]: created by github.com/thejerf/suture.(*Supervisor).runService
Sep 18 23:41:12 jasperodus.jupiter syncthing[904]:        /usr/share/gocode/src/github.com/thejerf/suture/supervisor.go:444 +0x5d
```

### Version Information

Syncthing Version: v0.14.37
OS Version: Fedora 27 (alpha-ish)

**Comment by calmh** [comment]
Is this a once off or regular, and what's the full output of `syncthing -version`?

**Comment by agriffis** [comment]
It's happening continuously and preventing my system from syncing since I updated.

```
$ syncthing -version
syncthing v0.14.37 "Dysprosium Dragonfly" (go1.9beta2 linux-amd64) mockbuild@fedora-koji 2017-09-15 14:38:21 UTC [noupgrade]
```

How do I collect the logs you'd like to see?

**Comment by calmh** [comment]
It's the same log you pasted, just slightly higher up. Does this happen with our binary release from https://github.com/syncthing/syncthing/releases/tag/v0.14.37 as well?

**Comment by agriffis** [comment]
I just started it manually with `-logfile syncthing.log` and here's the result:

```
[SBGGZ] INFO: syncthing v0.14.37 "Dysprosium Dragonfly" (go1.9beta2 linux-amd64) mockbuild@fedora-koji 2017-09-15 14:38:21 UTC [noupgrade]
[SBGGZ] INFO: My ID: SBGGZNR-NU6STFN-T3V4R65-F4H6OBO-KVCU5JN-45WEJXU-MOPHBLB-RM7ORQU
[SBGGZ] INFO: Single thread SHA256 performance is 284 MB/s using minio/sha256-simd (282 MB/s using crypto/sha256).
[SBGGZ] INFO: Hashing performance with weak hash is 235.02 MB/s
[SBGGZ] INFO: Hashing performance without weak hash is 275.59 MB/s
[SBGGZ] INFO: Weak hash enabled, as it has an acceptable performance impact.
[SBGGZ] INFO: Ready to synchronize "Default Folder" (default) (readwrite)
[SBGGZ] INFO: Send rate is unlimited, receive rate is unlimited
[SBGGZ] INFO: Rate limits do not apply to LAN connections
[SBGGZ] INFO: TCP listener (172.20.0.11:22000) starting
[SBGGZ] INFO: connections.Service: Failed service '(connections.serviceFunc)(0x5560a45ac990)' (1.000000 failures of 5.000000), restarting: true, error: reflect: call of reflect.Value.Int on zero Value, stacktrace: goroutine 12 [running]:
github.com/thejerf/suture.(*Supervisor).runService.func1.1(0xc420122460, 0x0)
        /usr/share/gocode/src/github.com/thejerf/suture/supervisor.go:448 +0xbe
panic(0x5560a4d7e080, 0xc42008a1a0)
        /usr/lib/golang/src/runtime/panic.go:491 +0x287
reflect.Value.Int(0x0, 0x0, 0x0, 0x5560a46b6190)
        /usr/lib/golang/src/reflect/value.go:908 +0x143
golang.org/x/net/internal/netreflect.socketOf(0x5560a5149ea0, 0xc42000e008, 0x9, 0x1, 0x0)
        /usr/share/gocode/src/golang.org/x/net/internal/netreflect/socket_posix.go:26 +0x198
golang.org/x/net/internal/netreflect.SocketOf(0x5560a5149ea0, 0xc42000e008, 0xc42002c600, 0xc42002c670, 0xc42002c600)
        /usr/share/gocode/src/golang.org/x/net/internal/netreflect/socket.go:23 +0x67
golang.org/x/net/ipv4.(*genericOpt).SetTOS(0xc4216d2d88, 0x0, 0x5560a40ee0c8, 0x5560a5142ec8)
        /usr/share/gocode/src/golang.org/x/net/ipv4/genericopt_posix.go:33 +0x53
github.com/syncthing/syncthing/lib/dialer.SetTrafficClass(0x5560a5149ea0, 0xc42000e008, 0x0, 0x1, 0xc42019d0f0)
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/dialer/public.go:85 +0x152
github.com/syncthing/syncthing/lib/connections.(*tcpDialer).Dial(0xc42004a140, 0xf4eeb087eb28a4e0, 0x9cfd4652342ef076, 0xa78231fbdc4ad8d, 0xf7315d3e727f30ba, 0xc420342200, 0x5560a51988c0, 0x3, 0x1, 0xc4201a1200, ...)
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/connections/tcp_dial.go:45 +0x2e3
github.com/syncthing/syncthing/lib/connections.(*Service).connect(0xc421861d10)
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/connections/service.go:401 +0x120f
github.com/syncthing/syncthing/lib/connections.(*Service).(github.com/syncthing/syncthing/lib/connections.connect)-fm()
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/connections/service.go:144 +0x2c
github.com/syncthing/syncthing/lib/connections.serviceFunc.Serve(0xc4200816b0)
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/connections/structs.go:133 +0x27
github.com/thejerf/suture.(*Supervisor).runService.func1(0xc420122460, 0xc400000000, 0x5560a5143260, 0xc4200816b0)
        /usr/share/gocode/src/github.com/thejerf/suture/supervisor.go:454 +0x65
created by github.com/thejerf/suture.(*Supervisor).runService
        /usr/share/gocode/src/github.com/thejerf/suture/supervisor.go:444 +0x5d
```

I'll try the binary release, hang on

**Comment by calmh** [comment]
If that gives the same issue, one run with `STTRACE=connections syncthing -logfile=...etc` would be helpful too.

**Comment by agriffis** [comment]
It doesn't happen with the binary release. Here's the log:

```
[SBGGZ] INFO: syncthing v0.14.37 "Dysprosium Dragonfly" (go1.9 linux-amd64) teamcity@build.syncthing.net 2017-08-24 04:26:12 UTC
[SBGGZ] INFO: My ID: SBGGZNR-NU6STFN-T3V4R65-F4H6OBO-KVCU5JN-45WEJXU-MOPHBLB-RM7ORQU
[SBGGZ] INFO: Single thread SHA256 performance is 283 MB/s using minio/sha256-simd (281 MB/s using crypto/sha256).
[SBGGZ] INFO: Hashing performance with weak hash is 231.09 MB/s
[SBGGZ] INFO: Hashing performance without weak hash is 272.04 MB/s
[SBGGZ] INFO: Weak hash enabled, as it has an acceptable performance impact.
[SBGGZ] INFO: Ready to synchronize "Default Folder" (default) (readwrite)
[SBGGZ] INFO: Send rate is unlimited, receive rate is unlimited
[SBGGZ] INFO: Rate limits do not apply to LAN connections
[SBGGZ] INFO: TCP listener (172.20.0.11:22000) starting
[SBGGZ] INFO: Device PGBNL6H-SHFG3HB-43HJDEK-6SJERY7-RD25VD7-QEBN5LA-5XUL652-U7RNUQG is "aron@crumb" at [dynamic]
[SBGGZ] INFO: Device SBGGZNR-NU6STFN-T3V4R65-F4H6OBO-KVCU5JN-45WEJXU-MOPHBLB-RM7ORQU is "aron@jasperodus" at [dynamic]
[SBGGZ] INFO: Device 4CSCR24-HWDXPIB-5XQFY2F-ERX5TSK-G23RF5D-4RXQCVC-2GB7XEP-S5GH3QQ is "aron@gargan" at [tcp://172.20.0.244:22000]
[SBGGZ] INFO: GUI and API listening on 127.0.0.1:8384
[SBGGZ] INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[SBGGZ] INFO: Starting usage reporting
[SBGGZ] INFO: Established secure connection to 4CSCR24-HWDXPIB-5XQFY2F-ERX5TSK-G23RF5D-4RXQCVC-2GB7XEP-S5GH3QQ at 172.20.0.11:43614-172.20.0.244:22000 (tcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[SBGGZ] INFO: Device 4CSCR24-HWDXPIB-5XQFY2F-ERX5TSK-G23RF5D-4RXQCVC-2GB7XEP-S5GH3QQ client is "syncthing v0.14.36" named "aron@gargan"
[SBGGZ] INFO: Automatic upgrade (current "v0.14.37" < latest "v0.14.38-rc.1")
[SBGGZ] INFO: Completed initial scan (rw) of "Default Folder" (default)
[SBGGZ] WARNING: Automatically upgraded to version "v0.14.38-rc.1". Restarting in 1 minute.
```

**Comment by calmh** [comment]
Then I'm afraid this is something related to the packages or build process used by fedora and it's hard for us to debug further. Luckily you have a workaround, now.

**Comment by agriffis** [comment]
Thanks @calmh. Reported at https://bugzilla.redhat.com/show_bug.cgi?id=1493095

**Comment by calmh** [comment]
FWIW I suspect the issue is that they're using an old version of the x/net/{ipv4,ipv6} packages that isn't compatible with Go 1.9. (And, possibly, using a beta compiler that is old at this point.)

**Comment by agriffis** [comment]
FYI fixed in Fedora update this morning:

```
$ rpm -q --changelog syncthing
* Mon Sep 18 2017 Fabio Valentini - 0.14.37-2
- Rebuild for updated dependencies, fixing crashes.
```
