### ISSUE TITLE
KCP gets confused when restarting a device

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4446]
I think we're back to (or just still at) some issue with connections not being established after being broken. For example, when I restart Syncthing on my laptop (`SYNO4VL`) connected to my server (`ITZRNXE`):

Laptop logs:

```
[SYNO4] 19:08:27 INFO: Started filesystem watcher for folder "Transfer" (4vcqq-sciqk)
[SYNO4] 19:08:27 INFO: Started filesystem watcher for folder "foto/2017" (2fyjq-jrfpr)
[SYNO4] 19:08:27 INFO: Started filesystem watcher for folder "Lightroom" (lightroom)
[SYNO4] 19:08:27 INFO: Started filesystem watcher for folder documents
[SYNO4] 19:08:27 INFO: Completed initial scan of readwrite folder "Transfer" (4vcqq-sciqk)
[SYNO4] 19:08:27 INFO: Completed initial scan of readonly folder "Lightroom" (lightroom)
[SYNO4] 19:08:27 INFO: Completed initial scan of readonly folder documents
[SYNO4] 19:08:28 INFO: Completed initial scan of readonly folder "foto/2017" (2fyjq-jrfpr)
[SYNO4] 19:08:30 INFO: Device ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM is "pseudo.nym.se" at [kcp://pseudo.int.nym.se:12345 dynamic]
[SYNO4] 19:08:30 INFO: Device SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC is "syno.nym.se" at [dynamic]
[SYNO4] 19:08:30 INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
[SYNO4] 19:08:30 INFO: GUI and API listening on 127.0.0.1:8385
[SYNO4] 19:08:30 INFO: Access the GUI via the following URL: http://127.0.0.1:8385/
[SYNO4] 19:08:30 INFO: Established secure connection to ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM at [::]:22020-172.16.32.11:12345 (kcp-client) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
[SYNO4] 19:08:30 INFO: Device ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM client is "syncthing v0.14.39" named "pseudo.nym.se"
[SYNO4] 19:08:30 INFO: Connection to ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM closed: reading length: EOF
[SYNO4] 19:08:36 INFO: kcp://0.0.0.0:22020 detected NAT type: Symetric NAT
[SYNO4] 19:08:36 INFO: kcp://0.0.0.0:22020 resolved external address kcp://94.255.169.149:31239 (via stun.voipstunt.com:3478)
[SYNO4] 19:08:38 INFO: Detected 0 NAT devices
[SYNO4] 19:08:40 INFO: Established secure connection to ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM at [::]:22020-172.16.32.11:12345 (kcp-client) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
[SYNO4] 19:08:40 INFO: Device ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM client is "syncthing v0.14.39" named "pseudo.nym.se"
[SYNO4] 19:08:40 INFO: Connection to ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM closed: reading length: EOF
[SYNO4] 19:08:50 INFO: Established secure connection to ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM at [::]:22020-172.16.32.11:12345 (kcp-client) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
[SYNO4] 19:08:50 INFO: Device ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM client is "syncthing v0.14.39" named "pseudo.nym.se"
[SYNO4] 19:08:50 INFO: Connection to ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM closed: reading length: EOF
```

server side logs:

```
root@pseudo: # grep SYNO4VL /var/log/messages | tail -n 20
Oct 21 18:21:50 pseudo syncthing: [ITZRN] INFO: Established secure connection to SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC at [::]:12345-172.16.33.59:22020 (kcp-server) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
Oct 21 18:21:50 pseudo syncthing: [ITZRN] INFO: Device SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC client is "syncthing v0.14.39" named "syno.nym.se"
Oct 21 18:22:10 pseudo syncthing: [ITZRN] INFO: Connected to already connected device (SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC)
Oct 21 18:23:49 pseudo syncthing: [ITZRN] INFO: Connection to SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC closed: reading length: broken pipe
Oct 21 18:29:19 pseudo syncthing: [ITZRN] INFO: Established secure connection to SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC at [::]:12345-172.16.33.59:22020 (kcp-server) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
Oct 21 18:29:19 pseudo syncthing: [ITZRN] INFO: Device SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC client is "syncthing v0.14.39" named "syno.nym.se"
Oct 21 18:29:39 pseudo syncthing: [ITZRN] INFO: Connected to already connected device (SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC)
Oct 21 18:57:24 pseudo syncthing: [ITZRN] INFO: Connected to already connected device (SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC)
Oct 21 18:57:35 pseudo syncthing: [ITZRN] INFO: Connected to already connected device (SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC)
Oct 21 18:57:48 pseudo syncthing: [ITZRN] INFO: Connection to SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC closed: reading length: broken pipe
Oct 21 18:58:45 pseudo syncthing: [ITZRN] INFO: Established secure connection to SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC at [::]:12345-172.16.33.59:22020 (kcp-server) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
Oct 21 18:58:45 pseudo syncthing: [ITZRN] INFO: Device SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC client is "syncthing v0.14.39" named "syno.nym.se"
Oct 21 18:59:05 pseudo syncthing: [ITZRN] INFO: Connected to already connected device (SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC)
Oct 21 18:59:15 pseudo syncthing: [ITZRN] INFO: Connected to already connected device (SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC)
Oct 21 18:59:45 pseudo syncthing: [ITZRN] INFO: Connection to SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC closed: reading length: broken pipe
Oct 21 19:06:36 pseudo syncthing: [ITZRN] INFO: Established secure connection to SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC at [::]:12345-[2001:7a0:8003:33:11c4:c2d:cdd1:3107]:22020 (kcp-server) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
Oct 21 19:06:36 pseudo syncthing: [ITZRN] INFO: Device SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC client is "syncthing v0.14.39+23-g20fac4bb" named "syno.nym.se"
Oct 21 19:06:47 pseudo syncthing: [ITZRN] INFO: Connected to already connected device (SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC)
Oct 21 19:08:30 pseudo syncthing: [ITZRN] INFO: Connected to already connected device (SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC)
Oct 21 19:09:06 pseudo syncthing: [ITZRN] INFO: Connection to SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC closed: reading length: broken pipe
```

It's now 19:15 and no new reconnections seem to be happening, unclear why.

**Comment by AudriusButkevicius** [comment]
:(

**Comment by calmh** [comment]
Here's a -QUIT trace after five minutes of no connection activity, on the laptop side: https://kastelo.net/r/272w.txt

Nothing totally obviously stuck, a few possibilities that *might* be suspicious or normal depending:

```
goroutine 117 [select, 5 minutes]:
github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter.(*FilteredConn).ReadFrom(0xc420b56080, 0xc420a72600, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter/conn.go:73 +0x2a4
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).receiver(0xc420c28080, 0xc421874420)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:781 +0xa7
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).monitor
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:700 +0x82

goroutine 115 [select, 5 minutes]:
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).monitor(0xc420c28080)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:702 +0x225
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.ServeConn
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:918 +0x21d

```

(just looking for stuff stuck on selects or iowait for minutes, but that might not be the case for the offending goroutine anyway)

**Comment by AudriusButkevicius** [comment]
I don't think it's stuck.
The connections get established, so it's making progress, yet I suspect there is some out of band packet business, or routing issues.

This is incredibly hard to debug as it's not obvious at which layer this is happening.
I tried debugging at the KCP layer, but given it opens tons of these connections which put messages on the output buffer that stay around for ages, there is just flood of dirt.

**Comment by calmh** [comment]
I think it's stuck somehow, as in the end both sides just stop logging info, indicating they are probably in the middle of a connection attempt that isn't making progress. No routing issues here, these are two boxes on the same LAN right next to each other, it just happens when Syncthing is restarted. Maybe it's just a timeout that hasn't been reached yet, but the timeout should ideally not be significantly longer than our ping timeout?

**Comment by AudriusButkevicius** [comment]
When I mean routing, I mean my routing thing for splitting stun versus KCP traffic.
From what you've posted, it seems that:


The main routine tracking packets has had some action recently:
```
goroutine 114 [IO wait]:
internal/poll.runtime_pollWait(0x5880780, 0x72, 0x0)
	/usr/local/go1.9/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420c28018, 0x72, 0x0, 0x0, 0x0)
	/usr/local/go1.9/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420c28018, 0xc420a73200, 0x5dc, 0x5dc)
	/usr/local/go1.9/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadFrom(0xc420c28000, 0xc420a73200, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go1.9/src/internal/poll/fd_unix.go:169 +0x19a
net.(*netFD).readFrom(0xc420c28000, 0xc420a73200, 0x5dc, 0x5dc, 0xc421c51f48, 0xc4202be780, 0xc420103160, 0xc421c51e28, 0x40062e8)
	/usr/local/go1.9/src/net/fd_unix.go:208 +0x5e
net.(*UDPConn).readFrom(0xc420d62010, 0xc420a73200, 0x5dc, 0x5dc, 0xc421c51e60, 0x4066a40, 0x4d23cf0, 0xc421a99080)
	/usr/local/go1.9/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc420d62010, 0xc420a73200, 0x5dc, 0x5dc, 0x4cce200, 0xc4218f8b40, 0xc4218f8b01, 0x0, 0x0)
	/usr/local/go1.9/src/net/udpsock.go:118 +0x72
github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter.(*PacketFilter).loop(0xc420b56040)
	src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter/filter.go:98 +0x1b0
created by github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter.(*PacketFilter).Start
	src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter/filter.go:90 +0x3f
```

The connection on the KCP listener is bored:
```
goroutine 117 [select, 5 minutes]:
github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter.(*FilteredConn).ReadFrom(0xc420b56080, 0xc420a72600, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter/conn.go:73 +0x2a4
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).receiver(0xc420c28080, 0xc421874420)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:781 +0xa7
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).monitor
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:700 +0x82
```

The Dial side connection has seen some action:
```
goroutine 596 [select]:
github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter.(*FilteredConn).ReadFrom(0xc420ae2440, 0xc42169e600, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter/conn.go:73 +0x2a4
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*UDPSession).receiver(0xc420c26120, 0xc4201b13e0)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:614 +0xa7
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*UDPSession).readLoop
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:632 +0x82
```

Given laptop is kcp-client, it all makes sense.
Anyways, I'll poke at it some more.

**Comment by AudriusButkevicius** [comment]
I did found a few bugs in my changes to KCP that I fixed after I declared this as being fixed todo with session caching, so perhaps fixing those bugs brought back this pain.

**Comment by calmh** [comment]
It recovers after ten minutes. I think we are just looking at the usual KCP timeout and I overreacted.

**Comment by AudriusButkevicius** [comment]
So I've managed to repro, but it's not as easy as it used to be to make it happen.
Perhaps I've just didn't manage to repro as I tried last time.

**Comment by AudriusButkevicius** [comment]
Relevant logs.

From not restarted device:
```
[MRIW7] 2017/10/21 22:08:52.524478 service.go:282: INFO: Established secure connection to I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU at 127.0.0.1:22002-127.0.0.1:22001 (kcp-client) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
[MRIW7] 2017/10/21 22:08:52.524478 model.go:1487: INFO: Device I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s1"
[MRIW7] 2017/10/21 22:09:43.366681 model.go:1212: INFO: Connection to I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU closed: reading length: broken pipe
[MRIW7] 2017/10/21 22:19:53.032030 service.go:282: INFO: Established secure connection to I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU at 127.0.0.1:22002-127.0.0.1:22001 (kcp-server) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[MRIW7] 2017/10/21 22:19:53.032030 model.go:1487: INFO: Device I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s1"
[MRIW7] 2017/10/21 22:20:15.396677 service.go:245: INFO: Connected to already connected device (I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU)
[MRIW7] 2017/10/21 22:20:45.471295 service.go:245: INFO: Connected to already connected device (I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU)
[MRIW7] 2017/10/21 22:20:52.976045 model.go:1212: INFO: Connection to I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU closed: reading length: broken pipe
[MRIW7] 2017/10/21 22:21:25.423656 service.go:282: INFO: Established secure connection to I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU at 127.0.0.1:22002-127.0.0.1:22001 (kcp-client) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
[MRIW7] 2017/10/21 22:21:25.423656 model.go:1487: INFO: Device I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s1"
[MRIW7] 2017/10/21 22:22:40.656279 service.go:245: INFO: Connected to already connected device (I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU)
[MRIW7] 2017/10/21 22:23:10.658664 service.go:245: INFO: Connected to already connected device (I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU)
[MRIW7] 2017/10/21 22:23:16.619282 model.go:1212: INFO: Connection to I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU closed: reading length: broken pipe
```

From short lived device:
```
[I6KAH] 2017/10/21 22:08:52.524478 service.go:282: INFO: Established secure connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC at 127.0.0.1:22001-127.0.0.1:22002 (kcp-server) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
[I6KAH] 2017/10/21 22:08:52.524478 model.go:1487: INFO: Device MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s2"

<restart>

[I6KAH] 2017/10/21 22:19:53.032030 service.go:282: INFO: Established secure connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC at 127.0.0.1:22001-127.0.0.1:22002 (kcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[I6KAH] 2017/10/21 22:19:53.032030 model.go:1487: INFO: Device MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s2"

<restart>

[I6KAH] 2017/10/21 22:20:15.396177 service.go:282: INFO: Established secure connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC at 127.0.0.1:22001-127.0.0.1:22002 (kcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[I6KAH] 2017/10/21 22:20:15.396177 model.go:1487: INFO: Device MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s2"
[I6KAH] 2017/10/21 22:20:15.410178 model.go:1212: INFO: Connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC closed: reading length: EOF
[I6KAH] 2017/10/21 22:20:45.470794 service.go:282: INFO: Established secure connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC at 127.0.0.1:22001-127.0.0.1:22002 (kcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[I6KAH] 2017/10/21 22:20:45.471295 model.go:1487: INFO: Device MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s2"
[I6KAH] 2017/10/21 22:20:45.471295 model.go:1212: INFO: Connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC closed: reading length: EOF
[I6KAH] 2017/10/21 22:21:25.423656 service.go:282: INFO: Established secure connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC at 127.0.0.1:22001-127.0.0.1:22002 (kcp-server) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
[I6KAH] 2017/10/21 22:21:25.423656 model.go:1487: INFO: Device MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s2"


<restart>

[I6KAH] 2017/10/21 22:22:40.655779 service.go:282: INFO: Established secure connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC at 127.0.0.1:22001-127.0.0.1:22002 (kcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[I6KAH] 2017/10/21 22:22:40.656279 model.go:1487: INFO: Device MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s2"
[I6KAH] 2017/10/21 22:22:40.657278 model.go:1212: INFO: Connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC closed: reading length: EOF
[I6KAH] 2017/10/21 22:23:10.656665 service.go:282: INFO: Established secure connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC at 127.0.0.1:22001-127.0.0.1:22002 (kcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[I6KAH] 2017/10/21 22:23:10.657165 model.go:1487: INFO: Device MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC client is "syncthing v0.14.18+311-g488ab29-fsyncsilent" named "s2"
[I6KAH] 2017/10/21 22:23:10.659665 model.go:1212: INFO: Connection to MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC closed: reading length: EOF
```

**Comment by AudriusButkevicius** [comment]
Added some HTTP endpoints for debugging.
It seems that when this happens connections that KCP claims "established" start accumulating on the listener. smux fails to handshake and supposedly close the connection, but it doesn't get cleaned up.

Anyways, the important bit is that I am figuring out how to debug this without pure logs that just cause havoc.

**Comment by AudriusButkevicius** [comment]
It seems that somehow our dialed connections, after us closing it due to failure to exchange smux handshakes get reparented and start looking like the other side dialed us with the same ID.

**Comment by calmh** [comment]
That means nothing to me but I'm happy you seem to understand it.

**Comment by AudriusButkevicius** [comment]
Let me know if you still see issues with blacklisting.

**Comment by calmh** [comment]
I think we're done here
