### ISSUE TITLE
Folder no longer stopped on error

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4464]
After #4455 my nonexistent folders are no longer stopped on error. For example I have a Folder foto/2017` on `/Volumes/samsung-1tb` which is an external SSD that is not present when I start Syncthing:

```
jb@unu:~ $ syncthing
[monitor] 10:52:59 INFO: Starting syncthing
[SYNO4] 10:52:59 INFO: syncthing v0.14.40-rc.1 "Dysprosium Dragonfly" (go1.9 darwin-amd64) jb@unu.kastelo.net 2017-10-24 07:58:55 UTC
[SYNO4] 10:52:59 INFO: My ID: SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC
[SYNO4] 10:53:00 INFO: Single thread SHA256 performance is 362 MB/s using minio/sha256-simd (359 MB/s using crypto/sha256).
[SYNO4] 10:53:01 INFO: Hashing performance with weak hash is 300.30 MB/s
[SYNO4] 10:53:01 INFO: Hashing performance without weak hash is 348.51 MB/s
[SYNO4] 10:53:01 INFO: Weak hash enabled, as it has an acceptable performance impact.
[SYNO4] 10:53:02 INFO: Starting deadlock detector with 20m0s timeout
[SYNO4] 10:53:02 INFO: Ready to synchronize documents (readonly)
[SYNO4] 10:53:03 INFO: Ready to synchronize "Lightroom" (lightroom) (readonly)
[SYNO4] 10:53:04 INFO: Ready to synchronize "foto/2017" (2fyjq-jrfpr) (readonly)
[SYNO4] 10:53:04 INFO: Ready to synchronize "Transfer" (4vcqq-sciqk) (readwrite)
[SYNO4] 10:53:04 INFO: Send rate is unlimited, receive rate is unlimited
[SYNO4] 10:53:04 INFO: Rate limits do not apply to LAN connections
[SYNO4] 10:53:04 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[SYNO4] 10:53:04 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[SYNO4] 10:53:04 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[SYNO4] 10:53:04 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[SYNO4] 10:53:04 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[SYNO4] 10:53:04 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[SYNO4] 10:53:04 INFO: Started filesystem watcher for folder "Transfer" (4vcqq-sciqk)
[SYNO4] 10:53:04 WARNING: Failed to start filesystem watcher for folder "foto/2017" (2fyjq-jrfpr): lstat /Volumes/samsung-1tb: no such file or directory
[SYNO4] 10:53:04 WARNING: Error on folder "foto/2017" (2fyjq-jrfpr): folder path missing
[SYNO4] 10:53:04 WARNING: Failed to start filesystem watcher for folder "foto/2017" (2fyjq-jrfpr): lstat /Volumes/samsung-1tb: no such file or directory
[SYNO4] 10:53:04 INFO: TCP listener ([::]:22000) starting
[SYNO4] 10:53:04 INFO: Started filesystem watcher for folder documents
[SYNO4] 10:53:04 INFO: KCP listener ([::]:22020) starting
[SYNO4] 10:53:04 INFO: Started filesystem watcher for folder "Lightroom" (lightroom)
[SYNO4] 10:53:04 INFO: Completed initial scan of readwrite folder "Transfer" (4vcqq-sciqk)
[SYNO4] 10:53:04 INFO: Device ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM is "pseudo.nym.se" at [dynamic]
[SYNO4] 10:53:04 INFO: Device SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC is "syno.nym.se" at [dynamic]
[SYNO4] 10:53:04 INFO: Anonymous usage reporting is always enabled for candidate releases.
[SYNO4] 10:53:04 INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
[SYNO4] 10:53:04 INFO: GUI and API listening on 127.0.0.1:8385
[SYNO4] 10:53:04 INFO: Access the GUI via the following URL: http://127.0.0.1:8385/
[SYNO4] 10:53:05 INFO: Completed initial scan of readonly folder documents
[SYNO4] 10:53:07 INFO: Completed initial scan of readonly folder "Lightroom" (lightroom)
[SYNO4] 10:53:14 INFO: kcp://0.0.0.0:22020 detected NAT type: Symetric NAT
[SYNO4] 10:53:14 INFO: kcp://0.0.0.0:22020 resolved external address kcp://94.255.169.149:26240 (via stun.voip.aebc.com:3478)
[SYNO4] 10:53:28 INFO: Established secure connection to ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM at [::]:22020-[2001:7a0:8003:32::11]:22020 (kcp-client) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
[SYNO4] 10:53:28 INFO: Device ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM client is "syncthing v0.14.40-rc.2" named "pseudo.nym.se"
[SYNO4] 10:53:29 INFO: Established secure connection to ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM at 172.16.33.87:60344-94.255.169.149:22000 (tcp-client) (TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305)
[SYNO4] 10:53:29 INFO: Replacing old connection [::]:22020-[2001:7a0:8003:32::11]:22020/kcp-client with 172.16.33.87:60344-94.255.169.149:22000/tcp-client for ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM
[SYNO4] 10:53:29 INFO: Connection to ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM closed: reading length: broken pipe
[SYNO4] 10:53:29 INFO: Device ITZRNXE-YNROGBZ-HXTH5P7-VK5NYE5-QHRQGE2-7JQ6VNJ-KZUEDIU-5PPR5AM client is "syncthing v0.14.40-rc.2" named "pseudo.nym.se"
```

Folder is green in the UI:

![screen shot 2017-10-26 at 10 55 55](https://user-images.githubusercontent.com/125426/32043880-42d5fbfc-ba3c-11e7-8f0a-fd6bc75d40dc.png)

On the plus side, my files haven't been deleted! :) (i.e., it still aborts the scan in time)

This should be fixed for 0.14.40.

**Comment by imsodin** [comment]
I just tried to reproduce and I can't. I tried both removing the entire path or its content (including .stfolder) and restarting Syncthing with folder being "healthy" or already stopped before. Also your log looks perfectly fine (except for the repeat fs watcher warning). Any ideas what else I could try to reproduce this?

**Comment by AudriusButkevicius** [comment]
Perhaps just a UI glitch?

**Comment by imsodin** [comment]
It isn't, I missed one little (well not so little) factor: Calmh's folder is send-only/read-only. Now I can repro and I am really hoping the cause is going to be something funny (and in my face please).

**Comment by imsodin** [comment]
And it is:

```
[CBBHG] 2017/10/26 11:48:08.613260 rofolder.go:50: DEBUG: sendOnlyFolder/dyk5u-gr9e3@0xc4201d92c0 Scanning subdirectories
[CBBHG] 2017/10/26 11:48:08.613295 folder.go:174: WARNING: Error on folder "missing" (dyk5u-gr9e3): folder path missing
[CBBHG] 2017/10/26 11:48:08.613329 asm_amd64.s:509: DEBUG: sendOnlyFolder/dyk5u-gr9e3@0xc4201d92c0 exiting
[CBBHG] 2017/10/26 11:48:08.613433 model.go:125: DEBUG: model: Failed service 'sendOnlyFolder/dyk5u-gr9e3@0xc4201d92c0' (1.000000 failures of 5.000000), restarting: true, error: runtime error: invalid memory address or nil pointer dereference, stacktrace: goroutine 61 [running]:
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1.1(0xc4202421c0, 0x7)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:448 +0xbc
panic(0xab6540, 0x1110a20)
	/media/ext4_data/Linux/source/go/src/runtime/panic.go:491 +0x283
github.com/syncthing/syncthing/lib/model.(*folder).setError(0xc4201d92c0, 0x10b6880, 0xc420042ee0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/folder.go:184 +0x232
github.com/syncthing/syncthing/lib/model.(*folder).CheckHealth(0xc4201d92c0, 0x0, 0x0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/folder.go:82 +0x4d
github.com/syncthing/syncthing/lib/model.(*Model).internalScanFolderSubdirs(0xc4201e3200, 0x10bffc0, 0xc4217d5300, 0xc4201dc9e0, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/model.go:1872 +0x44d
github.com/syncthing/syncthing/lib/model.(*folder).scanSubdirs(0xc4201d92c0, 0x0, 0x0, 0x0, 0xc421c36c18, 0x3)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/folder.go:106 +0x83
github.com/syncthing/syncthing/lib/model.(*folder).scanTimerFired(0xc4201d92c0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/folder.go:118 +0x5e
github.com/syncthing/syncthing/lib/model.(*sendOnlyFolder).Serve(0xc4201d92c0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/rofolder.go:51 +0x6d4
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1(0xc4202421c0, 0xc400000007, 0x7fa9434a88c0, 0xc4201d92c0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:454 +0x63
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:444 +0x5b

[CBBHG] 2017/10/26 11:48:08.613466 rofolder.go:30: DEBUG: sendOnlyFolder/dyk5u-gr9e3@0xc4201d92c0 starting
```

We really do need to find a solution how to make this suture stuff suitable verbose: The folder was completely broken and there was no (obvious) indication in non-debug logs at all!

**Comment by calmh** [comment]
Yeah that's not great. I have a patched suture that *doesn't* capture panics, and maybe we should use something like that. I like it's service management aspects, but I'm leaning towards that we should always crash hard no matter where and how a panic happens...

**Comment by imsodin** [comment]
Totally agree. If we don't want to fork, we could also just increase the suture logging level to warning. Then it wont fail, but prominently log errors/backtraces.

**Comment by calmh** [comment]
Problem is we use that for intentional restarts. So I think it's worth separating out returns (we should restart silently) from panics (we should panic).
