### ISSUE TITLE
Panic when connecting to device with auto accept and paused folders

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing#4634]
I regularly see panics resulting in a full stop. I searched the issues, I dont see anybody reported this yet.

```
Jan  1 20:44:43 nas syncthing[2753]: [LNO6H] INFO: connections.Service: Failed service '(connections.serviceFunc)(0x89a250)' (1.000000 failures of 5.000000), restarting: true, error: runtime error: invalid memory address or nil pointer dereference, stacktrace: goroutine 81 [running]:
Jan  1 20:44:43 nas syncthing[2753]: github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1.1(0xc420248460, 0x2)
Jan  1 20:44:43 nas syncthing[2753]: #011/tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:448 +0xbc
Jan  1 20:44:43 nas syncthing[2753]: panic(0xaca000, 0x112cb30)
Jan  1 20:44:43 nas syncthing[2753]: #011/usr/local/go/src/runtime/panic.go:491 +0x283
Jan  1 20:44:43 nas syncthing[2753]: github.com/syncthing/syncthing/lib/db.(*FileSet).IndexID(0x0, 0x842e203564d6bc3b, 0xff13778a109cf56d, 0x2c3bb56bbbba9dc0, 0x4b9b920cb1291d75, 0x1)
Jan  1 20:44:43 nas syncthing[2753]: #011/tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/lib/db/set.go:319 +0x65
Jan  1 20:44:43 nas syncthing[2753]: github.com/syncthing/syncthing/lib/model.(*Model).generateClusterConfig(0xc420092900, 0x842e203564d6bc3b, 0xff13778a109cf56d, 0x2c3bb56bbbba9dc0, 0x4b9b920cb1291d75, 0x4, 0xc421aa04b0, 0xc4225373ec)
Jan  1 20:44:43 nas syncthing[2753]: #011/tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/lib/model/model.go:2167 +0x4b5
Jan  1 20:44:43 nas syncthing[2753]: github.com/syncthing/syncthing/lib/model.(*Model).AddConnection(0xc420092900, 0x10e1880, 0xc421aa0540, 0xc42e147220, 0xd, 0xc42e147214, 0x9, 0xc42e147230, 0x8)
Jan  1 20:44:43 nas syncthing[2753]: #011/tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/lib/model/model.go:1544 +0xb21
Jan  1 20:44:43 nas syncthing[2753]: github.com/syncthing/syncthing/lib/connections.(*Service).handle(0xc421c520c0)
Jan  1 20:44:43 nas syncthing[2753]: #011/tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/lib/connections/service.go:277 +0x2144
Jan  1 20:44:43 nas syncthing[2753]: github.com/syncthing/syncthing/lib/connections.(*Service).(github.com/syncthing/syncthing/lib/connections.handle)-fm()
Jan  1 20:44:43 nas syncthing[2753]: #011/tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/lib/connections/service.go:146 +0x2a
Jan  1 20:44:43 nas syncthing[2753]: github.com/syncthing/syncthing/lib/connections.serviceFunc.Serve(0xc420e7e130)
Jan  1 20:44:43 nas syncthing[2753]: #011/tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/lib/connections/structs.go:170 +0x25
Jan  1 20:44:43 nas syncthing[2753]: github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1(0xc420248460, 0xc400000002, 0x10d8e20, 0xc420e7e130)
Jan  1 20:44:43 nas syncthing[2753]: #011/tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:454 +0x63
Jan  1 20:44:43 nas syncthing[2753]: created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService
Jan  1 20:44:43 nas syncthing[2753]: #011/tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:444 +0x5b
```
it simply halts

I'm in the process to build up a backup (syncthing). The database is growing.

### Version Information

Syncthing Version: 0.14.42
OS Version: Ubuntu 17.10

**Comment by calmh** [comment]
(That’s FileSet.IndexID called on a nil fileset from generateClusterConfig, which should clearly not happen)

**Comment by lkwg82** [comment]
Filesystem for the index is ext4

**Comment by calmh** [comment]
Paused folders?

**Comment by lkwg82** [comment]
jub, some, because of spinning disks

**Comment by calmh** [comment]
auto accept or introducer checked?

**Comment by lkwg82** [comment]
jub, both

**Comment by calmh** [comment]
So the bug is that auto accept shares the folder with the device on connection, but it's paused so it doesn't actually exist internally, so it blows up when it tries to use it...

**Comment by AudriusButkevicius** [comment]
Config but not the map makes sense, as that's what paused means essentially

**Comment by AudriusButkevicius** [comment]
This turned out to be quite interesting to repro, as it happens only under the conditions where the folder does not get restarted. If the folder does get restarted (because the tests specify folders devices in a different order), you can't repro it.

This also allowed to come up with an elegant solution.

**Comment by AudriusButkevicius** [comment]
#4639
