### ISSUE TITLE
lib/model test fails with "ThreadSanitizer failed to allocate 0x200000 (2097152) bytes" with Go 1.9.2

### ISSUE THREAD

**Issue by vrusinov** [syncthing/syncthing#4653]
Checked out fresh master, no local changes.

Run tests via `./build.sh test`.

I see two test failures: one in lib/model, another is lib/logger, with similar messages:

```
GOPATH is /tmp/syncthing-3f04b07a
ok  	github.com/syncthing/syncthing/lib/auto	1.161s
ok  	github.com/syncthing/syncthing/lib/beacon	1.005s
ok  	github.com/syncthing/syncthing/lib/config	1.114s
ok  	github.com/syncthing/syncthing/lib/connections	1.019s
==20126==ERROR: ThreadSanitizer failed to allocate 0x1000000 (16777216) bytes at address 23108f400000 (errno: 12)
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
panic during panic

runtime stack:
runtime.startpanic_m()
	/usr/lib64/go/src/runtime/panic.go:671 +0x19a
runtime.systemstack(0xc42002b900)
	/usr/lib64/go/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/usr/lib64/go/src/runtime/proc.go:1135

goroutine 107 [running]:
runtime.systemstack_switch()
	/usr/lib64/go/src/runtime/asm_amd64.s:298 fp=0x7f8e9aa74d88 sp=0x7f8e9aa74d80 pc=0x486c40
runtime.dopanic_m(0xc420001500, 0x45626a, 0x7f8e9aa74e70)
	/usr/lib64/go/src/runtime/panic.go:717 +0x182 fp=0x7f8e9aa74df8 sp=0x7f8e9aa74d88 pc=0x456472
runtime.dopanic.func1()
	/usr/lib64/go/src/runtime/panic.go:587 +0x3c fp=0x7f8e9aa74e20 sp=0x7f8e9aa74df8 pc=0x485b6c
runtime.systemstack(0x7f8e9aa74e40)
	/usr/lib64/go/src/runtime/asm_amd64.s:360 +0xab fp=0x7f8e9aa74e28 sp=0x7f8e9aa74e20 pc=0x486cfb
runtime.dopanic(0x0)
	/usr/lib64/go/src/runtime/panic.go:586 +0x70 fp=0x7f8e9aa74e70 sp=0x7f8e9aa74e28 pc=0x455e70
runtime.startpanic_m()
	/usr/lib64/go/src/runtime/panic.go:671 +0x19a fp=0x7f8e9aa74e98 sp=0x7f8e9aa74e70 pc=0x45626a
runtime.systemstack(0xc42002b900)
	/usr/lib64/go/src/runtime/asm_amd64.s:344 +0x79 fp=0x7f8e9aa74ea0 sp=0x7f8e9aa74e98 pc=0x486cc9
runtime.mstart()
	/usr/lib64/go/src/runtime/proc.go:1135 fp=0x7f8e9aa74ea8 sp=0x7f8e9aa74ea0 pc=0x45a200
created by testing.(*T).Run
	/usr/lib64/go/src/testing/testing.go:789 +0x569

...
goroutine 108 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc4201670a0)
	/tmp/syncthing-3f04b07a/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x1c5
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/tmp/syncthing-3f04b07a/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x310
FAIL	github.com/syncthing/syncthing/lib/db	0.134s
ok  	github.com/syncthing/syncthing/lib/dialer	1.016s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/discover	1.655s
ok  	github.com/syncthing/syncthing/lib/events	6.425s
ok  	github.com/syncthing/syncthing/lib/fs	2.723s
ok  	github.com/syncthing/syncthing/lib/ignore	1.022s
ok  	github.com/syncthing/syncthing/lib/logger	1.007s
==20524==ERROR: ThreadSanitizer failed to allocate 0x40000 (262144) bytes at address 60014f9a0000 (errno: 12)
FATAL: ThreadSanitizer can not mmap thread trace (0x60014f9a0000/0x000000040000->0xfffffffffffffff4)
FAIL	github.com/syncthing/syncthing/lib/model	0.146s
ok  	github.com/syncthing/syncthing/lib/nat	1.009s
ok  	github.com/syncthing/syncthing/lib/osutil	1.011s
ok  	github.com/syncthing/syncthing/lib/pmp	1.009s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/protocol	1.169s
ok  	github.com/syncthing/syncthing/lib/rand	3.559s
?   	github.com/syncthing/syncthing/lib/rc	[no test files]
ok  	github.com/syncthing/syncthing/lib/relay/client	1.009s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/relay/protocol	1.006s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/scanner	2.614s
?   	github.com/syncthing/syncthing/lib/sha256	[no test files]
ok  	github.com/syncthing/syncthing/lib/signature	1.649s
ok  	github.com/syncthing/syncthing/lib/stats	1.023s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/sync	2.037s
ok  	github.com/syncthing/syncthing/lib/tlsutil	1.005s
ok  	github.com/syncthing/syncthing/lib/upgrade	1.008s
ok  	github.com/syncthing/syncthing/lib/upnp	1.010s
ok  	github.com/syncthing/syncthing/lib/util	1.007s
ok  	github.com/syncthing/syncthing/lib/versioner	1.025s
ok  	github.com/syncthing/syncthing/lib/watchaggregator	7.235s
ok  	github.com/syncthing/syncthing/lib/weakhash	1.008s
?   	github.com/syncthing/syncthing/cmd/stbench	[no test files]
?   	github.com/syncthing/syncthing/cmd/stcli	[no test files]
?   	github.com/syncthing/syncthing/cmd/stcompdirs	[no test files]
?   	github.com/syncthing/syncthing/cmd/stdisco	[no test files]
?   	github.com/syncthing/syncthing/cmd/stdiscosrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/stevents	[no test files]
?   	github.com/syncthing/syncthing/cmd/stfileinfo	[no test files]
?   	github.com/syncthing/syncthing/cmd/stfinddevice	[no test files]
?   	github.com/syncthing/syncthing/cmd/stgenfiles	[no test files]
?   	github.com/syncthing/syncthing/cmd/stindex	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaypoolsrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaysrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaysrv/testutil	[no test files]
?   	github.com/syncthing/syncthing/cmd/stsigtool	[no test files]
?   	github.com/syncthing/syncthing/cmd/stvanity	[no test files]
?   	github.com/syncthing/syncthing/cmd/stwatchfile	[no test files]
ok  	github.com/syncthing/syncthing/cmd/syncthing	11.497s
exit status 1
exit status 1

```

Not sure if it's syncthing or Go bug, but filing here in case anyone knows what's up with ThreadSanitizer.
I use 1.9.2 compiled from source and cannot reproduce with 1.8.

### Version Information

Syncthing Version:

$ PAGER="cat" git show --oneline -s 
db03562d (HEAD -> master, upstream/master, origin/master, origin/HEAD) lib/scanner: Fix UTF-8 normalization on ZFS (fixes #4649)

OS Version: Linux x64 (Gentoo)

Go: 1.9.2, compiled from source. Cannot reproduce with 1.8 provided via CentOS rpm on another box.
```
$ go version
go version go1.9.2 linux/amd64
```

**Comment by calmh** [comment]
Running out of memory?

**Comment by vrusinov** [comment]
Unlikely - machine has 8G of ram (at least 50% unused) + 22G of swap.
Tests work with go 1.8 on much smaller machine.

I've just tried on another Debian-based machine, 64G ram + 64G swap, go 1.9.2 as well, but physically different binary (may be complied with different flags), slightly different but similar result:

```
$ ./build.sh test
GOPATH is /tmp/syncthing-9cd62bce
ok  	github.com/syncthing/syncthing/lib/auto	0.785s
ok  	github.com/syncthing/syncthing/lib/beacon	0.522s
ok  	github.com/syncthing/syncthing/lib/config	0.734s
ok  	github.com/syncthing/syncthing/lib/connections	0.610s
==70780==ERROR: ThreadSanitizer failed to allocate 0x1000000 (16777216) bytes at address 23108d000000 (errno: 12)
fatal error: unexpected signal during runtime execution
FAIL	github.com/syncthing/syncthing/lib/db	0.228s
ok  	github.com/syncthing/syncthing/lib/dialer	0.575s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/discover	1.700s
ok  	github.com/syncthing/syncthing/lib/events	5.981s
ok  	github.com/syncthing/syncthing/lib/fs	2.241s
ok  	github.com/syncthing/syncthing/lib/ignore	0.618s
ok  	github.com/syncthing/syncthing/lib/logger	0.550s
==71415==ERROR: ThreadSanitizer failed to allocate 0x400000 (4194304) bytes at address 231088c00000 (errno: 12)
fatal error: unexpected signal during runtime execution
FAIL	github.com/syncthing/syncthing/lib/model	0.456s
ok  	github.com/syncthing/syncthing/lib/nat	0.669s
ok  	github.com/syncthing/syncthing/lib/osutil	0.575s
ok  	github.com/syncthing/syncthing/lib/pmp	0.581s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/protocol	0.805s
ok  	github.com/syncthing/syncthing/lib/rand	2.880s
?   	github.com/syncthing/syncthing/lib/rc	[no test files]
ok  	github.com/syncthing/syncthing/lib/relay/client	0.580s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/relay/protocol	0.544s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/scanner	1.875s
?   	github.com/syncthing/syncthing/lib/sha256	[no test files]
ok  	github.com/syncthing/syncthing/lib/signature	0.626s
ok  	github.com/syncthing/syncthing/lib/stats	0.573s [no tests to run]
ok  	github.com/syncthing/syncthing/lib/sync	1.591s
ok  	github.com/syncthing/syncthing/lib/tlsutil	0.534s
ok  	github.com/syncthing/syncthing/lib/upgrade	0.594s
ok  	github.com/syncthing/syncthing/lib/upnp	0.591s
ok  	github.com/syncthing/syncthing/lib/util	0.532s
ok  	github.com/syncthing/syncthing/lib/versioner	0.605s
ok  	github.com/syncthing/syncthing/lib/watchaggregator	6.816s
ok  	github.com/syncthing/syncthing/lib/weakhash	0.527s
?   	github.com/syncthing/syncthing/cmd/stbench	[no test files]
?   	github.com/syncthing/syncthing/cmd/stcli	[no test files]
?   	github.com/syncthing/syncthing/cmd/stcompdirs	[no test files]
?   	github.com/syncthing/syncthing/cmd/stdisco	[no test files]
?   	github.com/syncthing/syncthing/cmd/stdiscosrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/stevents	[no test files]
?   	github.com/syncthing/syncthing/cmd/stfileinfo	[no test files]
?   	github.com/syncthing/syncthing/cmd/stfinddevice	[no test files]
?   	github.com/syncthing/syncthing/cmd/stgenfiles	[no test files]
?   	github.com/syncthing/syncthing/cmd/stindex	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaypoolsrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaysrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaysrv/testutil	[no test files]
?   	github.com/syncthing/syncthing/cmd/stsigtool	[no test files]
?   	github.com/syncthing/syncthing/cmd/stvanity	[no test files]
?   	github.com/syncthing/syncthing/cmd/stwatchfile	[no test files]
ok  	github.com/syncthing/syncthing/cmd/syncthing	11.045s
exit status 1
exit status 1
```

So, so far two different machines, to different go binaries (both 1.9.2) fail, 1.8 on a smaller machine seems to work.

**Comment by imsodin** [comment]
Well @calmh was right, tests with build.sh do run out of memory, but not because of missing system memory: Commenting out the following line prevents it:
`ulimit -d 512000 &>/dev/null || true` (https://github.com/syncthing/syncthing/blob/master/build.sh#L52)  
The other two `ulimit` commands don't trigger any problems.

Original commit note from 2014:
> Try to set some reasonable resource limits when running tests

So question is have resource limits become unreasonable or has Go's resource usage become unreasonable? :P

**Comment by calmh** [comment]
We can just remove the ulimit calls. They intended to protect the previous generation of build server, but seem out of date with reality.

**Comment by vrusinov** [comment]
Indeed, this was the problem. I have not thought of checking the script.

I'm happy to send PR if there is consensus on removing ulimit. Otherwise since I can easily reproduce the problem I can find a new value of "reasonable resource limits" :)

**Comment by imsodin** [comment]
@vrusinov A PR removing them would be appreciated.

**Comment by AudriusButkevicius** [comment]
Idk why bot didn't do the job.
