### ISSUE TITLE
KCP: Benchmark doesn't work, panics after 10 minute timeout

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4711]
BenchmarkRequestsRawKCP

```
SIGQUIT: quit
PC=0x105e2d3 m=0 sigcode=0

goroutine 0 [idle]:
runtime.mach_semaphore_timedwait(0x2903, 0x5f5caef, 0x7ffeefbff784, 0xc400000000, 0x5f5caefefbff7a0, 0x16d6660, 0x7ffeefbff7b8, 0x1058ae3, 0x5f5caef, 0x1035ba2, ...)
	/usr/local/go1.9.2/src/runtime/sys_darwin_amd64.s:455 +0x13
runtime.semasleep1(0x5f5caef, 0x1035ba2)
	/usr/local/go1.9.2/src/runtime/os_darwin.go:402 +0xdf
runtime.semasleep.func1()
	/usr/local/go1.9.2/src/runtime/os_darwin.go:432 +0x33
runtime.systemstack(0x16d6600)
	/usr/local/go1.9.2/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/usr/local/go1.9.2/src/runtime/proc.go:1135

goroutine 18 [syscall]:
runtime.notetsleepg(0x16d6060, 0x5f5caef, 0x16)
	/usr/local/go1.9.2/src/runtime/lock_sema.go:280 +0x4b fp=0xc420024760 sp=0xc420024720 pc=0x101169b
runtime.timerproc()
	/usr/local/go1.9.2/src/runtime/time.go:216 +0x305 fp=0xc4200247e0 sp=0xc420024760 pc=0x104cd05
runtime.goexit()
	/usr/local/go1.9.2/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200247e8 sp=0xc4200247e0 pc=0x105ced1
created by runtime.addtimerLocked
	/usr/local/go1.9.2/src/runtime/time.go:122 +0xed

goroutine 1 [chan receive, 9 minutes]:
testing.(*B).run1(0xc420219800, 0xc420219800)
	/usr/local/go1.9.2/src/testing/benchmark.go:216 +0xa1
testing.(*B).Run(0xc420001980, 0x14659a0, 0x17, 0x147a438, 0x10dfe00)
	/usr/local/go1.9.2/src/testing/benchmark.go:513 +0x21a
testing.runBenchmarks.func1(0xc420001980)
	/usr/local/go1.9.2/src/testing/benchmark.go:417 +0x60
testing.(*B).runN(0xc420001980, 0x1)
	/usr/local/go1.9.2/src/testing/benchmark.go:141 +0xb2
testing.runBenchmarks(0x146ef4b, 0x2b, 0xc4200f43e0, 0x16d13e0, 0x8, 0x8, 0x1463e2c)
	/usr/local/go1.9.2/src/testing/benchmark.go:423 +0x49e
testing.(*M).Run(0xc420135f18, 0xc42004df70)
	/usr/local/go1.9.2/src/testing/testing.go:927 +0x31c
main.main()
	github.com/syncthing/syncthing/lib/protocol/_test/_testmain.go:124 +0xdb

goroutine 6 [select]:
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*updateHeap).updateTask(0x16d5ac0)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/updater.go:81 +0x36f
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.init.2
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/updater.go:13 +0x74

goroutine 5137 [chan receive, 9 minutes]:
github.com/syncthing/syncthing/lib/protocol.getKCPConnectionPair(0x209010582c0, 0xc420211738, 0xc420211738, 0x107b916, 0x5a6c5ebc, 0x31ef7e38)
	/Users/jb/src/github.com/syncthing/syncthing/lib/protocol/benchmark_test.go:190 +0x17b
github.com/syncthing/syncthing/lib/protocol.BenchmarkRequestsRawKCP(0xc420219800)
	/Users/jb/src/github.com/syncthing/syncthing/lib/protocol/benchmark_test.go:37 +0x26
testing.(*B).runN(0xc420219800, 0x1)
	/usr/local/go1.9.2/src/testing/benchmark.go:141 +0xb2
testing.(*B).run1.func1(0xc420219800)
	/usr/local/go1.9.2/src/testing/benchmark.go:214 +0x5a
created by testing.(*B).run1
	/usr/local/go1.9.2/src/testing/benchmark.go:207 +0x80

goroutine 5155 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x1c74800, 0x72, 0x0)
	/usr/local/go1.9.2/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420220018, 0x72, 0x0, 0x0, 0x0)
	/usr/local/go1.9.2/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420220018, 0xc4200fe000, 0x5dc, 0x5dc)
	/usr/local/go1.9.2/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadFrom(0xc420220000, 0xc4200fe000, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go1.9.2/src/internal/poll/fd_unix.go:170 +0x19a
net.(*netFD).readFrom(0xc420220000, 0xc4200fe000, 0x5dc, 0x5dc, 0xc4200275d0, 0xc420027640, 0x106598a, 0xc420027608, 0x101033e)
	/usr/local/go1.9.2/src/net/fd_unix.go:208 +0x5e
net.(*UDPConn).readFrom(0xc42000e008, 0xc4200fe000, 0x5dc, 0x5dc, 0xc4200276a8, 0x106559b, 0x13c4260, 0xc4200f4380)
	/usr/local/go1.9.2/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc42000e008, 0xc4200fe000, 0x5dc, 0x5dc, 0xc420027601, 0xc4200277c8, 0x1370ac8, 0xc4201020c0, 0x1)
	/usr/local/go1.9.2/src/net/udpsock.go:118 +0x72
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).receiver(0xc420220080, 0xc420126120)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:784 +0xa7
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).monitor
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:703 +0x82

goroutine 5172 [select, 9 minutes]:
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*UDPSession).readLoop(0xc4200c8000)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:638 +0x1cd
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.newUDPSession
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:163 +0x572

goroutine 5173 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x1c74680, 0x72, 0x0)
	/usr/local/go1.9.2/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420220118, 0x72, 0x0, 0x0, 0x0)
	/usr/local/go1.9.2/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420220118, 0xc420138600, 0x5dc, 0x5dc)
	/usr/local/go1.9.2/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadFrom(0xc420220100, 0xc420138600, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go1.9.2/src/internal/poll/fd_unix.go:170 +0x19a
net.(*netFD).readFrom(0xc420220100, 0xc420138600, 0x5dc, 0x5dc, 0x1010f010136fcc6, 0xc420026e70, 0x1386f93, 0xc420026e08, 0x101033e)
	/usr/local/go1.9.2/src/net/fd_unix.go:208 +0x5e
net.(*UDPConn).readFrom(0xc42000e028, 0xc420138600, 0x5dc, 0x5dc, 0xc420026ea8, 0x106559b, 0x13c4260, 0xc42000c2e0)
	/usr/local/go1.9.2/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc42000e028, 0xc420138600, 0x5dc, 0x5dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go1.9.2/src/net/udpsock.go:118 +0x72
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*UDPSession).receiver(0xc4200c8000, 0xc42005b2c0)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:617 +0xa7
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*UDPSession).readLoop
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:635 +0x82

goroutine 5171 [select, 9 minutes]:
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).AcceptKCP(0xc420220080, 0xc4200e3620, 0x0, 0x0)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:834 +0x233
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).Accept(0xc420220080, 0x105ced6, 0xc4200fe0c0, 0x9b8, 0xc420144108)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:824 +0x2b
github.com/syncthing/syncthing/lib/protocol.getKCPConnectionPair.func1(0xc42003e1c0, 0xc42003e3d0, 0x167e480, 0xc420220080, 0xc420222120)
	/Users/jb/src/github.com/syncthing/syncthing/lib/protocol/benchmark_test.go:179 +0x35
created by github.com/syncthing/syncthing/lib/protocol.getKCPConnectionPair
	/Users/jb/src/github.com/syncthing/syncthing/lib/protocol/benchmark_test.go:178 +0xfd

goroutine 5170 [select, 9 minutes]:
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Listener).monitor(0xc420220080)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:705 +0x21b
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.ServeConn
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/sess.go:921 +0x21d

rax    0xe
rbx    0x0
rcx    0x7ffeefbff758
rdx    0x5f5caef
rdi    0x2903
rsi    0x0
rbp    0x7ffeefbff790
rsp    0x7ffeefbff758
r8     0xc420066300
r9     0x6
r10    0xdc52da62
r11    0x206
r12    0x28bba88572f
r13    0xc420072120
r14    0x1
r15    0x0
rip    0x105e2d3
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
BenchmarkRequestsRawTCP-4             5000     201582 ns/op                                  
BenchmarkSecureSource-4            2000000        789 ns/op           8 B/op      1 allocs/op
```

**Comment by calmh** [comment]
I disabled the benchmark
