### ISSUE TITLE
daemon won't launch anymore

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [syncthing/syncthing#4826]
Hi, for no reason apparently my syncthing setup stopped working, reboot doesn't help.

My OS is ubuntu 16.04, syncthing version is 0.9.3.

The indicator shows up but stays grey and `connecting to daemon`. When clicking `show window` a window appears but stays blank apart from the cog on the top right corner and the icon on the top left corner. These are functionnal.

Here's the output of `syncthing-gtk -q && syncthing-gtk -d -v`

```
>syncthing-gtk -v -d    
D UIBuilder     Enabled: traditional_header
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /usr/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'traditional_header'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: old_gtk
D UIBuilder     Removed 'child' by attribute: header_bar
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py:453: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
D Daemon        Reading syncthing config /home/glume/.config/syncthing/config.xml
D Daemon        WebUI listens on 0.0.0.0, connecting to 127.0.0.1 instead
V Notifications Error notifications enabled
V Notifications File update notifications enabled
V Notifications Folder notifications enabled
I App           
I App           Syncthing-GTK started and running in notification area
V Daemon        Set refresh interval to 5
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 398, in _request_config
    RESTRequest(self, "system/config", self._syncthing_cb_config, self._syncthing_cb_config_error).start()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 1045, in __init__
    self.connect("event", self._socket_event)
TypeError: argument connectable: Expected Gio.SocketConnectable, but got unicode
```

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
