### ISSUE TITLE
macOS panic in FS watcher setup

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4854]
```
[TestWatchOverflow] [Test Output]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4104805]

goroutine 19 [running, locked to thread]:
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.gostream(0x4600880, 0x3, 0x13, 0x43006f0, 0x42f4000, 0x42f3000)
	/Users/jb/buildAgent-syncthing/work/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:107 +0x235
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._cgoexpwrap_4ce340c09c06_gostream(0x4600880, 0x3, 0x13, 0x43006f0, 0x42f4000, 0x42f3000)
	_cgo_gotypes.go:399 +0x5d
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:214 +0x41
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.init.1.func1()
	/Users/jb/buildAgent-syncthing/work/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:72 +0x62
created by github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.init.1
	/Users/jb/buildAgent-syncthing/work/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:65 +0x4e
```

https://build.syncthing.net/viewLog.html?buildTypeId=Syncthing_BuildMac&buildId=18881&branch_Syncthing_BuildMac=%3Cdefault%3E

**Comment by wwwutz** [comment]
since the next release

https://build.syncthing.net/viewType.html?buildTypeId=Syncthing_BuildMac&branch_Syncthing=pull%2F4889

built fine, is this still an issue ? Or do I miss some policy ?

**Comment by calmh** [comment]
It's an issue, it's just apparently an intermittent issue.

**Comment by imsodin** [comment]
Yep, unfortunately definitely not gone:

```
2018/05/10 17:20:08.631166 folder.go:152: INFO: Failed initial scan of readwrite folder "sEYUjoPv" (sEYUjoPv)
2018/05/10 17:20:08.631316 folder.go:243: WARNING: Error on folder "9ixWjJhE" (9ixWjJhE): folder path missing
2018/05/10 17:20:08.631408 folder.go:152: INFO: Failed initial scan of readwrite folder "9ixWjJhE" (9ixWjJhE)
2018/05/10 17:20:08.631516 folder.go:243: WARNING: Error on folder "yuoasyjL" (yuoasyjL): folder path missing
2018/05/10 17:20:08.631559 folder.go:152: INFO: Failed initial scan of readwrite folder "yuoasyjL" (yuoasyjL)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4281605]

goroutine 50 [running, locked to thread]:
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.gostream(0x4d003e0, 0x2, 0x1, 0x4d00880, 0x4bef000, 0x4bee000)
	/Users/jb/buildAgent-syncthing/work/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:107 +0x235
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._cgoexpwrap_4ce340c09c06_gostream(0x4d003e0, 0x2, 0x1, 0x4d00880, 0x4bef000, 0x4bee000)
	_cgo_gotypes.go:399 +0x5d
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:214 +0x41
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.init.1.func1()
	/Users/jb/buildAgent-syncthing/work/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:72 +0x62
created by github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.init.1
	/Users/jb/buildAgent-syncthing/work/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:65 +0x4e
```

**Comment by calmh** [comment]
This happening in Go code called from C doesn't give me the warm fuzzies at all

**Comment by calmh** [comment]
And also not Mac specific nor specific to that exact test. This is the linux builder:

```
[TestAutoAcceptPausedWhenFolderConfigNotChanged] [Test Output]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4281325]

goroutine 4 [running, locked to thread]:
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.gostream(0x4e08880, 0x2, 0x1, 0x4c008f0, 0x4bef000, 0x4bee000)
	/Users/jb/buildAgent-syncthing/work/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:107 +0x235
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._cgoexpwrap_4ce340c09c06_gostream(0x4e08880, 0x2, 0x1, 0x4c008f0, 0x4bef000, 0x4bee000)
	_cgo_gotypes.go:399 +0x5d
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:214 +0x41
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.init.1.func1()
	/Users/jb/buildAgent-syncthing/work/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:72 +0x62
created by github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.init.1
	/Users/jb/buildAgent-syncthing/work/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:65 +0x4e
```

**Comment by calmh** [comment]
This thing is really annoying. It's flake on the build servers and also happens to me locally.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x417b012]

goroutine 19 [running, locked to thread]:
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.gostream(0x6b00c30, 0x4, 0x11, 0x6900ef0, 0x4df9000, 0x4df8000)
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:107 +0x2d2
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._cgoexpwrap_4ce340c09c06_gostream(0x6b00c30, 0x4, 0x11, 0x6900ef0, 0x4df9000, 0x4df8000)
	_cgo_gotypes.go:399 +0x6b
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:214 +0x5f
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.init.1.func1()
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:72 +0xce
created by github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.init.1
	/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:65 +0x5c
FAIL	github.com/syncthing/syncthing/lib/fs	0.764s
```

**Comment by imsodin** [comment]
@calmh I raised a PR upstream - does it seem reasonable to you? https://github.com/rjeczalik/notify/pull/156

**Comment by calmh** [comment]
@imsodin I really don't have the expertise to say; it doesn't look *un*reasonable at least. :)
