### ISSUE TITLE
panic: incorrect length of byte slice representing device ID

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#4934]
Let me know if I this report is useful, or if you need more information.

This bug was submitted in the Debian bug tracker ([#896888](https://bugs.debian.org/896888))

I have already requested more details from the Debian submitter.

The user has gotten this stack trace when launching Syncthing:

```
[edited] 14:47:33 INFO: syncthing v0.14.46-ds1 "Dysprosium Dragonfly"
(go1.10.1 linux-amd64) debian@debian 2018-04-04 18:28:29 UTC [noupgrade]
[edited] 14:47:33 INFO: My ID: [edited]
[edited] 14:47:34 INFO: Single thread SHA256 performance is 344 MB/s using
minio/sha256-simd (287 MB/s using crypto/sha256).
[edited] 14:47:34 INFO: Hashing performance with weak hash is 249.13 MB/s
[edited] 14:47:34 INFO: Hashing performance without weak hash is 335.79 MB/s
[edited] 14:47:34 INFO: Weak hash disabled, as it has an unacceptable
performance impact.
...
Panic at 2018-04-25T14:47:35+02:00
panic: incorrect length of byte slice representing device ID

goroutine 1 [running]:
github.com/syncthing/syncthing/lib/protocol.DeviceIDFromBytes(0x1111234,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/syncthing-PqLcAU/syncthing-0.14.46+ds1/_build/src/
github.com/syncthing/syncthing/lib/protocol/deviceid.go:44 +0xa7
github.com/syncthing/syncthing/lib/db.readWriteTransaction.updateGlobal(...)
        /build/syncthing-PqLcAU/syncthing-0.14.46+ds1/_build/src/
github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:89 +0x8d
github.com/syncthing/syncthing/lib/db.(*Instance).updateSchema0to1(0xc42021b7a0)
        /build/syncthing-PqLcAU/syncthing-0.14.46+ds1/_build/src/
github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:593 +0x651
github.com/syncthing/syncthing/lib/db.(*Instance).UpdateSchema(0xc42021b7a0)
        /build/syncthing-PqLcAU/syncthing-0.14.46+ds1/_build/src/
github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:92 +0xf1
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb349d4, 0x1, 0x0, 0x0,
...)
        /build/syncthing-PqLcAU/syncthing-0.14.46+ds1/_build/src/
github.com/syncthing/syncthing/cmd/syncthing/main.go:774 +0x11cd
main.main()
        /build/syncthing-PqLcAU/syncthing-0.14.46+ds1/_build/src/
github.com/syncthing/syncthing/cmd/syncthing/main.go:440 +0x3e9
```

### Version Information

Syncthing Version: 0.14.46+ds1-1 (this is the Debian build)
OS Version: Debian Buster
Kernel: Linux 4.15.0-2-amd64 (SMP w/4 CPU cores)

**Comment by AudriusButkevicius** [comment]
He might have to do syncthing -reset-database to get around it. It seems there is something invalid in the db, yet the question is how it got in there in the first place

**Comment by calmh** [comment]
It's an interesting error. It means that when looking up the device ID in the device index in the database we got back something that isn't device ID-shaped. That's clearly not supposed to happen.

**Comment by danielholm** [comment]
I got the same issue and tried a -reset-database. It worked.
