### ISSUE TITLE
0.14.44 crash

### ISSUE THREAD

**Issue by jpdoyle** [syncthing/syncthing#5204]
I managed to trigger a crash when trying to connect my android phone to a laptop running Syncthing 0.14.44. It's possible that this has been fixed since (I've been meaning to update this machine), but I figure it's worthwhile to give y'all a stack trace:

```
panic: bug: removed more than added
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x95e89c]
goroutine 406 [running]:
github.com/syncthing/syncthing/lib/model.(*Model).Closed(0xc42008e240, 0x7f35eae11ab0, 0xc42112a150, 0x0, 0x0)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/model/model.go:1297 +0x50c
github.com/syncthing/syncthing/lib/protocol.(*nativeModel).Closed(0xc421ec2150, 0x113c3e0, 0xc4207a6180, 0x0, 0x0)
        <autogenerated>:1 +0x64
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).close.func1()
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:778 +0x20b
sync.(*Once).Do(0xc4207a6208, 0xc422c8f018)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.9.2/share/go/src/sync/once.go:44 +0xbe
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).close(0xc4207a6180, 0x0, 0x0)
```

This is only an intermittent crash, so I suspect you have some sort of race condition on closing connections.

### Version Information

Syncthing Version: v0.14.44
OS Version: NixOS:
`$ nix-shell -p nix-info --run "nix-info -m"`
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.81, NixOS, 17.09.3023.c882c4dd55e (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3023.c882c4dd55e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jpdoyle** [comment]
It actually seems to be repeating itself now, pretty consistently. With an Android phone connected to host A, a large non-syncthing I/O load on host B, starting syncthing on host B, it crashes. Here's another stack trace:
```
panic: bug: removed more than added
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x95e89c]
goroutine 78 [running]:
github.com/syncthing/syncthing/lib/model.(*Model).Closed(0xc42008e240, 0x7fe92eb0ef68, 0xc421bbf680, 0x0, 0x0)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/model/model.go:1297 +0x50c
github.com/syncthing/syncthing/lib/protocol.(*nativeModel).Closed(0xc4213a6210, 0x113c3e0, 0xc4223c40c0, 0x0, 0x0)
        <autogenerated>:1 +0x64
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).close.func1()
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:778 +0x20b
sync.(*Once).Do(0xc4223c4148, 0xc420ff9018)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.9.2/share/go/src/sync/once.go:44 +0xbe
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).close(0xc4223c40c0, 0x0, 0x0)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:765 +0x6b
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).readerLoop.func1(0xc4223c40c0, 0xc420ff9fd0)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:280 +0x41
panic(0xa9ec00, 0xdf04d0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.9.2/share/go/src/runtime/panic.go:491 +0x283
github.com/syncthing/syncthing/lib/db.(*metadataTracker).removeFile(0xc421542b00, 0xe482ca163be2a774, 0x23a2ea4dfe3ac47, 0xf3641b2c93c0b14, 0xe6b72723e49fe0c5, 0x113bde0, 0xc420ad5d
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/db/meta.go:138 +0x4f7
github.com/syncthing/syncthing/lib/db.(*Instance).updateFiles(0xc42051c7b0, 0xc42149c9f0, 0xf, 0x10, 0xc4206b98a0, 0x20, 0x20, 0xc420e6a000, 0xe8, 0x11c, ...)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:120 +0x608
github.com/syncthing/syncthing/lib/db.(*FileSet).Update(0xc421c1f450, 0xe482ca163be2a774, 0x23a2ea4dfe3ac47, 0xf3641b2c93c0b14, 0xe6b72723e49fe0c5, 0xc420e6a000, 0xe8, 0x11c)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/db/set.go:157 +0xc0d
github.com/syncthing/syncthing/lib/model.(*Model).IndexUpdate(0xc42008e240, 0xe482ca163be2a774, 0x23a2ea4dfe3ac47, 0xf3641b2c93c0b14, 0xe6b72723e49fe0c5, 0xc421203930, 0xf, 0xc420e6
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/model/model.go:886 +0x4bf
github.com/syncthing/syncthing/lib/protocol.(*nativeModel).IndexUpdate(0xc4213a6210, 0xe482ca163be2a774, 0x23a2ea4dfe3ac47, 0xf3641b2c93c0b14, 0xe6b72723e49fe0c5, 0xc421203930, 0xf,
        <autogenerated>:1 +0xa2
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).handleIndexUpdate(0xc4223c40c0, 0xc421203930, 0xf, 0xc420e6a000, 0xe8, 0x11c)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:469 +0x1c3
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).readerLoop(0xc4223c40c0, 0x0, 0x0)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:328 +0x1392
created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:171 +0x43
goroutine 1 [chan receive]:
main.syncthingMain(0x7ffd5629dba5, 0x1b, 0x0, 0x0, 0x0, 0x1, 0xba5a14, 0x1, 0x0, 0x0, ...)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:924 +0x1c5d
main.main()
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:440 +0x3c9
goroutine 6 [chan receive]:
github.com/syncthing/syncthing/vendor/github.com/zillode/notify.(*nonrecursiveTree).dispatch(0xc4200622a0, 0xc4200621e0)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/vendor/github.com/zillode/notify/tree_nonrecursive.go:36 +0xc0
created by github.com/syncthing/syncthing/vendor/github.com/zillode/notify.newNonrecursiveTree
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/vendor/github.com/zillode/notify/tree_nonrecursive.go:29 +0x149
goroutine 7 [chan receive]:
github.com/syncthing/syncthing/vendor/github.com/zillode/notify.(*nonrecursiveTree).internal(0xc4200622a0, 0xc420062240)
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/vendor/github.com/zillode/notify/tree_nonrecursive.go:81 +0x88
created by github.com/syncthing/syncthing/vendor/github.com/zillode/notify.newNonrecursiveTree
        /build/syncthing-v0.14.44-src/src/github.com/syncthing/syncthing/vendor/github.com/zillode/notify/tree_nonrecursive.go:30 +0x178
goroutine 98 [syscall]:
syscall.Syscall(0x6, 0xc421224000, 0xc421161148, 0x0, 0x0, 0xc420a27f80, 0xc420ff56c8)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.9.2/share/go/src/syscall/asm_linux_amd64.s:18 +0x5

```

**Comment by jpdoyle** [comment]
If it matters, the Android phone is running Syncthing 0.14.49 and host A (another NixOS machine) is running Syncthing 0.14.46.

**Comment by uok** [comment]
What is the reason you are running v0.14.44? The latest is v0.14.50

**Comment by AudriusButkevicius** [comment]
Did you try downloading a new binary? The fact it crashes with sigsev could meam the binary is corrupt or you have bad ram.

**Comment by imsodin** [comment]
I am pretty sure this is fixed: https://github.com/syncthing/syncthing/pull/5106

Please report back if not.
