### ISSUE TITLE
Panic: sequence index corruption

### ISSUE THREAD

**Issue by xjtdy888** [syncthing/syncthing#5234]
```
STTRACE=db 
```
will get the panic every time it runs. 

Version:
syncthing v0.14.51-rc.4+18-gc2b0d30-dirty "Dysprosium Dragonfly" (go1.10.3 darwin-amd64)

```
Panic at 2018-10-02T18:46:23+08:00
panic: sequence index corruption, file sequence 36 != expected 27

goroutine 351 [running]:
github.com/syncthing/syncthing/lib/db.(*Instance).withHaveSequence(0xc4201560c0, 0xc420628430, 0xb, 0x10, 0x1b, 0xc421085f10)
	/Users/ZZZZZZZZZZ/go/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:220 +0x6bd
github.com/syncthing/syncthing/lib/db.(*FileSet).WithHaveSequence(0xc420180cd0, 0x1b, 0xc421323170)
	/Users/ZZZZZZZZZZ/go/src/github.com/syncthing/syncthing/lib/db/set.go:218 +0x1a3
github.com/syncthing/syncthing/lib/model.sendIndexTo(0x1a, 0x5625858, 0xc4206b2540, 0xc4206ea010, 0xb, 0xc420180cd0, 0xc4201da7e0, 0xc4201a22a0, 0x7, 0xc420e95b00, ...)
	/Users/ZZZZZZZZZZ/go/src/github.com/syncthing/syncthing/lib/model/model.go:1754 +0x2ac
github.com/syncthing/syncthing/lib/model.sendIndexes(0x5625858, 0xc4206b2540, 0xc4206ea010, 0xb, 0xc420180cd0, 0xc4201da7e0, 0x1a, 0xc4201a22a0, 0x7, 0xc420bc2000)
	/Users/ZZZZZZZZZZ/go/src/github.com/syncthing/syncthing/lib/model/model.go:1728 +0x633
created by github.com/syncthing/syncthing/lib/model.(*Model).ClusterConfig
	/Users/ZZZZZZZZZZ/go/src/github.com/syncthing/syncthing/lib/model/model.go:1037 +0x1a18
```

[panic-20181002-184623.log](https://github.com/syncthing/syncthing/files/2437523/panic-20181002-184623.log)

**Comment by xjtdy888** [comment]
Reproduce:
In my environment, A is macOS, B is Linux.
1. A, B share a directory waiting for synchronization to complete
2. A machine deletes index-v0.14.0.db
3. A will get panic every time run syncthing

**Comment by calmh** [comment]
Interesting, that shouldn't happen.

**Comment by calmh** [comment]
Log doesn't look like startup without database though, as it panics on entries that it hasn't logged adding to the database?

**Comment by calmh** [comment]
This should be solved by the issues recently fixed.
