### ISSUE TITLE
`cmd/stdiscosrv` test suite sometimes seg faults on OpenBSD

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing#5247]
This seems to be another non-deterministic failure:

```
$ go run build.go test
...
ok      github.com/syncthing/syncthing/lib/versioner    0.034s
ok      github.com/syncthing/syncthing/lib/watchaggregator      7.579s
ok      github.com/syncthing/syncthing/lib/weakhash     0.005s
?       github.com/syncthing/syncthing/cmd/stbench      [no test files]
?       github.com/syncthing/syncthing/cmd/stcli        [no test files]
?       github.com/syncthing/syncthing/cmd/stcompdirs   [no test files]
?       github.com/syncthing/syncthing/cmd/stdisco      [no test files]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6efdcc]

goroutine 32 [running]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).newRawIterator(0xc000080ea0, 0x0, 0x0, 0x0, 0x0, 0xc00007b8f0, 0x0, 0xc0004eaf00, 0xc00001ea00)
        /home/porter/go/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:54 +0x29c
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).newIterator(0xc000080ea0, 0x0, 0x0, 0x0, 0x0, 0x4, 0xc000041f88, 0x0, 0x4759b6)
        /home/porter/go/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_iter.go:79 +0x99
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0xc000080ea0, 0xc000041f88, 0x0, 0x0, 0x0)
        /home/porter/go/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:886 +0x146
github.com/syncthing/syncthing/cmd/stdiscosrv.(*levelDBStore).statisticsServe(0xc00001ed80, 0xc000022960, 0xc0000229c0)
        /home/porter/go/src/github.com/syncthing/syncthing/cmd/stdiscosrv/database.go:201 +0x8ff
created by github.com/syncthing/syncthing/cmd/stdiscosrv.(*levelDBStore).Serve
        /home/porter/go/src/github.com/syncthing/syncthing/cmd/stdiscosrv/database.go:167 +0x135
...
```

I can't get it to fail in isolation sadly:
```
fremen% STRACE=stdisosrcv go test -v
=== RUN   TestFixupAddresses
--- PASS: TestFixupAddresses (0.00s)
=== RUN   TestDatabaseGetSet
--- PASS: TestDatabaseGetSet (0.08s)
=== RUN   TestFilter
--- PASS: TestFilter (0.00s)
PASS
ok      github.com/syncthing/syncthing/cmd/stdiscosrv   0.236s
```

git version: `f528923d1ef224a07d58fea21b0dca14ca18ba78`

This is the last of the OpenBSD issues that I am aware of. Sorry for filing so many!

**Comment by calmh** [comment]
I can see why this might happen in the tests

**Comment by calmh** [comment]
See if this helps:


```diff
diff --git a/cmd/stdiscosrv/database.go b/cmd/stdiscosrv/database.go
index 33234ea4..8a267980 100644
--- a/cmd/stdiscosrv/database.go
+++ b/cmd/stdiscosrv/database.go
@@ -162,10 +162,10 @@ func (s *levelDBStore) Serve() {
        // Start the statistics serve routine. It will exit with us when
        // statisticsTrigger is closed.
        statisticsTrigger := make(chan struct{})
-       defer close(statisticsTrigger)
        statisticsDone := make(chan struct{})
        go s.statisticsServe(statisticsTrigger, statisticsDone)

+loop:
        for {
                select {
                case fn := <-s.inbox:
@@ -184,12 +184,17 @@ func (s *levelDBStore) Serve() {

                case <-s.stop:
                        // We're done.
-                       return
+                       close(statisticsTrigger)
+                       break loop
                }
        }
+
+       <-statisticsDone
 }

 func (s *levelDBStore) statisticsServe(trigger <-chan struct{}, done chan<- struct{}) {
+       defer close(done)
+
        for range trigger {
                t0 := time.Now()
                nowNanos := t0.UnixNano()
```
