### ISSUE TITLE
WebGUI doesn't work in 0.14.53 in old Firefox and unable to launch old version

### ISSUE THREAD

**Issue by alguryanow** [syncthing/syncthing#5348]
After automatic upgrade from 0.14.52 to 0.14.53 webGui doesn't work anymore in Firefox 29. 
The main page is almost empty and it seems like javascript isn't working. For example on the top of the page I see {{thisDeviceName()}} instead of the actual name of device. I do not see any shared folders (just the header "Folders") and connected devices. I'm also unable to open any page with settings - when I click on any menu-item from menu Actions nothing happens.

And I unable to start previous version (syncthing.old) because of changed database format:

[235QK] 12:14:03 FATAL: Database schema: Syncthing v0.14.53 required

### Version Information

Syncthing Version: v0.14.53
OS Version: some old clone of Debian
Browser Version: Firefox 29.0

I'm unable to upgrade browser on this system. I'm unable to use any other browser on this system as well. 
GUI was working well just before automatic upgrade of syncthing (previous one was 0.14.52)

Because of non-working GUI right now I'm unable to reconfigure syncthing to allow access from other computers.

**Comment by calmh** [comment]
The one thing I can imagine is the new TLS 1.2 requirement; however TLS 1.2 should be supported in Firefox 27+ according to my Googling.

**Comment by calmh** [comment]
I'll Google that too for you:

https://accountants-community.intuit.com/articles/1737631-how-to-enable-tls-1-2-in-internet-explorer-11

Try those steps.

**Comment by uok** [comment]
In the screenshot there is a HTTP url, so it must be something else?

**Comment by calmh** [comment]
Yeah, just realized.

**Comment by mrkingmidas** [comment]
I am try, but already this settings set by admin. This is WinServer 2012 R2.

![image](https://user-images.githubusercontent.com/1373772/49508331-816bb280-f893-11e8-92fd-a1349e79ca85.png)

**Comment by calmh** [comment]
Can you check the browser javascript console for any errors?

**Comment by mrkingmidas** [comment]
This console ?
![image](https://user-images.githubusercontent.com/1373772/49508715-78c7ac00-f894-11e8-8f3c-6b0368471c3c.png)

**Comment by uok** [comment]
IE11 gives this JS error
```
Error: [ng:areq] Argument 'SyncthingController' is not a function, got undefined
http://errors.angularjs.org/1.3.20/ng/areq?p0=SyncthingController&p1=not%20a%20function%2C%20got%20undefined
at assertArg (https://myhost:1234/vendor/angular/angular.js:1609:5)
at assertArgFn (https://myhost:1234/vendor/angular/angular.js:1619:3)
at Anonymous function (https://myhost:1234/vendor/angular/angular.js:8512:9)
at Anonymous function (https://myhost:1234/vendor/angular/angular.js:7680:13)
at forEach (https://myhost:1234/vendor/angular/angular.js:353:11)
at nodeLinkFn (https://myhost:1234/vendor/angular/angular.js:7667:11)
at compositeLinkFn (https://myhost:1234/vendor/angular/angular.js:7159:13)
at publicLinkFn (https://myhost:1234/vendor/angular/angular.js:7038:30)
at Anonymous function (https://myhost:1234/vendor/angular/angular.js:1479:11)
at Scope.prototype.$eval (https://myhost:1234/vendor/angular/angular.js:14589:9)
```
which seems because of (partial) missing ES6 support
https://stackoverflow.com/questions/40473277/error-ngareq-argument-maincontroller-is-not-a-function-got-undefined-in-i
could also be the reason for old FF

**Comment by uok** [comment]
IE11 gives this JS error
```
Error: [ng:areq] Argument 'SyncthingController' is not a function, got undefined
http://errors.angularjs.org/1.3.20/ng/areq?p0=SyncthingController&p1=not%20a%20function%2C%20got%20undefined
at assertArg (https://myhost:1234/vendor/angular/angular.js:1609:5)
at assertArgFn (https://myhost:1234/vendor/angular/angular.js:1619:3)
at Anonymous function (https://myhost:1234/vendor/angular/angular.js:8512:9)
at Anonymous function (https://myhost:1234/vendor/angular/angular.js:7680:13)
at forEach (https://myhost:1234/vendor/angular/angular.js:353:11)
at nodeLinkFn (https://myhost:1234/vendor/angular/angular.js:7667:11)
at compositeLinkFn (https://myhost:1234/vendor/angular/angular.js:7159:13)
at publicLinkFn (https://myhost:1234/vendor/angular/angular.js:7038:30)
at Anonymous function (https://myhost:1234/vendor/angular/angular.js:1479:11)
at Scope.prototype.$eval (https://myhost:1234/vendor/angular/angular.js:14589:9)
```
which seems because of (partial) missing ES6 support
https://stackoverflow.com/questions/40473277/error-ngareq-argument-maincontroller-is-not-a-function-got-undefined-in-i
https://angular.io/guide/browser-support
could also be the reason for old FF

**Comment by calmh** [comment]
Yeah, screenshot error points to `Object.entries` which seems like something newfangled

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

**Comment by calmh** [comment]
Oh and I see there is also ES6 syntax there, yes.

**Comment by mrkingmidas** [comment]
> * [Windows](https://build.syncthing.net/viewLog.html?buildId=30405&buildTypeId=Syncthing_BuildWindows&tab=artifacts)
Yes, 64-bit version work!

**Comment by uok** [comment]
Great bug hunting everybody! :tada:

**Comment by alguryanow** [comment]
On old Debian's clone in Firefox 29 patched version works too. And 0.14.54 as well. 

Thanks a lot!

**Comment by bugith** [comment]
I keep a copy of "SSL Version Control 0.4.1-signed.xpi" plugin to run with old FF. Maybe hard to find nowadays. Just ask
