### ISSUE TITLE
Incorrect file info passed as argument to delete existing file

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#5616]
This is a regression introduced in #5567 and thus relevant for the current v1.1.1 RC. To reproduce, run `TestSymlinksSimpleVersioning` from the integration test suite (or possible any other symlink test). The test will time out and one Syncthing log contains:

```
   1677 panic: bug: attempting to version a symlink
   1678 
   1679 goroutine 805 [running]:
   1680 github.com/syncthing/syncthing/lib/versioner.Simple.Archive(0x5, 0xf30580, 0xc0001710b0, 0xc0017eb7e0, 0xb, 0xc0004b75   1680 70, 0x7ad2c3)
   1681         /media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/versioner/simple.go:54 +0x1180
   1682 github.com/syncthing/syncthing/lib/osutil.InWritableDir(0xc0004b7668, 0xf30180, 0xc0001c01b0, 0xc0017eb7e0, 0xb, 0x0,    1682 0x0)
   1683         /media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/osutil/osutil.go:88 +0x120
   1684 github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).deleteItemOnDisk(0xc0000f2b00, 0xc0017eb7e0, 0xb, 0x0, 0   1684 x0, 0x1b4, 0x5c98af96, 0x1c534b9e, 0x479403ffdef496b5, 0x0, ...)
   1685         /media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/folder_sendrecv.go:1817 +0x204
   1686 github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).performFinish(0xc0000f2b00, 0xc0017eb7e0, 0xb, 0x0, 0x0,   1686  0x1b4, 0x5c98af96, 0x1c534b9e, 0x479403ffdef496b5, 0x0, ...)
   1687         /media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/folder_sendrecv.go:1524 +0x5fc
   1688 github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).finisherRoutine(0xc0000f2b00, 0xc00204a6c0, 0xc00204a780   1688 , 0xc00204a480)
   1689         /media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/folder_sendrecv.go:1553 +0x96d
   1690 github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pullerIteration.func4(0xc0000f2b00, 0xc00204a6c0, 0xc002   1690 04a780, 0xc00204a480, 0xf1f640, 0xc0017dabd0)
   1691         /media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/folder_sendrecv.go:264 +0x49
   1692 created by github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pullerIteration
   1693         /media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/folder_sendrecv.go:263 +0x4ee
   1694 
```

The culprit is `file` instead of `curFile` here: https://github.com/syncthing/syncthing/commit/8e238c8e48cd6ef3ba9ef24a2df7a8f86ecdb9f2#diff-cf783533b0c2c4fe7c3a325925917a56R1531  
PR incoming.

**Comment by calmh** [comment]
So this happens when versioning is enabled and there is an existing symlink to be replaced with something not-symlink, yes?

**Comment by imsodin** [comment]
Yes, that's what I understand from that integration test. However it seems to be more complicated than that, as a simple unit test doing just that (creating and syncing a regular file, then replacing with a symlink) did not trigger the panic.

**Comment by calmh** [comment]
Other direction, I think. As is (buggy) we skip versioning if the new thing is a symlink. With the fix it checks if the old thing is a symlink.
