### ISSUE TITLE
panic: chmod ...: operation not permitted

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5836]
```
syncthing v1.1.4 "Erbium Earthworm" (go1.12.5 linux-amd64) teamcity@build.syncthing.net 2019-05-12 19:17:55 UTC

goroutine 1000714 [running]:
github.com/syncthing/syncthing/lib/osutil.InWritableDir.func1(0xf2f5c0, 0xc0046400f0, 0xc005d32dc0, 0x19, 0xf28f00, 0xc002e475d0, 0xc0004a8c30)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/osutil/osutil.go:107 +0xb4
github.com/syncthing/syncthing/lib/osutil.InWritableDir(0xc0004a8d68, 0xf2f5c0, 0xc0046400f0, 0xc005d32dc0, 0x4b, 0xf10ec0, 0xc002e77d10)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/osutil/osutil.go:113 +0x13b
github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).deleteFile(0xc0001c0840, 0xc005d32dc0, 0x4b, 0x0, 0x0, 0x0, 0x5b26c0bf, 0x29d0c913, 0xa6a9c1e3243bbb5c, 0x1, ...)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder_sendrecv.go:856 +0x89b
github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).processDeletions(0xc0001c0840, 0xc002e76a20, 0x0, 0x0, 0x0, 0xc0027798c0, 0xc0027796e0)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder_sendrecv.go:509 +0x294
github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pullerIteration(0xc0001c0840, 0xc0027796e0, 0xc002779600)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder_sendrecv.go:283 +0x6a2
github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pull(0xc0001c0840, 0x4063c0898b700)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder_sendrecv.go:195 +0x70b
github.com/syncthing/syncthing/lib/model.(*folder).Serve.func2()
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder.go:137 +0x8c
github.com/syncthing/syncthing/lib/model.(*folder).Serve(0xc0001c0840)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder.go:163 +0x4db
github.com/thejerf/suture.(*Supervisor).runService.func1(0xc0002b1a40, 0xc00000000d, 0x7fade8522550, 0xc0001c0840)
	/opt/tcagent/syncthing-1-work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:600 +0x47
created by github.com/thejerf/suture.(*Supervisor).runService
	/opt/tcagent/syncthing-1-work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:588 +0x5b
```

https://github.com/syncthing/syncthing/blob/e4956358fbab0d78e975d474acba2a0d098e4adc/lib/osutil/osutil.go#L103-L108

Comment says it's bizarre and I agree (I probably wrote it), nonetheless here we are. A panic isn't super appropriate here.

**Comment by AudriusButkevicius** [comment]
This does lead to a bad state however, so not clear of the best way to handle this.

**Comment by calmh** [comment]
Warning level message? The state is equally bad after we panicked, after all.
