### ISSUE TITLE
Takes a long time to shut down on Ctrl-C (1.2.1-rc.1)

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5860]
```
MRIW7] 22:14:47 INFO: Detected 2 NAT services
[monitor] 22:14:48 INFO: Signal 2 received; exiting
[MRIW7] 22:14:48 INFO: TCP listener (127.0.0.1:22002) shutting down
2019/07/16 22:14:58 Supervisor discover.cachingMux: discover.cachingMux: Service IPv6 local failed to terminate in a timely manner
2019/07/16 22:14:58 Supervisor local: local: Service multicastBeacon failed to terminate in a timely manner
[MRIW7] 22:14:58 INFO: connections.Service: Service c.S.listenerSupervisor failed to terminate in a timely manner
[MRIW7] 22:14:58 INFO: c.S.listenerSupervisor: Service dynamic+https://relays.syncthing.net/endpoint failed to terminate in a timely manner
[MRIW7] 22:14:58 INFO: Exiting
```

v1.2.1-rc.1

**Comment by calmh** [comment]
Also, a couple of supervisor log entries that don't pass through our own logging framework apparently.

**Comment by calmh** [comment]
v1.2.1 regression

**Comment by imsodin** [comment]
The (or at least a) problem is the relay listener not terminating timely. I enabled connection debug log (and some manual debug strings) and after sending INT followed that by an ABRT to get the stack

```
[TDZP4] 2019/07/17 00:04:49.745101 syncthing.go:368: INFO: app stopping
[TDZP4] 2019/07/17 00:04:49.745397 quic_listen.go:125: INFO: QUIC listener ([::]:22000) shutting down
[TDZP4] 2019/07/17 00:04:49.894085 tcp_listen.go:86: INFO: TCP listener ([::]:22000) shutting down
SIGABRT: abort
PC=0x4b6eda m=0 sigcode=0
[...]
goroutine 95 [runnable]:
internal/poll.runtime_pollWait(0x7f09fc173a58, 0x77, 0xc00030c180)
	/media/ext4_data/Linux/source/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00011f418, 0x77, 0x105fb00, 0xc0000f3260, 0xc00011f400)
	/media/ext4_data/Linux/source/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitWrite(...)
	/media/ext4_data/Linux/source/go/src/internal/poll/fd_poll_runtime.go:96
internal/poll.(*FD).WaitWrite(...)
	/media/ext4_data/Linux/source/go/src/internal/poll/fd_unix.go:498
net.(*netFD).connect(0xc00011f400, 0x105fb00, 0xc0000f3260, 0x0, 0x0, 0x104d620, 0xc0001170c0, 0x0, 0x0, 0x0, ...)
	/media/ext4_data/Linux/source/go/src/net/fd_unix.go:152 +0x29d
net.(*netFD).dial(0xc00011f400, 0x105fb00, 0xc0000f3260, 0x1064440, 0x0, 0x1064440, 0xc0001057d0, 0x0, 0x1, 0xc0006592f0)
	/media/ext4_data/Linux/source/go/src/net/sock_posix.go:149 +0xff
net.socket(0x105fb00, 0xc0000f3260, 0xd856d5, 0x3, 0x2, 0x1, 0x0, 0x0, 0x1064440, 0x0, ...)
	/media/ext4_data/Linux/source/go/src/net/sock_posix.go:70 +0x1c0
net.internetSocket(0x105fb00, 0xc0000f3260, 0xd856d5, 0x3, 0x1064440, 0x0, 0x1064440, 0xc0001057d0, 0x1, 0x0, ...)
	/media/ext4_data/Linux/source/go/src/net/ipsock_posix.go:141 +0x141
net.(*sysDialer).doDialTCP(0xc00011f380, 0x105fb00, 0xc0000f3260, 0x0, 0xc0001057d0, 0xc7fdc0, 0x16273d0, 0x0)
	/media/ext4_data/Linux/source/go/src/net/tcpsock_posix.go:65 +0xc2
net.(*sysDialer).dialTCP(0xc00011f380, 0x105fb00, 0xc0000f3260, 0x0, 0xc0001057d0, 0xc00006d2b0, 0x10, 0x10)
	/media/ext4_data/Linux/source/go/src/net/tcpsock_posix.go:61 +0xd7
net.(*sysDialer).dialSingle(0xc00011f380, 0x105fb00, 0xc0000f3260, 0x1056260, 0xc0001057d0, 0x0, 0x0, 0x0, 0x0)
	/media/ext4_data/Linux/source/go/src/net/dial.go:578 +0x36e
net.(*sysDialer).dialSerial(0xc00011f380, 0x105fb00, 0xc0000f3260, 0xc00006d2b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/media/ext4_data/Linux/source/go/src/net/dial.go:546 +0x221
net.(*Dialer).DialContext(0xc0006598a0, 0x105fac0, 0xc0000360e8, 0xd856d5, 0x3, 0xc0006e6ea8, 0x14, 0x0, 0x0, 0x0, ...)
	/media/ext4_data/Linux/source/go/src/net/dial.go:424 +0x666
net.(*Dialer).Dial(...)
	/media/ext4_data/Linux/source/go/src/net/dial.go:347
net.DialTimeout(0xd856d5, 0x3, 0xc0006e6ea8, 0x14, 0x3b9aca00, 0x1, 0x44fc18, 0x2d35087e0c67, 0x276f21b9)
	/media/ext4_data/Linux/source/go/src/net/dial.go:333 +0xb5
github.com/syncthing/syncthing/lib/dialer.DialTimeout(0xd856d5, 0x3, 0xc0006e6ea8, 0x14, 0x3b9aca00, 0x0, 0x0, 0xc7, 0x0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/dialer/public.go:51 +0x81
github.com/syncthing/syncthing/lib/osutil.TCPPing(0xc0006e6ea8, 0x14, 0xc00011f300, 0x0, 0x0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/osutil/ping.go:21 +0x7f
github.com/syncthing/syncthing/lib/osutil.GetLatencyForURL(0xc0006e6ea0, 0xc7, 0x2, 0xc000659c48, 0x0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/osutil/ping.go:36 +0x80
github.com/syncthing/syncthing/lib/relay/client.relayAddressesOrder(0xc00040b000, 0xd8, 0x100, 0x3, 0x0, 0xc00040b000)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/relay/client/dynamic.go:154 +0xec
github.com/syncthing/syncthing/lib/relay/client.(*dynamicClient).serve(0xc0001ca1c0, 0xc0001534a0, 0x0, 0x0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/relay/client/dynamic.go:80 +0x5d5
github.com/syncthing/syncthing/lib/relay/client.newCommonClient.func1(0xc0001534a0, 0x0, 0x0)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/relay/client/client.go:61 +0x74
github.com/syncthing/syncthing/lib/util.(*service).Serve(0xc00027e240)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/util/utils.go:232 +0x11d
created by github.com/syncthing/syncthing/lib/connections.(*relayListener).Serve
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/connections/relay_listen.go:57 +0x165
[...]
goroutine 175 [chan receive]:
github.com/syncthing/syncthing/lib/util.(*service).Stop(0xc00027e240)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/util/utils.go:239 +0x78
github.com/syncthing/syncthing/lib/connections.(*relayListener).Stop(0xc0001c8240)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/connections/relay_listen.go:124 +0x81
github.com/thejerf/suture.(*Supervisor).stopSupervisor.func1(0x7f09fc11b800, 0xc0001c8240, 0xc00013e2d0, 0x2d, 0xc000b8e070, 0x1)
	/media/ext4_data/Coding/go/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:651 +0x31
created by github.com/thejerf/suture.(*Supervisor).stopSupervisor
	/media/ext4_data/Coding/go/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:650 +0x204
```

@AudriusButkevicius Is it ok if I steal your changes to lib/relay/client in #5753 and adapt them to allow early termination?

**Comment by AudriusButkevicius** [comment]
See if it helps, I suspect that PR will address a big chunk of the problem. We could also abuse the contexts better in the services, with util.AsServiceWithContext
