### ISSUE TITLE
Panic in 1.2.1 rc-2

### ISSUE THREAD

**Issue by tezfair** [syncthing/syncthing#5872]
Not sure if this is related to #5837, but my rc-2 just threw this..
```
2019/07/18 21:29:48 http: panic serving 127.0.0.1:50022: runtime error: index out of range
goroutine 46080 [running]:
net/http.(*conn).serve.func1(0xc00006f360)
	C:/Go/src/net/http/server.go:1769 +0x140
panic(0xc80120, 0x163af70)
	C:/Go/src/runtime/panic.go:522 +0x1c3
github.com/syncthing/syncthing/lib/model.(*model).NeedFolderFiles(0xc000c46000, 0xc00031b379, 0xe, 0x1, 0xa, 0x0, 0xc0011714b8, 0x6dfc60, 0xc003ae6880, 0xc0043e8910, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/model/model.go:852 +0x700
github.com/syncthing/syncthing/lib/api.(*service).getDBNeed(0xc000077040, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:697 +0xd5
net/http.HandlerFunc.ServeHTTP(0xc000061dd0, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6880, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.getPostHandler.func1(0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:425 +0xed
net/http.HandlerFunc.ServeHTTP(0xc0038b64b0, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.metricsMiddleware.func1(0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:517 +0x11e
net/http.HandlerFunc.ServeHTTP(0xc0000a5260, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.noCacheMiddleware.func1(0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:540 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc0000a5280, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6940, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.csrfMiddleware.func1(0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api_csrf.go:44 +0x6b6
net/http.HandlerFunc.ServeHTTP(0xc0000aa4d0, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.withDetailsMiddleware.func1(0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:548 +0x2d5
net/http.HandlerFunc.ServeHTTP(0xc003ae6a00, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.corsMiddleware.func1(0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:509 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc0000a5300, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.localhostMiddleware.func1(0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:555 +0x94
net/http.HandlerFunc.ServeHTTP(0xc0000a5320, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.debugMiddleware.func1(0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:437 +0xae
net/http.HandlerFunc.ServeHTTP(0xc0000a5340, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.serverHandler.ServeHTTP(0xc000666270, 0x10449a0, 0xc002c5e0e0, 0xc0000fa400)
	C:/Go/src/net/http/server.go:2774 +0xaf
net/http.(*conn).serve(0xc00006f360, 0x1046da0, 0xc005242880)
	C:/Go/src/net/http/server.go:1878 +0x858
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/07/18 21:29:48 http: panic serving 127.0.0.1:49951: runtime error: index out of range
goroutine 43092 [running]:
net/http.(*conn).serve.func1(0xc003002780)
	C:/Go/src/net/http/server.go:1769 +0x140
panic(0xc80120, 0x163af70)
	C:/Go/src/runtime/panic.go:522 +0x1c3
github.com/syncthing/syncthing/lib/model.(*model).NeedFolderFiles(0xc000c46000, 0xc0029f8609, 0xe, 0x1, 0xa, 0x0, 0xc000ac14b8, 0x6dfc60, 0xc003ae6880, 0xc003de7ab0, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/model/model.go:852 +0x700
github.com/syncthing/syncthing/lib/api.(*service).getDBNeed(0xc000077040, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:697 +0xd5
net/http.HandlerFunc.ServeHTTP(0xc000061dd0, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6880, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.getPostHandler.func1(0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:425 +0xed
net/http.HandlerFunc.ServeHTTP(0xc0038b64b0, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.metricsMiddleware.func1(0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:517 +0x11e
net/http.HandlerFunc.ServeHTTP(0xc0000a5260, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.noCacheMiddleware.func1(0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:540 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc0000a5280, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6940, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.csrfMiddleware.func1(0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api_csrf.go:44 +0x6b6
net/http.HandlerFunc.ServeHTTP(0xc0000aa4d0, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.withDetailsMiddleware.func1(0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:548 +0x2d5
net/http.HandlerFunc.ServeHTTP(0xc003ae6a00, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.corsMiddleware.func1(0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:509 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc0000a5300, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.localhostMiddleware.func1(0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:555 +0x94
net/http.HandlerFunc.ServeHTTP(0xc0000a5320, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.debugMiddleware.func1(0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:437 +0xae
net/http.HandlerFunc.ServeHTTP(0xc0000a5340, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.serverHandler.ServeHTTP(0xc000666270, 0x10449a0, 0xc0031bc9a0, 0xc0003a4e00)
	C:/Go/src/net/http/server.go:2774 +0xaf
net/http.(*conn).serve(0xc003002780, 0x1046da0, 0xc00127b3c0)
	C:/Go/src/net/http/server.go:1878 +0x858
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/07/18 21:29:48 http: panic serving 127.0.0.1:50029: runtime error: index out of range
goroutine 46856 [running]:
net/http.(*conn).serve.func1(0xc00006fb80)
	C:/Go/src/net/http/server.go:1769 +0x140
panic(0xc80120, 0x163af70)
	C:/Go/src/runtime/panic.go:522 +0x1c3
github.com/syncthing/syncthing/lib/model.(*model).NeedFolderFiles(0xc000c46000, 0xc001098109, 0xe, 0x1, 0xa, 0x0, 0xc000b0f4b8, 0x6dfc60, 0xc003ae6880, 0xc001433890, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/model/model.go:852 +0x700
github.com/syncthing/syncthing/lib/api.(*service).getDBNeed(0xc000077040, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:697 +0xd5
net/http.HandlerFunc.ServeHTTP(0xc000061dd0, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6880, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.getPostHandler.func1(0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:425 +0xed
net/http.HandlerFunc.ServeHTTP(0xc0038b64b0, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.metricsMiddleware.func1(0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:517 +0x11e
net/http.HandlerFunc.ServeHTTP(0xc0000a5260, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.noCacheMiddleware.func1(0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:540 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc0000a5280, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6940, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.csrfMiddleware.func1(0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api_csrf.go:44 +0x6b6
net/http.HandlerFunc.ServeHTTP(0xc0000aa4d0, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.withDetailsMiddleware.func1(0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:548 +0x2d5
net/http.HandlerFunc.ServeHTTP(0xc003ae6a00, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.corsMiddleware.func1(0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:509 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc0000a5300, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.localhostMiddleware.func1(0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:555 +0x94
net/http.HandlerFunc.ServeHTTP(0xc0000a5320, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.debugMiddleware.func1(0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:437 +0xae
net/http.HandlerFunc.ServeHTTP(0xc0000a5340, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.serverHandler.ServeHTTP(0xc000666270, 0x10449a0, 0xc0001910a0, 0xc001560100)
	C:/Go/src/net/http/server.go:2774 +0xaf
net/http.(*conn).serve(0xc00006fb80, 0x1046da0, 0xc0033c9980)
	C:/Go/src/net/http/server.go:1878 +0x858
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/07/18 21:29:48 http: panic serving 127.0.0.1:50030: runtime error: index out of range
goroutine 46896 [running]:
net/http.(*conn).serve.func1(0xc000212820)
	C:/Go/src/net/http/server.go:1769 +0x140
panic(0xc80120, 0x163af70)
	C:/Go/src/runtime/panic.go:522 +0x1c3
github.com/syncthing/syncthing/lib/model.(*model).NeedFolderFiles(0xc000c46000, 0xc00031b6e9, 0xe, 0x1, 0xa, 0x0, 0xc006ded4b8, 0x6dfc60, 0xc003ae6880, 0xc0043e8a60, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/model/model.go:852 +0x700
github.com/syncthing/syncthing/lib/api.(*service).getDBNeed(0xc000077040, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:697 +0xd5
net/http.HandlerFunc.ServeHTTP(0xc000061dd0, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6880, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.getPostHandler.func1(0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:425 +0xed
net/http.HandlerFunc.ServeHTTP(0xc0038b64b0, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.metricsMiddleware.func1(0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:517 +0x11e
net/http.HandlerFunc.ServeHTTP(0xc0000a5260, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.noCacheMiddleware.func1(0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:540 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc0000a5280, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6940, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.csrfMiddleware.func1(0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api_csrf.go:44 +0x6b6
net/http.HandlerFunc.ServeHTTP(0xc0000aa4d0, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.withDetailsMiddleware.func1(0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:548 +0x2d5
net/http.HandlerFunc.ServeHTTP(0xc003ae6a00, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.corsMiddleware.func1(0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:509 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc0000a5300, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.localhostMiddleware.func1(0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:555 +0x94
net/http.HandlerFunc.ServeHTTP(0xc0000a5320, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.debugMiddleware.func1(0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:437 +0xae
net/http.HandlerFunc.ServeHTTP(0xc0000a5340, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.serverHandler.ServeHTTP(0xc000666270, 0x10449a0, 0xc002c5e2a0, 0xc001560500)
	C:/Go/src/net/http/server.go:2774 +0xaf
net/http.(*conn).serve(0xc000212820, 0x1046da0, 0xc00675cd80)
	C:/Go/src/net/http/server.go:1878 +0x858
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
2019/07/18 21:29:49 http: panic serving 127.0.0.1:50032: runtime error: index out of range
goroutine 47030 [running]:
net/http.(*conn).serve.func1(0xc00006f220)
	C:/Go/src/net/http/server.go:1769 +0x140
panic(0xc80120, 0x163af70)
	C:/Go/src/runtime/panic.go:522 +0x1c3
github.com/syncthing/syncthing/lib/model.(*model).NeedFolderFiles(0xc000c46000, 0xc00163d289, 0xe, 0x1, 0xa, 0x0, 0xc0007f74b8, 0x6dfc60, 0xc003ae6880, 0xc0000747d0, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/model/model.go:852 +0x700
github.com/syncthing/syncthing/lib/api.(*service).getDBNeed(0xc000077040, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:697 +0xd5
net/http.HandlerFunc.ServeHTTP(0xc000061dd0, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6880, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.getPostHandler.func1(0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:425 +0xed
net/http.HandlerFunc.ServeHTTP(0xc0038b64b0, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.metricsMiddleware.func1(0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:517 +0x11e
net/http.HandlerFunc.ServeHTTP(0xc0000a5260, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.noCacheMiddleware.func1(0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:540 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc0000a5280, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc003ae6940, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:2375 +0x1dd
github.com/syncthing/syncthing/lib/api.csrfMiddleware.func1(0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api_csrf.go:44 +0x6b6
net/http.HandlerFunc.ServeHTTP(0xc0000aa4d0, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.withDetailsMiddleware.func1(0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:548 +0x2d5
net/http.HandlerFunc.ServeHTTP(0xc003ae6a00, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.corsMiddleware.func1(0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:509 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc0000a5300, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.localhostMiddleware.func1(0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:555 +0x94
net/http.HandlerFunc.ServeHTTP(0xc0000a5320, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/syncthing/syncthing/lib/api.debugMiddleware.func1(0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/BuildAgent/work/174e136266f8a219/lib/api/api.go:437 +0xae
net/http.HandlerFunc.ServeHTTP(0xc0000a5340, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:1995 +0x4b
net/http.serverHandler.ServeHTTP(0xc000666270, 0x10449a0, 0xc000190e00, 0xc000a99000)
	C:/Go/src/net/http/server.go:2774 +0xaf
net/http.(*conn).serve(0xc00006f220, 0x1046da0, 0xc002a70a00)
	C:/Go/src/net/http/server.go:1878 +0x858
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
```

however Syncthing appears to be continuing (under synctrazor). Thought it was worth mentioning.

**Comment by imsodin** [comment]
Another RC bug, introduced in https://github.com/syncthing/syncthing/pull/5804
