### ISSUE TITLE
folderconfiguration.go crash on creating new config on Android

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#5955]
Go crash, see forum topic for details: https://forum.syncthing.net/t/problem-creating-configuration-on-android-q/13648

```
12:12:58E/Go       goroutine 1 [running]:
12:12:58E/Go       github.com/syncthing/syncthing/lib/config.(*FolderConfiguration).prepare(0x628bc0b0)
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/lib/config/folderconfiguration.go:253 +0x206
12:12:58E/Go       github.com/syncthing/syncthing/lib/config.NewFolderConfiguration(0x777638d6, 0x92749d36, 0x9f569bb3, 0x4ff8f9e6, 0x4c28ebf5, 0xca934f1f, 0x5a5d7db, 0xa870023f, 0x5ff844ee, 0x7, ...)
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/lib/config/folderconfiguration.go:86 +0x12f
12:12:58E/Go       github.com/syncthing/syncthing/lib/syncthing.DefaultConfig(0x62a8bc20, 0x44, 0x777638d6, 0x92749d36, 0x9f569bb3, 0x4ff8f9e6, 0x4c28ebf5, 0xca934f1f, 0x5a5d7db, 0xa870023f, ...)
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/lib/syncthing/utils.go:53 +0x2d7
12:12:58E/Go       main.generate(0xfffe9811, 0x39, 0x0, 0x0)
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:440 +0x452
12:12:58E/Go       main.main()
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:347 +0x23e
```

**Comment by Catfriend1** [comment]
This line fixes it for me: (folderconfiguration.go#253)

`l.Debugf(`Detecting FS at %v on android: Setting mtime window to 2s: err == %v`, f.Path, err)`

**Comment by Catfriend1** [comment]
Ah cool, I'll test your commit ...

**Comment by Catfriend1** [comment]
Damn, it's looking good on a fresh app install, WORKS. :-)

> 13:14:33 [start] DEBUG: Detecting FS at "/storage/emulated/0/DCIM" on android: Setting mtime window to 2s: usage.Fstype == ""
