### ISSUE TITLE
github.com/syncthing/syncthing/lib/protocol tests running out of memory on 32bit arches

### ISSUE THREAD

**Issue by decathorpe** [syncthing/syncthing#6209]
With the changes between syncthing 1.3.1 and 1.3.2, running the tests for `github.com/syncthing/syncthing/lib/protocol` on 32 bit architectures (i686 and armv7hl) now runs out of system memory:

on armv7hl:

```
runtime: out of memory: cannot allocate 20922368-byte block (2805399552 in use)
fatal error: out of memory
```

on i686:

```
runtime: out of memory: cannot allocate 23289856-byte block (3761274880 in use)
fatal error: out of memory
```

Can I ignore this issue on 32 bit architectures?

Syncthing Version: v1.3.2
OS Version: fedora (32)

**Comment by imsodin** [comment]
There have been changes to that part of the code in 1.3.2 and allocating ~20GiB doesn't seem right. Do you get stacktraces/test info about when/where this happens?

**Comment by decathorpe** [comment]
Yes, sorry, I should have included that:

```
runtime: out of memory: cannot allocate 19210240-byte block (3765501952 in use)
fatal error: out of memory
runtime stack:
runtime.throw(0x56a0c555, 0xd)
	/usr/lib/golang/src/runtime/panic.go:774 +0x70
runtime.largeAlloc(0x1251f7c, 0xbe0101, 0xfa9c3d5)
	/usr/lib/golang/src/runtime/malloc.go:1140 +0x11a
runtime.mallocgc.func1()
	/usr/lib/golang/src/runtime/malloc.go:1033 +0x3a
runtime.systemstack(0x524fd700)
	/usr/lib/golang/src/runtime/asm_386.s:399 +0x62
runtime.mstart()
	/usr/lib/golang/src/runtime/proc.go:1146
goroutine 36 [running]:
runtime.systemstack_switch()
	/usr/lib/golang/src/runtime/asm_386.s:360 fp=0x58c7ee7c sp=0x58c7ee78 pc=0x566a08a0
runtime.mallocgc(0x1251f7c, 0x56b9b180, 0x56818001, 0x5668a9c5)
	/usr/lib/golang/src/runtime/malloc.go:1032 +0x6ff fp=0x58c7eed0 sp=0x58c7ee7c pc=0x566503ff
runtime.makeslice(0x56b9b180, 0x1251f7c, 0x1251f7c, 0x1c0)
	/usr/lib/golang/src/runtime/slice.go:49 +0x50 fp=0x58c7eee4 sp=0x58c7eed0 pc=0x5668aa10
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Get(0x58cac180, 0x1251f7c, 0x1251f7c, 0xbac2c7, 0x1000000)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:34 +0x21b fp=0x58c7ef0c sp=0x58c7eee4 pc=0x569e299b
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:91 +0xa5 fp=0x58c7efd0 sp=0x58c7ef0c pc=0x56a00435
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_386.s:1325 +0x1 fp=0x58c7efd4 sp=0x58c7efd0 pc=0x566a2301
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
goroutine 1 [chan receive]:
testing.(*T).Run(0x58cde640, 0x56a0f630, 0x14, 0x56c05a60, 0x301)
	/usr/lib/golang/src/testing/testing.go:961 +0x2f2
testing.runTests.func1(0x58cde460)
	/usr/lib/golang/src/testing/testing.go:1202 +0x5b
testing.tRunner(0x58cde460, 0x58c81edc)
	/usr/lib/golang/src/testing/testing.go:909 +0xae
testing.runTests(0x58c0e170, 0x56e8f6e0, 0x2c, 0x2c, 0x0)
	/usr/lib/golang/src/testing/testing.go:1200 +0x28b
testing.(*M).Run(0x58c94180, 0x0)
	/usr/lib/golang/src/testing/testing.go:1117 +0x16e
main.main()
	_testmain.go:144 +0x14f
goroutine 6 [sleep]:
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:310
time.Sleep(0x1dcd6500, 0x0)
	/usr/lib/golang/src/runtime/time.go:105 +0x17a
github.com/syncthing/syncthing/lib/dialer.init.0.func2()
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/dialer/internal.go:52 +0x2a
created by github.com/syncthing/syncthing/lib/dialer.init.0
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/dialer/internal.go:51 +0x1f7
goroutine 10 [semacquire]:
sync.runtime_Semacquire(0x58c1c604)
	/usr/lib/golang/src/runtime/sema.go:56 +0x37
sync.(*WaitGroup).Wait(0x58c1c604)
	/usr/lib/golang/src/sync/waitgroup.go:130 +0x7d
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool(0x58cde640)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:104 +0x23d
testing.tRunner(0x58cde640, 0x56c05a60)
	/usr/lib/golang/src/testing/testing.go:909 +0xae
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:960 +0x2d3
goroutine 11 [runnable]:
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Get(0x58cac180, 0xa1a9a6, 0xa1a9a6, 0x1aa7ab, 0x1000000)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:55 +0x169
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:91 +0xa5
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
goroutine 12 [runnable]:
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Get(0x58cac180, 0x14a7fb6, 0x14a7fb6, 0xaf4084, 0x1000000)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:34 +0x21b
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:91 +0xa5
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
goroutine 13 [runnable]:
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Get(0x58cac180, 0x117dd5b, 0x117dd5b, 0x0, 0x56ed5900)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:34 +0x21b
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:91 +0xa5
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
goroutine 14 [semacquire]:
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Get(0x58cac180, 0x142a65d, 0x142a65d, 0x4b2a17, 0x800000)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:34 +0x21b
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:91 +0xa5
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
goroutine 15 [runnable]:
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Get(0x58cac180, 0x16c74f4, 0x16c74f4, 0xe69556, 0x1000000)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:34 +0x21b
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:91 +0xa5
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
goroutine 16 [runnable]:
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Get(0x58cac180, 0x15f78bb, 0x15f78bb, 0x10b0b78, 0x10b0b78)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:34 +0x21b
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:91 +0xa5
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
goroutine 34 [semacquire]:
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Put(0x58cac180, 0x6445a000, 0x5f089, 0x800000)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:60 +0x2d
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:98 +0x12b
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
goroutine 35 [runnable]:
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Get(0x58cac180, 0x14bb269, 0x14bb269, 0x62b495, 0x800000)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:34 +0x21b
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:91 +0xa5
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
goroutine 37 [runnable]:
github.com/syncthing/syncthing/lib/protocol.(*bufferPool).Get(0x58cac180, 0x120bed3, 0x120bed3, 0xfd9241, 0x1000000)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool.go:34 +0x21b
github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool.func1(0x58c1c604, 0x387948fd, 0xbf71b14b, 0x18207a, 0x0, 0x56ed5900, 0x58cac180, 0x58c22480)
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:91 +0xa5
created by github.com/syncthing/syncthing/lib/protocol.TestStressBufferPool
	/builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/protocol/bufferpool_test.go:82 +0x21d
FAIL	github.com/syncthing/syncthing/lib/protocol	0.219s
FAIL
```

Looks like the test creates a lot of goroutines (recursively?) at `lib/protocol/bufferpool_test.go:82` and `lib/protocol/bufferpool_test.go:91` - not sure if that's the cause of the OOM crash though.

**Comment by imsodin** [comment]
Ah yeah, I missed my mark by three orders of magnitudes, the allocation in the panic message is MiBs not GiBs. That test spawns 10 goroutines that all take blocks of 0-24MiB size from a pool and take them back immediately. I just tested and running that test resulted in peak (resident) memory usage of 1-2GiB. That's more than I expected and maybe we should change that test to use less memory (if possible), but it's definitely not a problem for Syncthing itself, i.e. you can safely ignore these failures (or up the available memory on your test runners).

**Comment by calmh** [comment]
Not arguing with the conclusions, just noting that this is one of the tests that are skipped with `-short`. We have other non-short tests that also take nontrivial amounts of CPU or RAM. I think that's OK for those kinds of tests.

**Comment by decathorpe** [comment]
So I'll just have to invoke `go test` with `-short` for `github.com/syncthing/syncthing/lib/protocol` to skip this test?
I'll probably do that, since it consistently failed due to OOM issues on the fedora 32 bit builders.
Thanks!
