### ISSUE TITLE
TestRequest failure on FreeBSD ("file is invalid")

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing#6618]
On yesterday's master (c20ed80dc473ae7476a9359a55f7ec2618eb62e2) on FreeBSD-12.1 I saw the following:

```
=== RUN   TestRequest
11:47:15 INFO: No stored folder metadata for "default"; recalculating
11:47:15 INFO: Ready to synchronize "default" (default) (sendreceive)
11:47:15 INFO: Completed initial scan of sendreceive folder "default" (default)
    TestRequest: model_test.go:141: file is invalid
--- FAIL: TestRequest (0.01s)      
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x109f9a2]
                                        
goroutine 811 [running]:             
testing.tRunner.func1.1(0x11e7240, 0x1bdd790)
        /usr/local/go/src/testing/testing.go:941 +0x5d0
testing.tRunner.func1(0xc0006c97a0)            
        /usr/local/go/src/testing/testing.go:944 +0x600
panic(0x11e7240, 0x1bdd790)      
        /usr/local/go/src/runtime/panic.go:973 +0x3e3
github.com/syncthing/syncthing/lib/model.TestRequest(0xc0006c97a0)
        /usr/home/edd/syncthing/lib/model/model_test.go:143 +0x1f2
testing.tRunner(0xc0006c97a0, 0x1326540)
        /usr/local/go/src/testing/testing.go:992 +0x1ec
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1043 +0x661
FAIL    github.com/syncthing/syncthing/lib/model        3.555s
```

**Comment by imsodin** [comment]
The panic is just a small issue with the test (https://github.com/syncthing/syncthing/pull/6620), the actual relevant bit is `TestRequest: model_test.go:141: file is invalid`. Which is only returned when request `size` or offset are < 0 (not the case), the requested file is internal (not either) or ignored. The test operates in the default test folder, and `foo` is a pretty common name when testing, so test interference might be to blame. Did any other tests fail in the same run? Can you reproduce?

**Comment by vext01** [comment]
I did a git pull just now and got a similar (but not identical) crash:

```
=== RUN   TestParseReport 
{"message":"panic: runtime error: invalid memory address or nil pointer dereference","event_id":"","project":"","timestamp":"0001-01-01T00:00:00.00","level":"","logger":"","platform":"go","release":"v1.1.3","environment":"Development","tags":[["version","v1.1.3+39-g62a6d619e-dirty"],["tag","v1.1.3"],["codename","Erbium Earthworm"],["runtime","go1.12.1"],["goos","darwin"],["goarch","amd64"],["builder","jb@kvar.kastelo.net"],["commit","62a6d619e"]],"extra":{"url":"https://crash.syncthing.net/report/1/2/345"},"stacktrace":{"frames":[{"filename":"/Users/jb/dev/github.com/syncthing/syncthing/lib/connections/service.go","function":"func1","module":"(*service).dialParallel","lineno":838,"abs_path":"/Users/jb/dev/github.com/syncthing/syncthing/lib/connections/service.go","in_app":false},{"filename":"/Users/jb/dev/github.com/syncthing/syncthing/lib/connections/service.go","function":"setConnectionStatus","module":"(*service)","lineno":689,"abs_path":"/Users/jb/dev/github.com/syncthing/syncthing/lib/connections/service.go","context_line":"\treturn listenerFactory, nil","pre_context":["\t\treturn nil, err","\t}",""],"post_context":["}","","func filterAndFindSleepDuration(nextDial map[string]time.Time, seen []string, now time.Time) (map[string]time.Time, time.Duration) {"],"in_app":false}]}}
--- PASS: TestParseReport (1.04s)
```

[full output](https://gist.github.com/vext01/85762ffde2a1f6ec7031da32c6244623)

There's no stack trace like before...

**Comment by imsodin** [comment]
In that log I only find the failure from #6613, everything else passes. From the failure in the original post, do you have the full log?

**Comment by vext01** [comment]
So after a `git pull` I ran the tests all day and couldn't repro this.

I used:
```
for i in `jot 1000`; do go run build.go test >LOG 2>&1; if grep 'file is invalid' LOG; then break;fi ; done
```

But nada.

So let's close this!
