### ISSUE TITLE
Doesn't work with large dirs - runtime/cgo: pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by x011** [syncthing/syncthing#7246]
What's the point of developing `syncthing` if it  doesn't work with large dirs?
The whole point is to sync dirs, **no matter their size**, and I cannot sync a dir with 260 GB from a raspberry to a windows computer. Plain and simple. 
You can blame it on the lack of resources, but if this app was a bit smarter, it would limit the resources according to the system it runs, which is doesn't
Just disappointed with this.

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0xb6e8f6f6 m=2

goroutine 0 [idle]:

goroutine 1 [chan receive]:
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x686b80, 0x1, 0x0, ...)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:831 +0x29a8
main.main()
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:380 +0x70c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.7/src/runtime/asm_arm.s:998 +0x4

goroutine 50 [chan receive]:
github.com/syncthing/syncthing/lib/model.(*Model).internalScanFolderSubdirs(0x111a6fd0, 0x111aa5f4, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/lib/model/model.go:1832 +0xc58
github.com/syncthing/syncthing/lib/model.(*folder).scanSubdirsIfHealthy(0x128fa7e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/lib/model/folder.go:44 +0x3bc
github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).Serve(0x128fa7e0)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/lib/model/rwfolder.go:280 +0x1b98
github.com/thejerf/suture.(*Supervisor).runService.func1(0x10f854d0, 0x0, 0xb449eba0, 0x128fa7e0)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/thejerf/suture/supervisor.go:454 +0x5c
created by github.com/thejerf/suture.(*Supervisor).runService
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/thejerf/suture/supervisor.go:457 +0x44

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go-1.7/src/runtime/sigqueue.go:116 +0x190
os/signal.loop()
        /usr/lib/go-1.7/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /usr/lib/go-1.7/src/os/signal/signal_unix.go:28 +0x30

goroutine 51 [IO wait]:
net.runtime_pollWait(0xb4442130, 0x77, 0x124a5098)
        /usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).wait(0x1253e638, 0x77, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).waitWrite(0x1253e638, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/fd_poll_runtime.go:82 +0x30
net.(*netFD).connect(0x1253e600, 0xab31a0, 0x1253e5c0, 0x0, 0x0, 0xaaf980, 0x12146500, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/fd_unix.go:152 +0x260
net.(*netFD).dial(0x1253e600, 0xab31a0, 0x1253e5c0, 0xab3ee8, 0x0, 0xab3ee8, 0x121464e0, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/sock_posix.go:137 +0x248
net.socket(0xab31a0, 0x1253e5c0, 0x12704400, 0x3, 0x2, 0x1, 0x0, 0x0, 0xab3ee8, 0x0, ...)
        /usr/lib/go-1.7/src/net/sock_posix.go:89 +0x2ec
net.internetSocket(0xab31a0, 0x1253e5c0, 0x12704400, 0x3, 0xab3ee8, 0x0, 0xab3ee8, 0x121464e0, 0x1, 0x0, ...)
        /usr/lib/go-1.7/src/net/ipsock_posix.go:158 +0xd0
net.doDialTCP(0xab31a0, 0x1253e5c0, 0x12704400, 0x3, 0x0, 0x121464e0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/tcpsock_posix.go:58 +0x90
net.dialTCP(0xab31a0, 0x1253e5c0, 0x12704400, 0x3, 0x0, 0x121464e0, 0x540ad89d, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/tcpsock_posix.go:54 +0xac
net.dialSingle(0xab31a0, 0x1253e5c0, 0x1122a5f0, 0xab1450, 0x121464e0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/dial.go:501 +0x644
net.dialSerial(0xab31a0, 0x1253e5c0, 0x1122a5f0, 0x12614248, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/dial.go:469 +0x734
net.(*Dialer).DialContext(0x124a562c, 0xab31a0, 0x1253e5c0, 0x12704400, 0x3, 0x12704406, 0xe, 0x0, 0x0, 0x0, ...)
        /usr/lib/go-1.7/src/net/dial.go:351 +0x8cc
net.(*Dialer).Dial(0x124a562c, 0x12704400, 0x3, 0x12704406, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/dial.go:282 +0x80
net.DialTimeout(0x12704400, 0x3, 0x12704406, 0xe, 0x540be400, 0x2, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/net/dial.go:268 +0x70
github.com/syncthing/syncthing/lib/dialer.DialTimeout(0x12704400, 0x3, 0x12704406, 0xe, 0x540be400, 0x2, 0x0, 0x0, 0x0, 0x0)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/lib/dialer/public.go:51 +0xfc
github.com/syncthing/syncthing/lib/connections.(*tcpDialer).Dial(0x12614228, 0x183be563, 0xb35b4527, 0xf7ba1f5d, 0x356e7973, 0x131696af, 0x77d167b7, 0x18519089, 0xffb894b6, 0x1253e540, ...)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/lib/connections/tcp_dial.go:36 +0x94
github.com/syncthing/syncthing/lib/connections.(*Service).connect(0x1284c2d0)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/lib/connections/service.go:413 +0x1b20
github.com/syncthing/syncthing/lib/connections.(*Service).(github.com/syncthing/syncthing/lib/connections.connect)-fm()
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/lib/connections/service.go:155 +0x1c
github.com/syncthing/syncthing/lib/connections.serviceFunc.Serve(0x11bf8bc0)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/syncthing/syncthing/lib/connections/structs.go:127 +0x1c
github.com/thejerf/suture.(*Supervisor).runService.func1(0x1284c1b0, 0x0, 0xab1b50, 0x11bf8bc0)
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/thejerf/suture/supervisor.go:454 +0x5c
created by github.com/thejerf/suture.(*Supervisor).runService
        /build/syncthing-IOYMc5/syncthing-0.14.18+dfsg1/_build/src/github.com/thejerf/suture/supervisor.go:457 +0x44
```

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
