### ISSUE TITLE
Syncthing install via brew fails on M1 Big Sur 

### ISSUE THREAD

**Issue by tauren** [syncthing/syncthing#7282]
### Does your log mention database corruption?

No

### which version of Syncthing and what operating system you are using

syncthing v1.12.1
macOS Big Sur 11.1 on new M1 MacBookPro

### browser and version, if applicable

n/a

### what happened

Attempt to install using `brew install syncthing` fails

```
% brew install syncthing
Warning: Treating syncthing as a formula. For the cask, use homebrew/cask/syncthing
Error: syncthing: no bottle available!
You can try to install from source with:
  brew install --build-from-source syncthing
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

Attempt to install using `brew install --build-from-source syncthing` succeeds

```
% brew install --build-from-source syncthing
Warning: Treating syncthing as a formula. For the cask, use homebrew/cask/syncthing
==> Downloading https://homebrew.bintray.com/bottles/go-1.15.6.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/c2bd24b5a24c19bfdf97a8904aaa76c4db2a8f59096aade83310fee7af4b186c?response-
######################################################################## 100.0%
==> Downloading https://github.com/syncthing/syncthing/archive/v1.12.1.tar.gz
==> Downloading from https://codeload.github.com/syncthing/syncthing/tar.gz/v1.12.1
######################################################################## 100.0%
==> Installing dependencies for syncthing: go
==> Installing syncthing dependency: go
==> Pouring go-1.15.6.arm64_big_sur.bottle.tar.gz
==> Caveats
This is a beta version of the Go compiler for Apple Silicon
(Go 1.16beta1).
==> Summary
🍺  /opt/homebrew/Cellar/go/1.15.6: 10,058 files, 522.2MB
==> Installing syncthing
==> go run build.go --version v1.12.1 --no-upgrade tar
==> syncthing cask is installed, skipping link.
==> Caveats
To have launchd start syncthing now and restart at login:
  brew services start syncthing
Or, if you don't want/need a background service you can just run:
  syncthing
==> Summary
🍺  /opt/homebrew/Cellar/syncthing/1.12.1: 23 files, 22.4MB, built in 1 minute 1 second
==> Caveats
==> go
This is a beta version of the Go compiler for Apple Silicon
(Go 1.16beta1).
==> syncthing
To have launchd start syncthing now and restart at login:
  brew services start syncthing
Or, if you don't want/need a background service you can just run:
  syncthing
```

Starting service using `brew services start syncthing` appears to succeed

```
% brew services start syncthing
==> Successfully started `syncthing` (label: homebrew.mxcl.syncthing)
```

Running a verbose test using `brew test --verbose syncthing` shows an error occurred

```
% brew test --verbose syncthing
git config --replace-all homebrew.devcmdrun true
==> Testing syncthing
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210114-93916-1fs1vns.sb ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/test.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/syncthing.rb --verbose
==> /opt/homebrew/Cellar/syncthing/1.12.1/bin/syncthing --version
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x1b4

Error: syncthing: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<2>.
/Library/Ruby/Gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:55:in `block in assert_block'
/Library/Ruby/Gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1636:in `_wrap_assertion'
/Library/Ruby/Gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:53:in `assert_block'
/Library/Ruby/Gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:240:in `assert_equal'
/opt/homebrew/Library/Homebrew/formula_assertions.rb:19:in `shell_output'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/syncthing.rb:69:in `block in <class:Syncthing>'
/opt/homebrew/Library/Homebrew/formula.rb:1910:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/utils.rb:531:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1909:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:899:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1908:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2156:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:1902:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:42:in `<main>'
```

### what you expected to happen instead

I was hoping it would install and run on a new M1 Mac using Homebrew! :)
 
### any steps to reproduce the problem.

Steps are listed above. I've already communicated with the Homebrew project:
https://github.com/Homebrew/discussions/discussions/547

And a new bottle request was submitted, but failed:
https://github.com/Homebrew/homebrew-core/actions/runs/487191067

Here's some additional information.

```
% syncthing
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x1b4

% syncthing --version
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x1b4

% syncthing -generate ./
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x1b4
```

**Comment by calmh** [comment]
This is a brew packaging issue, though one that we now facilitate avoiding by not building the quic package with the beta Go compiler. You can use our binary of 1.13.0-rc.1 in the meantime.
