### ISSUE TITLE
systemd not starting.  errors out (Debian 9)

### ISSUE THREAD

**Issue by imwireless** [syncthing/syncthing#7363]
Ive tried to get this going every which way I can.   I followed the guide you have here.  [Guide](https://docs.syncthing.net/users/autostart.html#linux)

```[Unit]
Description=Syncthing - Open Source Continuous File Synchronization for %I
Documentation=man:syncthing(1)
After=network.target

[Service]
User=%i
ExecStart=/usr/bin/syncthing serve --no-browser --no-restart --logflags=0
Restart=on-failure
RestartSec=5
SuccessExitStatus=3 4
RestartForceExitStatus=3 4

# Hardening
ProtectSystem=full
PrivateTmp=true
SystemCallArchitectures=native
MemoryDenyWriteExecute=true
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```
I added the above inside my /etc/systemd/system/
I then ran the systemctl enable syncthing@david.service
and then systemctl start syncthing@david.service

This is my error:
```root@website:/home/david# systemctl enable syncthing@david.service
Created symlink /etc/systemd/system/default.target.wants/syncthing@david.service → /etc/systemd/system/syncthing@.service.
root@website:/home/david# systemctl start syncthing@david.service
root@website:/home/david# systemctl status syncthing@david.service
● syncthing@david.service - Syncthing - Open Source Continuous File Synchronization
   Loaded: loaded (/etc/systemd/system/syncthing@.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2021-02-14 00:30:32 EST; 4s ago
     Docs: man:syncthing(1)
  Process: 16480 ExecStart=/usr/bin/syncthing serve --no-browser --no-restart --logflags=0 (code=exited, status=2)
 Main PID: 16480 (code=exited, status=2)

Feb 14 00:30:32 website.net systemd[1]: syncthing@david.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 00:30:32 website.net systemd[1]: syncthing@david.service: Unit entered failed state.
Feb 14 00:30:32 website.net systemd[1]: syncthing@david.service: Failed with result 'exit-code'.
```
```
Feb 14 00:35:24 website.net systemd[1]: syncthing@david.service: Failed with result 'exit-code'.
Feb 14 00:35:24 website.net systemd[1]: syncthing@david.service: Unit entered failed state.
Feb 14 00:35:24 website.net systemd[1]: syncthing@david.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 00:35:24 website.net syncthing[17445]:         github.com/syncthing/syncthing/lib/locations/locations.go:57 +0x34
Feb 14 00:35:24 website.net syncthing[17445]: github.com/syncthing/syncthing/lib/locations.init.0()
Feb 14 00:35:24 website.net syncthing[17445]:         github.com/syncthing/syncthing/lib/locations/locations.go:188 +0xd3
Feb 14 00:35:24 website.net syncthing[17445]: github.com/syncthing/syncthing/lib/locations.userHomeDir(0x30, 0x1022100)
Feb 14 00:35:24 website.net syncthing[17445]: goroutine 1 [running]:
Feb 14 00:35:24 website.net syncthing[17445]: panic: Failed to get user home dir
Feb 14 00:35:24 website.net syncthing[17445]: $HOME is not defined
Feb 14 00:35:24 website.net systemd[1]: Started Syncthing - Open Source Continuous File Synchronization.
Feb 14 00:35:24 website.net systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization.
Feb 14 00:35:24 website.net systemd[1]: syncthing@david.service: Service hold-off time over, scheduling restart.
```
```
-- Logs begin at Sat 2021-02-06 21:25:17 EST, end at Sun 2021-02-14 00:40:44 EST. --
Feb 14 00:40:44 website.net systemd[1]: syncthing@david.service: Failed with result 'exit-code'.
Feb 14 00:40:44 website.net systemd[1]: syncthing@david.service: Unit entered failed state.
Feb 14 00:40:44 website.net systemd[1]: syncthing@david.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 00:40:44 website.net systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for david.
Feb 14 00:40:44 website.net systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for david.
Feb 14 00:40:44 website.net systemd[1]: syncthing@david.service: Service hold-off time over, scheduling restart.
Feb 14 00:40:39 website.net systemd[1]: syncthing@david.service: Failed with result 'exit-code'.
Feb 14 00:40:39 website.net systemd[1]: syncthing@david.service: Unit entered failed state.
Feb 14 00:40:39 website.net systemd[1]: syncthing@david.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 00:40:39 website.net systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for david.
Feb 14 00:40:39 website.net systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for david.
Feb 14 00:40:39 website.net systemd[1]: syncthing@david.service: Service hold-off time over, scheduling restart.
Feb 14 00:40:33 website.net systemd[1]: syncthing@david.service: Failed with result 'exit-code'.
Feb 14 00:40:33 website.net systemd[1]: syncthing@david.service: Unit entered failed state.
Feb 14 00:40:33 website.net systemd[1]: syncthing@david.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 00:40:33 website.net systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for david.
Feb 14 00:40:33 website.net systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for david.
Feb 14 00:40:33 website.net systemd[1]: syncthing@david.service: Service hold-off time over, scheduling restart.

```

```
Feb 14 00:48:41 website.net systemd[1]: syncthing@david.service: Failed with result 'exit-code'.
Feb 14 00:48:41 website.net systemd[1]: syncthing@david.service: Unit entered failed state.
Feb 14 00:48:41 website.net systemd[1]: syncthing@david.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 00:48:41 website.net syncthing[20011]:   -version                  Show version
Feb 14 00:48:41 website.net syncthing[20011]:   -verbose                  Print verbose log output
Feb 14 00:48:41 website.net syncthing[20011]:   -upgrade-to=""            Force upgrade directly from specified URL
Feb 14 00:48:41 website.net syncthing[20011]:   -upgrade-check            Check for available upgrade
Feb 14 00:48:41 website.net syncthing[20011]:   -upgrade                  Perform upgrade
Feb 14 00:48:41 website.net syncthing[20011]:   -unpaused                 Start with all devices and folders unpaused
Feb 14 00:48:41 website.net syncthing[20011]:   -reset-deltas             Reset delta index IDs, forcing a full index exchange
Feb 14 00:48:41 website.net syncthing[20011]:   -reset-database           Reset the database, forcing a full rescan and resync
Feb 14 00:48:41 website.net syncthing[20011]:   -paused                   Start with all devices and folders paused
Feb 14 00:48:41 website.net syncthing[20011]:   -paths                    Show configuration paths
Feb 14 00:48:41 website.net syncthing[20011]:   -no-restart               Do not restart Syncthing when exiting due to API/GUI command, upgrade, or crash
Feb 14 00:48:41 website.net syncthing[20011]:   -no-browser               Do not start browser
Feb 14 00:48:41 website.net syncthing[20011]:   -logflags="2"             Select information in log line prefix (see below)
Feb 14 00:48:41 website.net syncthing[20011]:   -logfile="-"              Log file name (see below).
Feb 14 00:48:41 website.net syncthing[20011]:   -log-max-size="10485760"  Maximum size of any file (zero to disable log rotation).
Feb 14 00:48:41 website.net syncthing[20011]:   -log-max-old-files="3"    Number of old files to keep (zero to keep only current).
Feb 14 00:48:41 website.net syncthing[20011]:   -home=""                  Set configuration and data directory
Feb 14 00:48:41 website.net syncthing[20011]:   -help                     Show this help
Feb 14 00:48:41 website.net syncthing[20011]:   -gui-apikey=""            Override GUI API key
Feb 14 00:48:41 website.net syncthing[20011]:   -gui-address=""           Override GUI address (e.g. "http://192.0.2.42:8443")
Feb 14 00:48:41 website.net syncthing[20011]:   -generate=""              Generate key and config in specified dir, then exit
Feb 14 00:48:41 website.net syncthing[20011]:   -device-id                Show the device ID
Feb 14 00:48:41 website.net syncthing[20011]:   -data=""                  Set data directory (database and logs)
Feb 14 00:48:41 website.net syncthing[20011]:   -config=""                Set configuration directory (config and keys)
Feb 14 00:48:41 website.net syncthing[20011]:   -browser-only             Open GUI in browser
Feb 14 00:48:41 website.net syncthing[20011]:   -auditfile=""             Specify audit file (use "-" for stdout, "--" for stderr)
Feb 14 00:48:41 website.net syncthing[20011]:   -audit                    Write events to audit file
Feb 14 00:48:41 website.net syncthing[20011]:   -allow-newer-config       Allow loading newer than current config version
Feb 14 00:48:41 website.net syncthing[20011]: Options:
Feb 14 00:48:41 website.net syncthing[20011]:   syncthing [options]
Feb 14 00:48:41 website.net syncthing[20011]: Usage:
Feb 14 00:48:41 website.net systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for david.
Feb 14 00:48:41 website.net systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for david.
Feb 14 00:48:41 website.net systemd[1]: syncthing@david.service: Service hold-off time over, scheduling restart.

```

**Comment by imwireless** [comment]
Ok i think i got this.  I removed the serve from the exec in systemd and this seems to have worked.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
