### ISSUE TITLE
panic: leveldb: internal key "…" corrupted: invalid type

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7569]
I have had this very strange panic today. Syncthing restarted automatically and continued to work as usual, so I have only found about it by looking for panic log files.

```
Panic at 2021-04-13T19:01:10+09:00
panic: leveldb: internal key "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff" corrupted: invalid type

goroutine 145925 [running]:
github.com/syndtr/goleveldb/leveldb.memGet(0xc00107c620, 0xc0020cc7e0, 0x6a, 0x6a, 0xc0001e55b0, 0x70, 0x3724a3, 0x1, 0xc0020cc7e0, 0x6a, ...)
	github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/db.go:748 +0x35d
github.com/syndtr/goleveldb/leveldb.(*DB).get(0xc0000fca80, 0x0, 0x0, 0x0, 0x0, 0xc0020cc770, 0x62, 0x70, 0x3724a3, 0x0, ...)
	github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/db.go:779 +0x1be
github.com/syndtr/goleveldb/leveldb.(*DB).Get(0xc0000fca80, 0xc0020cc770, 0x62, 0x70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/db.go:851 +0x148
github.com/syncthing/syncthing/lib/db/backend.(*leveldbBackend).Get(0xc0003c00e0, 0xc0020cc770, 0x62, 0x70, 0x62, 0x70, 0x70, 0x62, 0xc0020cc770)
	github.com/syncthing/syncthing/lib/db/backend/leveldb_backend.go:90 +0x7a
github.com/syncthing/syncthing/lib/db.NamespacedKV.Bytes(0x2086390, 0xc0000de380, 0xc0001d1910, 0x5, 0xc000be42a0, 0x5d, 0xc000be42a0, 0x5d, 0x1d7425f, 0xc000bb3b40, ...)
	github.com/syncthing/syncthing/lib/db/namespaced.go:95 +0xd1
github.com/syncthing/syncthing/lib/fs.(*mtimeFS).load(0xc000309710, 0xc000be42a0, 0x5d, 0xc000bb3bc8, 0x3, 0xc000bb3c10, 0x163b92e, 0xc000be42a0, 0xc000bb3bc8, 0x3, ...)
	github.com/syncthing/syncthing/lib/fs/mtimefs.go:177 +0x66
github.com/syncthing/syncthing/lib/fs.(*mtimeFS).Walk.func1(0xc000be42a0, 0x5d, 0x20855f8, 0xc002780490, 0x0, 0x0, 0xc000bb3d10, 0x10)
	github.com/syncthing/syncthing/lib/fs/mtimefs.go:109 +0xea
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0xc000a9f758, 0xc000be42a0, 0x5d, 0x20855f8, 0xc002780490, 0xc0035be210, 0x0, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:90 +0x18b
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0xc000a9f758, 0xc00276a510, 0x26, 0x20855f8, 0xc000a56980, 0xc0035be210, 0x0, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:124 +0x5a7
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).Walk(0xc000a9f758, 0xc00276a510, 0x26, 0xc0035be210, 0x0, 0xc0035be210)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:150 +0xf8
github.com/syncthing/syncthing/lib/fs.(*caseFilesystem).Walk(0xc0007d64e0, 0xc00276a510, 0x26, 0xc0035be210, 0x1, 0x0)
	github.com/syncthing/syncthing/lib/fs/casefs.go:319 +0xc2
github.com/syncthing/syncthing/lib/fs.(*mtimeFS).Walk(0xc000309710, 0xc00276a510, 0x26, 0xc00281a690, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/mtimefs.go:107 +0x8f
github.com/syncthing/syncthing/lib/scanner.(*walker).scan(0xc000125360, 0x2079338, 0xc000756e80, 0xc002700240, 0xc0027002a0)
	github.com/syncthing/syncthing/lib/scanner/walk.go:230 +0x20a
created by github.com/syncthing/syncthing/lib/scanner.(*walker).walk
	github.com/syncthing/syncthing/lib/scanner/walk.go:119 +0x18a
````

[panic-20210413-190110.log](https://github.com/syncthing/syncthing/files/6302994/panic-20210413-190110.log)

**Comment by imsodin** [comment]
This is db corruption or a memory db bug in goleveldb - issues like this (of which we get a lot to sentry) is a reason to consider alternatives: https://github.com/syncthing/syncthing/issues/7415

Anyone there's not really anything to do on this in particular, thus closing. If anyone can read something more into this, please just comment and we can reopen.

**Comment by tomasz1986** [comment]
Just for the record, I have tested both the storage and memory, and the hardware seems to be fine. As this is a USB external drive, I'm going to also change the cable in order to rule out other possible failures…
