### ISSUE TITLE
panic: deadlock detected at fmut

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7764]
I have found these panic logs on one of my devices. It seems that Syncthing was able to recover and continued to work on its own, so until now I wasn't even aware that they were occurring.

```
panic: deadlock detected at fmut

goroutine 33 [running]:
github.com/syncthing/syncthing/lib/model.(*deadlockDetector).Watch.func1(0xc00026c890, 0x2926444f128, 0xc00002a330, 0x2009211, 0x4)
	github.com/syncthing/syncthing/lib/model/util.go:61 +0x3a5
created by github.com/syncthing/syncthing/lib/model.(*deadlockDetector).Watch
	github.com/syncthing/syncthing/lib/model/util.go:37 +0xbe

goroutine 1 [chan receive, 95 minutes]:
github.com/syncthing/syncthing/lib/syncthing.(*App).Wait(...)
	github.com/syncthing/syncthing/lib/syncthing/syncthing.go:371
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/cmd/syncthing/main.go:721 +0xa2f
main.serveOptions.Run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/cmd/syncthing/main.go:407 +0x3f8
reflect.Value.call(0x1ffd120, 0x28d9600, 0x293, 0x2008e39, 0x4, 0xc000151c38, 0x0, 0x0, 0x146ce34, 0x1ffd120, ...)
	reflect/value.go:476 +0x907
reflect.Value.Call(0x1ffd120, 0x28d9600, 0x293, 0xc000151c38, 0x0, 0x0, 0x1f75320, 0xc000270b90, 0x186)
	reflect/value.go:337 +0xc5
github.com/alecthomas/kong.callMethod(0x200886f, 0x3, 0x1ffd120, 0x28d9600, 0x199, 0x1ffd120, 0x28d9600, 0x293, 0xc00025fe00, 0xc0000b0700, ...)
	github.com/alecthomas/kong@v0.2.16/callbacks.go:71 +0x4ba
github.com/alecthomas/kong.(*Context).RunNode(0xc0000b0700, 0xc00023e1c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/alecthomas/kong@v0.2.16/context.go:706 +0x565
github.com/alecthomas/kong.(*Context).Run(0xc0000b0700, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/alecthomas/kong@v0.2.16/context.go:723 +0xa5
main.main()
	github.com/syncthing/syncthing/cmd/syncthing/main.go:260 +0x2b6
```

[panic-20210607-054548.log](https://github.com/syncthing/syncthing/files/6644231/panic-20210607-054548.log)
[panic-20210609-053437.log](https://github.com/syncthing/syncthing/files/6644232/panic-20210609-053437.log)
[panic-20210611-033227.log](https://github.com/syncthing/syncthing/files/6644233/panic-20210611-033227.log)
[panic-20210611-053630.log](https://github.com/syncthing/syncthing/files/6644234/panic-20210611-053630.log)

Syncthing version is 1.17.0 with a few minor custom tweaks (see https://github.com/tomasz1986/syncthing/commits/tomasz86-v1.17.0).

**Comment by AudriusButkevicius** [comment]
Couldn't find the cause yet, but 

There are a few routines trying to close the connection:
```
1: chan receive [24 minutes] [Created by v4.(*Supervisor).runService @ supervisor.go:539]
    model       model.go:311               (*model).closeAllConnectionsAndWait(#102)
    model       model.go:275               (*model).serve(#102, #51, #203, #41, #95)
    svcutil     svcutil.go:125             (*service).Serve(#209, #51, #203, #215, 0x1853)
    v4          supervisor.go:551          (*Supervisor).runService.func2(#132, #75, #542, #209, #51, #203, #160, #184)
1: semacquire [50 minutes] [Created by protocol.(*rawConnection).Start @ protocol.go:282]
    sync        sema.go:71                 runtime_SemacquireMutex(#294, 0, 1)
    sync        mutex.go:138               (*Mutex).lockSlow(#293)
    sync        mutex.go:81                (*Mutex).Lock(...)
    sync        once.go:64                 (*Once).doSlow(#292, #443)
    sync        once.go:59                 (*Once).Do(...)
    protocol    protocol.go:937            (*rawConnection).internalClose(#291, #43, #527)
    protocol    protocol.go:730            (*rawConnection).writerLoop(#291)
    protocol    protocol.go:283            (*rawConnection).Start.func3(#291)
1: semacquire [27 minutes] [Created by protocol.(*rawConnection).Close @ protocol.go:932]
    sync        sema.go:71                 runtime_SemacquireMutex(#294, #387, 1)
    sync        mutex.go:138               (*Mutex).lockSlow(#293)
    sync        mutex.go:81                (*Mutex).Lock(...)
    sync        once.go:64                 (*Once).doSlow(#292, #388)
    sync        once.go:59                 (*Once).Do(...)
    protocol    protocol.go:937            (*rawConnection).internalClose(#291, #42, #107)
1: chan receive [50 minutes] [Created by protocol.(*rawConnection).Start @ protocol.go:290]
    protocol    protocol.go:953            (*rawConnection).internalClose.func1()
    sync        once.go:68                 (*Once).doSlow(#292, #104)
    sync        once.go:59                 (*Once).Do(...)
    protocol    protocol.go:937            (*rawConnection).internalClose(#291, #42, #106)
    protocol    protocol.go:999            (*rawConnection).pingReceiver(#291)
    protocol    protocol.go:291            (*rawConnection).Start.func5(#291)
```
The last one being that got past the sync.Once (for 50 minutes), but it's waiting on the dispatcher to terminate, and the dispatcher is processing the index:
```
1: runnable [Created by protocol.(*rawConnection).Start @ protocol.go:277]
    protocol    bep.pb.go:4264             (*Vector).Unmarshal(#229, #487, 0x13, 0x81, 0x2c, 0xc3f1500685f4d2af)
    db          structs.pb.go:1980         (*FileInfoTruncated).Unmarshal(#228, #486, 0xbc, 0xc0, 7, 1)
    db          transactions.go:86         readOnlyTransaction.unmarshalTrunc(#547, #319, #60, #97, 0, 0, #486, 0xbc, 0xc0, #463, ...)
    db          transactions.go:73         readOnlyTransaction.getFileTrunc(#547, #319, #60, #97, 0, 0, #450, 0x35, 0x35, 1, ...)
    db          transactions.go:228        readOnlyTransaction.getGlobalFromFileVersion(#547, #319, #60, #97, 0, 0, #450, 0x35, 0x35, #462, ...)
    db          transactions.go:691        readWriteTransaction.updateGlobal(#56, #319, #547, #319, #60, #97, 0, 0, #439, 0x31, ...)
    db          lowlevel.go:180            (*Lowlevel).updateRemoteFiles(#126, #462, 0xb, 0x10, #303, 0x20, 0x20, #158, 1, 1, ...)
    db          set.go:142                 (*FileSet).Update(#278, 0xf2a718f0199a071f, 0xfe07b19a5758b0d9, #565, #552, #158, 1, 1)
    model       model.go:1147              (*model).handleIndex(#102, 0xf2a718f0199a071f, 0xfe07b19a5758b0d9, #565, #552, #499, 0xb, #383, 1, 1, ...)
    model       model.go:1100              (*model).IndexUpdate(#102, 0xf2a718f0199a071f, 0xfe07b19a5758b0d9, #565, #552, #499, 0xb, #383, 1, 1, ...)
    protocol    nativemodel_windows.go:26  nativeModel.IndexUpdate(#546, #102, 0xf2a718f0199a071f, 0xfe07b19a5758b0d9, #565, #552, #499, 0xb, #383, 1, ...)
    protocol    encryption.go:64           encryptedModel.IndexUpdate(#55, #498, #403, 0xf2a718f0199a071f, 0xfe07b19a5758b0d9, #565, #552, #499, 0xb, #383, ...)
    protocol    protocol.go:594            (*rawConnection).handleIndexUpdate(#291, #499, 0xb, #383, 1, 1, 1, 1)
    protocol    protocol.go:477            (*rawConnection).dispatcherLoop(#291, 0, 0)
    protocol    protocol.go:278            (*rawConnection).Start.func2(#291)
```

To be honest, feels as if it's a slow device?

**Comment by tomasz1986** [comment]
> To be honest, feels as if it's a slow device?

Yep, it is a slow Intel Atom CPU and an external USB hard drive.

**Comment by imsodin** [comment]
I used to regularly check f/pmut "deadlocks" but all my samples look like false positives. Actually I think we should make our reaction less painful: What do you think about having the same kind of timeout as now, but it only results in a failure event (which I'd extend to be able to transport goroutine traces), and only after a much longer time do we actually panic. I'd still keep the panic for cases like e.g. introducing a real deadlock in a new RC release, which would otherwise require a manual upgrade (or at least restart) to resolve. My hope is to reduce the amount of false positive lock-panics and thus make it less likely for goleveldb to fail and even if the db is fine, it's also nicer on devices already being slow, if we don't interrupt their slow progress every now and then.

**Comment by tomasz1986** [comment]
I have had another panic yesterday, and judging by the times when those panics have been occurring, it seems that they usually happen when the OS is busy performing nightly backup operations, which probably causes Syncthing to wait for its turn to access the drive (as it is being run with a lower I/O priority).

Is there anything that I could do right now to prevent the panics from happening? Would moving just the database to a different storage help in this case?

**Comment by AudriusButkevicius** [comment]
The deadlock detector should only run in debug builds, so I guess your custom builds are getting in the way.

You can disable it via `STDEADLOCKTIMEOUT=0`
