### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by basings** [syncthing/syncthing#8038]
Syncthing crashes right after start on ubuntu server with docker-compose

docker-compose.yml
````
version: "2.1"

services:

  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - /data:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
````

````
Attaching to syncthing
syncthing  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
syncthing  | [s6-init] ensuring user provided files have correct perms...exited 0.
syncthing  | [fix-attrs.d] applying ownership & permissions fixes...
syncthing  | [fix-attrs.d] done.
syncthing  | [cont-init.d] executing container initialization scripts...
syncthing  | [cont-init.d] 01-envfile: executing... 
syncthing  | [cont-init.d] 01-envfile: exited 0.
syncthing  | [cont-init.d] 10-adduser: executing... 
syncthing  | 
syncthing  | -------------------------------------
syncthing  |           _         ()
syncthing  |          | |  ___   _    __
syncthing  |          | | / __| | |  /  \
syncthing  |          | | \__ \ | | | () |
syncthing  |          |_| |___/ |_|  \__/
syncthing  | 
syncthing  | 
syncthing  | Brought to you by linuxserver.io
syncthing  | -------------------------------------
syncthing  | 
syncthing  | To support LSIO projects visit:
syncthing  | https://www.linuxserver.io/donate/
syncthing  | -------------------------------------
syncthing  | GID/UID
syncthing  | -------------------------------------
syncthing  | 
syncthing  | User uid:    1000
syncthing  | User gid:    1000
syncthing  | -------------------------------------
syncthing  | 
syncthing  | [cont-init.d] 10-adduser: exited 0.
syncthing  | [cont-init.d] 90-custom-folders: executing... 
syncthing  | [cont-init.d] 90-custom-folders: exited 0.
syncthing  | [cont-init.d] 99-custom-files: executing... 
syncthing  | [custom-init] no custom files found exiting...
syncthing  | [cont-init.d] 99-custom-files: exited 0.
syncthing  | [cont-init.d] done.
syncthing  | [services.d] starting services
syncthing  | [services.d] done.
syncthing  | [start] 01:06:47 INFO: syncthing v1.18.4 "Fermium Flea" (go1.16.8 linux-arm64) root@SOMENUMBER 2021-11-02 17:11:16 UTC [noupgrade]
syncthing  | panic: leveldb: internal key "\x02\x00\x00\x00\x05\x93.", len=7: invalid length [recovered]
syncthing  | [monitor] 01:06:48 WARNING: Panic detected, writing to "/config/panic-20211105-010648.log"
syncthing  | [monitor] 01:06:48 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
syncthing  | [monitor] 01:06:48 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
syncthing  | [monitor] 01:06:48 INFO: Reporting crash found in panic-20211105-010648.log (report ID 1e0d812c) ...
syncthing  | [start] 01:06:50 INFO: syncthing v1.18.4 "Fermium Flea" (go1.16.8 linux-arm64) root@07be1e95901e 2021-11-02 17:11:16 UTC [noupgrade]
syncthing  | panic: leveldb: internal key "\x02\x00\x00\x00\x05\x93.", len=7: invalid length [recovered]
syncthing  | [monitor] 01:06:50 WARNING: Panic detected, writing to "/config/panic-20211105-010650.log"
syncthing  | [monitor] 01:06:50 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
syncthing  | [monitor] 01:06:50 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
syncthing  | [monitor] 01:06:51 INFO: Reporting crash found in panic-20211105-010650.log (report ID 590b1bc3) ...
syncthing  | [start] 01:06:52 INFO: syncthing v1.18.4 "Fermium Flea" (go1.16.8 linux-arm64) root@07be1e95901e 2021-11-02 17:11:16 UTC [noupgrade]
syncthing  | panic: leveldb: internal key "\x02\x00\x00\x00\x05\x93.", len=7: invalid length [recovered]
syncthing  | [monitor] 01:06:52 WARNING: Panic detected, writing to "/config/panic-20211105-010652.log"
syncthing  | [monitor] 01:06:52 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
syncthing  | [monitor] 01:06:52 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
^CGracefully stopping... (press Ctrl+C again to force)

````

panic-log:

````
Panic at 2021-11-05T00:56:48Z
panic: leveldb: internal key "\x02\x00\x00\x00\x05\x93.", len=7: invalid length [recovered]
        panic: leveldb: internal key "\x02\x00\x00\x00\x05\x93.", len=7: invalid length

goroutine 1 [running]:
github.com/alecthomas/kong.catch(0x4000257eb8)
        github.com/alecthomas/kong@v0.2.17/kong.go:398 +0xc0
panic(0x9368a0, 0x4000302450)
        runtime/panic.go:965 +0x154
github.com/syndtr/goleveldb/leveldb.internalKey.assert(...)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/key.go:111
github.com/syndtr/goleveldb/leveldb.internalKey.ukey(0x40000b8a71, 0x7, 0xa9c, 0xffffb91c8108, 0x40002562d8, 0x1c8d8)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/key.go:116 +0xf8
github.com/syndtr/goleveldb/leveldb.(*iComparer).Compare(0x4000302070, 0x40000b8a71, 0x7, 0xa9c, 0x40000342a0, 0x9, 0x9, 0x619e88)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/comparer.go:38 +0x38
github.com/syndtr/goleveldb/leveldb/table.(*block).seek.func1(0x5e, 0x40001260e0)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/table/reader.go:71 +0x1a0
sort.Search(0xbd, 0x4000256378, 0xe8)
        sort/search.go:66 +0x4c
github.com/syndtr/goleveldb/leveldb/table.(*block).seek(0x40004d2200, 0xdc1070, 0x4000302070, 0x0, 0xbd, 0x40000342a0, 0x9, 0x9, 0xe8, 0xa9>
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/table/reader.go:65 +0x94
github.com/syndtr/goleveldb/leveldb/table.(*blockIter).Seek(0x400006c3c0, 0x40000342a0, 0x9, 0x9, 0x40004d2200)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/table/reader.go:232 +0xc8
github.com/syndtr/goleveldb/leveldb/table.(*Reader).newBlockIter(0x40001061a0, 0x40004d2200, 0xdab428, 0x40001260e0, 0x40002cd050, 0x1, 0x0)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/table/reader.go:740 +0x304
github.com/syndtr/goleveldb/leveldb/table.(*Reader).NewIterator(0x40001061a0, 0x40002cd050, 0x0, 0x0, 0x0)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/table/reader.go:812 +0x154
github.com/syndtr/goleveldb/leveldb.(*tOps).newIterator(0x40002feed0, 0x400024c140, 0x40002cd050, 0x0, 0x1, 0x4000302430)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/table.go:479 +0x80
github.com/syndtr/goleveldb/leveldb.(*version).getIterators(0x40001284e0, 0x40002cd050, 0x0, 0x1, 0x4000256738, 0x38)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/version.go:266 +0xf0
github.com/syndtr/goleveldb/leveldb.(*DB).newRawIterator(0x40001a0000, 0x0, 0x0, 0x0, 0x0, 0x40002cd050, 0x0, 0x1, 0x40000342b0)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/db_iter.go:41 +0xa0
github.com/syndtr/goleveldb/leveldb.(*DB).newIterator(0x40001a0000, 0x0, 0x0, 0x0, 0x0, 0xa0a40, 0x4000256928, 0x0, 0x4000034298)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/db_iter.go:79 +0x60
github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0x40001a0000, 0x4000256928, 0x0, 0x0, 0x0)
        github.com/syndtr/goleveldb@v1.0.1-0.20200815071216-d9e9293bd0f7/leveldb/db.go:897 +0x11c
github.com/syncthing/syncthing/lib/db/backend.(*leveldbBackend).NewPrefixIterator(0x400003c040, 0x400003425c, 0x1, 0x1, 0x50, 0x400024c230,>
        github.com/syncthing/syncthing/lib/db/backend/leveldb_backend.go:95 +0xdc
github.com/syncthing/syncthing/lib/db.(*smallIndex).load(0x400024c230)
        github.com/syncthing/syncthing/lib/db/smallindex.go:44 +0x58
github.com/syncthing/syncthing/lib/db.newSmallIndex(0xdcd238, 0x400003c040, 0x400003425c, 0x1, 0x1, 0x37e11d600)
        github.com/syncthing/syncthing/lib/db/smallindex.go:37 +0xe0
github.com/syncthing/syncthing/lib/db.NewLowlevel(0xdcd238, 0x400003c040, 0xdbca28, 0x40002f7980, 0x4000256be8, 0x2, 0x2, 0x40001a0000, 0x1>
        github.com/syncthing/syncthing/lib/db/lowlevel.go:82 +0xe0
github.com/syncthing/syncthing/lib/syncthing.New(0xdd1bf8, 0x40004ee000, 0xdcd238, 0x400003c040, 0xdbca28, 0x40002f7980, 0x40002d8b10, 0x1,>
        github.com/syncthing/syncthing/lib/syncthing/syncthing.go:84 +0x88
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/syncthing/syncthing/cmd/syncthing/main.go:683 +0x690
main.serveOptions.Run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/syncthing/syncthing/cmd/syncthing/main.go:407 +0x304
reflect.Value.call(0xaab140, 0x1395700, 0x293, 0xab6bb0, 0x4, 0x40001e5c10, 0x0, 0x0, 0xaab140, 0x7fca0, ...)
        reflect/value.go:476 +0x644
reflect.Value.Call(0xaab140, 0x1395700, 0x293, 0x40001e5c10, 0x0, 0x0, 0xb, 0x9368a0, 0x0)
        reflect/value.go:337 +0x84
github.com/alecthomas/kong.callMethod(0xab65bd, 0x3, 0xaab140, 0x1395700, 0x199, 0xaab140, 0x1395700, 0x293, 0x40002fe840, 0x355bc0, ...)
        github.com/alecthomas/kong@v0.2.17/callbacks.go:71 +0x37c
github.com/alecthomas/kong.(*Context).RunNode(0x4000182d00, 0x400019e380, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/alecthomas/kong@v0.2.17/context.go:715 +0x3b8
github.com/alecthomas/kong.(*Context).Run(0x4000182d00, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/alecthomas/kong@v0.2.17/context.go:732 +0x80
main.main()
        github.com/syncthing/syncthing/cmd/syncthing/main.go:260 +0x220

````

**Comment by basings** [comment]
rien ne va plus

**Comment by imsodin** [comment]
The panic is because of database corruption, which is most likely a fault with your system's storage or memory. You will need to delete the index database to clear this up. However do also check your storage before continuing, otherwise if it's starting to fail, you might just see the same problem (and/or lose other data) soon.
