### ISSUE TITLE
"TypeError: $scope.saveConfig.then is not a function" when trying to unignore folders/devices

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8115]
The problem affects the current `main` after https://github.com/syncthing/syncthing/commit/21d04b895a7b3ee0803e36e4f0b3f5e8e6cf1379. Basically, there is an JS error upon trying to unignore either a folder or a device and then clicking the "save" button.

The workaround is to remove the ignored device/folder from `config.xml` manually.

```
TypeError: $scope.saveConfig.then is not a function
    at Scope.$scope.saveSettings (syncthingController.js:1516:35)
    at $parseFunctionCall (angular.js:12493:18)
    at callback (angular.js:21719:17)
    at Scope.$eval (angular.js:14589:28)
    at Scope.$apply (angular.js:14688:23)
    at HTMLButtonElement.<anonymous> (angular.js:21724:23)
    at HTMLButtonElement.dispatch (jquery-2.2.2.js:4755:27)
    at HTMLButtonElement.elemData.handle (jquery-2.2.2.js:4567:28)
```

**Comment by acolomb** [comment]
Oh, you were quicker than me with noticing this.  I opened #8116, which describes this omission as well, but also some more extensive problems with the new config saving code / `emitHTTPError()` changes.

I suggest to close this in favor of #8116.
