### ISSUE TITLE
MacOS 10.12 incompatibility

### ISSUE THREAD

**Issue by gpl34** [syncthing/syncthing#8319]
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G2136
```

and 

```
syncthing v1.20.0 "Fermium Flea" (go1.18.1 darwin-amd64) teamcity@build.syncthing.net 2022-04-25 17:15:14 UTC
```

Syncthing has auto-updated and now there is an error on launch:

```
[start] 2022/05/04 14:47:44 INFO: syncthing v1.20.0 "Fermium Flea" (go1.18.1 darwin-amd64) teamcity@build.syncthing.net 2022-04-25 17:15:14 UTC
[INMG6] 2022/05/04 14:47:44 INFO: My ID: **********************
[INMG6] 2022/05/04 14:47:45 INFO: Single thread SHA256 performance is 111 MB/s using minio/sha256-simd (110 MB/s using crypto/sha256).
[INMG6] 2022/05/04 14:47:46 INFO: Hashing performance is 91.93 MB/s
[INMG6] 2022/05/04 14:47:46 INFO: Overall send rate is unlimited, receive rate is unlimited
[INMG6] 2022/05/04 14:47:46 INFO: Using discovery mechanism: global discovery server *****
[INMG6] 2022/05/04 14:47:46 INFO: Using discovery mechanism: global discovery server *****
[INMG6] 2022/05/04 14:47:46 INFO: Using discovery mechanism: global discovery server *****
[INMG6] 2022/05/04 14:47:46 INFO: Using discovery mechanism: IPv4 local broadcast discovery on port 21027
[INMG6] 2022/05/04 14:47:46 INFO: Using discovery mechanism: IPv6 local multicast discovery on address [ff12::8384]:21027
[INMG6] 2022/05/04 14:47:46 INFO: TCP listener ([::]:22000) starting
[INMG6] 2022/05/04 14:47:46 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[INMG6] 2022/05/04 14:47:46 INFO: Ready to synchronize "Default Folder" (default) (sendreceive)
[INMG6] 2022/05/04 14:47:46 INFO: QUIC listener ([::]:22000) starting
[INMG6] 2022/05/04 14:47:46 INFO: GUI and API listening on 127.0.0.1:8384
[INMG6] 2022/05/04 14:47:46 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[INMG6] 2022/05/04 14:47:46 INFO: My name is "*****"
[INMG6] 2022/05/04 14:47:46 INFO: Completed initial scan of sendreceive folder "Default Folder" (default)
dyld: lazy symbol binding failed: Symbol not found: _SecTrustEvaluateWithError
  Referenced from: /*****/bin/./syncthing
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security

dyld: Symbol not found: _SecTrustEvaluateWithError
  Referenced from: /*****/bin/./syncthing
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security

SIGABRT: abort
PC=0xf7de9ee m=11 sigcode=0

goroutine 0 [idle]:
crypto/x509/internal/macos.syscall(0x0?, 0x0?, 0xc000721360?, 0x420b2b8?, 0x6e8b158c?, 0x5433620?, 0x0?)
	runtime/sys_darwin.go:99 +0x58 fp=0xc0007212f0 sp=0xc000721290 pc=0x40682b8
crypto/x509/internal/macos.SecTrustEvaluateWithError(0xc000035368?)
	crypto/x509/internal/macos/security.go:195 +0x48 fp=0xc000721370 sp=0xc0007212f0 pc=0x420b388
crypto/x509.(*Certificate).systemVerify(0xc000290100, 0xc000721718)
	crypto/x509/root_darwin.go:57 +0x37a fp=0xc0007215c8 sp=0xc000721370 pc=0x4214cba
crypto/x509.(*Certificate).Verify(0xc000290100, {{0xc000035368, 0x14}, 0xc00082c660, 0x0, {0xc094bb5c9821e6f8, 0x6e8b158c, 0x5433620}, {0x0, 0x0, ...}, ...})
	crypto/x509/verify.go:750 +0x4c7 fp=0xc000721718 sp=0xc0007215c8 pc=0x4219807
...
``` 

Apparently, the go version used to compile is for macOS 10.13+.

**Comment by calmh** [comment]
> Apparently, the go version used to compile is for macOS 10.13+.

Current Go states "macOS 11 or later", but yes, the root cause will be "too new Go". As such, there isn't much we can do here. You can build yourself with an older Go, for as long as that works, or you can pin Syncthing to 1.19.2 or what the latest of our binaries that worked was.
