### ISSUE TITLE
gui: "TypeError: Cannot read properties of undefined (reading 'label')" when trying to accept multiple shared folders using the Web GUI

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8589]
I've encountered this issue quite a few times. Basically, when you share multiple folders from Device A to Device B, and then use the Web GUI on the latter to quickly click the "Share" button for multiple folders, the GUI sometimes throws up the following error.

```
TypeError: Cannot read properties of undefined (reading 'label')
    at syncthingController.js:2178:78
    at processQueue (angular.js:13337:27)
    at angular.js:13353:27
    at Scope.$eval (angular.js:14589:28)
    at Scope.$digest (angular.js:14405:31)
    at Scope.$apply (angular.js:14694:24)
    at angular.js:14984:22
    at completeOutstandingRequest (angular.js:4959:10)
    at angular.js:5347:7
```

An easy way to reproduce would be something like this.

1. Share multiple (e.g. 10+) folders between Device A and Device B, then let everything sync.
2. Share the same folders between Device A and Device C, then also let them sync.
3. Now, share the folders from Device C to Device B.
4. Wait for the multiple notifications to appear in the Web GUI on Device B.
5. Lastly, on Device B try to quickly click the "Share" button for multiple folders one after another. Do not wait for the first notification to disappear before moving to the next though, just keep clicking the button for each folder even if the previous notifications are still on the screen.
6. The error may then randomly show up after trying to "share" a few of the folders.

I've experienced this problem especially when administering another device remotely, where there is a lag between the click and the GUI response. Also, the slower the hardware, the more likely is the error to show up.

**Comment by tomasz1986** [comment]
Closing as the issue was essentially fixed by https://github.com/syncthing/syncthing/pull/9063. As of now, it is impossible to try accepting multiple folders at once, because the Web GUI waits for the config to get saved first after each operation.
