### ISSUE TITLE
syncthing can't auto run with systemctl in raspberry pi-2b, but it works fine run manually

### ISSUE THREAD

**Issue by jtuTc** [syncthing/syncthing#8693]
### my os version is

```
root@raspberrypi:~# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@raspberrypi:~#
```

### syncthing.service is
```
root@raspberrypi:~# cat /usr/lib/systemd/system/syncthing.service 
[Unit]
Description=Syncthing - Open Source Continuous File Synchronization
Documentation=man:syncthing(1)
StartLimitIntervalSec=60
StartLimitBurst=4

[Service]
ExecStart=/usr/bin/syncthing serve --no-restart
Restart=on-failure
RestartSec=1
SuccessExitStatus=3 4
RestartForceExitStatus=3 4

# Elevated permissions to sync ownership (disabled by default),
# see https://docs.syncthing.net/advanced/folder-sync-ownership
#AmbientCapabilities=CAP_CHOWN CAP_FOWNER

[Install]
WantedBy=multi-user.target
root@raspberrypi:~#
```

### `journalctl -r` result is
```
Nov 27 15:30:16 raspberrypi systemd[1]: syncthing.service: Failed with result 'exit-code'.
Nov 27 15:30:16 raspberrypi systemd[1]: syncthing.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 27 15:30:16 raspberrypi syncthing[2445]:         github.com/syncthing/syncthing/lib/locations/locations.go:56 +0x14
Nov 27 15:30:16 raspberrypi syncthing[2445]: github.com/syncthing/syncthing/lib/locations.init.0()
Nov 27 15:30:16 raspberrypi syncthing[2445]:         github.com/syncthing/syncthing/lib/locations/locations.go:228 +0xb0
Nov 27 15:30:16 raspberrypi syncthing[2445]: github.com/syncthing/syncthing/lib/locations.userHomeDir()
Nov 27 15:30:16 raspberrypi syncthing[2445]: goroutine 1 [running]:
Nov 27 15:30:16 raspberrypi syncthing[2445]: panic: Failed to get user home dir
Nov 27 15:30:16 raspberrypi syncthing[2445]: $HOME is not defined
Nov 27 15:30:16 raspberrypi systemd[1]: Started Syncthing - Open Source Continuous File Synchronization.
Nov 27 15:29:50 raspberrypi systemd[1]: Reloading.
```

### but it works when i run it manually
```
root@raspberrypi:~# syncthing serve
[start] 2022/11/27 15:35:38 INFO: syncthing v1.22.2-rc.3 "Fermium Flea" (go1.19.2 linux-arm) teamcity@build.syncthing.net 2022-11-21 11:58:00 UTC
[start] 2022/11/27 15:35:38 INFO: Generating ECDSA key and certificate for syncthing...
[start] 2022/11/27 15:35:39 INFO: Default folder created and/or linked to new config
[start] 2022/11/27 15:35:39 INFO: Default config saved. Edit /root/.config/syncthing/config.xml to taste (with Syncthing stopped) or use the GUI
[start] 2022/11/27 15:35:39 INFO: Archiving a copy of old config file format at: /root/.config/syncthing/config.xml.v0
[start] 2022/11/27 15:35:39 INFO: Automatic upgrade is always enabled for candidate releases
```

**Comment by acolomb** [comment]
As it's telling you, the `$HOME` environment variable is not defined.  You'll have to read up on systemd how to fix that.

What you usually do is either instantiate the system template `syncthing@.service` for a specific user, or install it as a systemd user service right away, like `systemctl --user enable syncthing.service`.  Both should correctly set the `$HOME` variable.  See the [documentation](https://docs.syncthing.net/users/autostart.html#using-systemd).

If you have further questions, please use the forum, as the issue tracker is only meant for the developers to track actionable items.
