### ISSUE TITLE
[Bug] Fails to detect $HOME despite POSIX-compliant username 'first.last'

### ISSUE THREAD

**Issue by OdinVex** [syncthing/syncthing#8784]
### Include required information
Error during AUR compilation:
```
QDEBUG : WizardTests::testConfiguringLauncher() launcher output:  "$HOME is not defined\npanic: Failed to get user home dir\n\ngoroutine 1 [running]:\ngithub.com/syncthing/syncthing/lib/locations.userHomeDir()\n\tgithub.com/syncthing/syncthing/lib/locations/locations.go:228 +0x7d\ngithub.com/syncthing/syncthing/lib/locations.init.0()\n\tgithub.com/syncthing/syncthing/lib/locations/locations.go:56 +0x1d\n"
```

Syncthing Version: GIT (master)
Operating System: Manjaro

**Comment by calmh** [comment]
Syncthing needs `$HOME` to be set. It doesn't care about the format of your username.

**Comment by bt90** [comment]
This looks more like the AUR build script is filtering environments variables to be honest.
