### ISSUE TITLE
Syncthing v1.23.2-rc.1 crashes instantly on FreeBSD 10.4-RELEASE-p13 (amd64)

### ISSUE THREAD

**Issue by brycied00d** [syncthing/syncthing#8793]
Attempting to execute the syncthing binary from syncthing-freebsd-amd64-v1.23.2-rc.1.tar.gz results in an immediate Go runtime error, no matter what command line switches are used. The binary from syncthing-freebsd-amd64-v1.23.1.tar.gz works normally and as expected.

OS: FreeBSD 10.4-RELEASE-p13 -- I acknowledge that FreeBSD 10 is long EOL at this point. It's an old NAS and I haven't the means to replace it.
hw.model: Intel(R) Celeron(R) CPU G1610 @ 2.60GHz
hw.machine: amd64
hw.ncpu: 2
hw.physmem: 17047523328
Syncthing: v1.23.2-rc.1 (previous version works fine)

Unfortunately, given the limitations of my old NAS, I'm not able to attempt to build Syncthing from source in order to provide more troubleshooting or detail. I'm very sorry.

I've also looked at the changes between the tags (https://github.com/syncthing/syncthing/compare/v1.23.1...v1.23.2-rc.1) but nothing directly jumped out at me.

Failure Output from v1.23.2-rc.1
---
```
## wget https://github.com/syncthing/syncthing/releases/download/v1.23.2-rc.1/syncthing-freebsd-amd64-v1.23.2-rc.1.tar.gz
## tar xzvf syncthing-freebsd-amd64-v1.23.2-rc.1.tar.gz
$ syncthing-freebsd-amd64-v1.23.2-rc.1/syncthing --version
runtime: kevent failed with 78
fatal error: runtime: kevent failed

runtime stack:
runtime.throw({0xf7745b?, 0xc00006fe38?})
        runtime/panic.go:1047 +0x5d fp=0xc00006fde0 sp=0xc00006fdb0 pc=0x4361bd
runtime.netpollinit()
        runtime/netpoll_kqueue.go:44 +0x185 fp=0xc00006fe88 sp=0xc00006fde0 pc=0x432645
runtime.netpollGenericInit()
        runtime/netpoll.go:197 +0x3b fp=0xc00006fea0 sp=0xc00006fe88 pc=0x431c3b
runtime.doaddtimer(0xc000048000, 0xc00007a000)
        runtime/time.go:294 +0x31 fp=0xc00006fef8 sp=0xc00006fea0 pc=0x455d91
runtime.modtimer(0xc00007a000, 0x76ac9a4d51615c, 0x0, 0x11c7e10, {0xdccec0?, 0xc0000af1e0}, 0x0)
        runtime/time.go:508 +0x33f fp=0xc00006ff40 sp=0xc00006fef8 pc=0x45687f
runtime.resettimer(...)
        runtime/time.go:555
runtime.resetForSleep(0xc0000af1e0?, 0x400000002?)
        runtime/time.go:204 +0x37 fp=0xc00006ff88 sp=0xc00006ff40 pc=0x455b37
runtime.park_m(0xc0000af1e0?)
        runtime/proc.go:3500 +0xa3 fp=0xc00006ffb8 sp=0xc00006ff88 pc=0x43f6e3
runtime.mcall()
        runtime/asm_amd64.s:452 +0x43 fp=0xc00006ffc8 sp=0xc00006ffb8 pc=0x469183

goroutine 1 [runnable, locked to thread]:
sync.(*Once).doSlow.func1()
        sync/once.go:71 +0x35 fp=0xc0000c5568 sp=0xc0000c5560 pc=0x487295
sync.(*Once).doSlow(0x8018ac5b8?, 0x40da47?)
        sync/once.go:76 +0xfc fp=0xc0000c55c8 sp=0xc0000c5568 pc=0x4871dc
sync.(*Once).Do(...)
        sync/once.go:65
hash/crc32.MakeTable(0xd0?)
        hash/crc32/crc32.go:129 +0x97 fp=0xc0000c55e8 sp=0xc0000c55c8 pc=0x5244d7
github.com/syndtr/goleveldb/leveldb/util.init()
        github.com/syndtr/goleveldb@v1.0.1-0.20220721030215-126854af5e6d/leveldb/util/crc32.go:12 +0x1e fp=0xc0000c5600 sp=0xc0000c55e8 pc=0x914abe
runtime.doInit(0x18b5200)
        runtime/proc.go:6506 +0x118 fp=0xc0000c5730 sp=0xc0000c5600 pc=0x445e78
runtime.doInit(0x18b2760)
        runtime/proc.go:6483 +0x71 fp=0xc0000c5860 sp=0xc0000c5730 pc=0x445dd1
runtime.doInit(0x18bab40)
        runtime/proc.go:6483 +0x71 fp=0xc0000c5990 sp=0xc0000c5860 pc=0x445dd1
runtime.doInit(0x18b7a20)
        runtime/proc.go:6483 +0x71 fp=0xc0000c5ac0 sp=0xc0000c5990 pc=0x445dd1
runtime.doInit(0x18bc640)
        runtime/proc.go:6483 +0x71 fp=0xc0000c5bf0 sp=0xc0000c5ac0 pc=0x445dd1
runtime.doInit(0x18c1e20)
        runtime/proc.go:6483 +0x71 fp=0xc0000c5d20 sp=0xc0000c5bf0 pc=0x445dd1
runtime.doInit(0x18bcac0)
        runtime/proc.go:6483 +0x71 fp=0xc0000c5e50 sp=0xc0000c5d20 pc=0x445dd1
runtime.doInit(0x18bf280)
        runtime/proc.go:6483 +0x71 fp=0xc0000c5f80 sp=0xc0000c5e50 pc=0x445dd1
runtime.main()
        runtime/proc.go:233 +0x1b4 fp=0xc0000c5fe0 sp=0xc0000c5f80 pc=0x4389b4
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000c5fe8 sp=0xc0000c5fe0 pc=0x46b281

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc00005afb0 sp=0xc00005af90 pc=0x438e36
        runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc00005afb0 sp=0xc00005af90 pc=0x438e36
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.forcegchelper()
        runtime/proc.go:305 +0xa5 fp=0xc00005afe0 sp=0xc00005afb0 pc=0x438c65
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc00005afe8 sp=0xc00005afe0 pc=0x46b281
created by runtime.init.6
        runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc00005b780 sp=0xc00005b760 pc=0x438e36
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:278 +0x8e fp=0xc00005b7c8 sp=0xc00005b780 pc=0x423dae
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x26 fp=0xc00005b7e0 sp=0xc00005b7c8 pc=0x419146
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc00005b7e8 sp=0xc00005b7e0 pc=0x46b281
created by runtime.gcenable
        runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000044070?, 0x12c16d0?, 0x1?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc00005bf70 sp=0xc00005bf50 pc=0x438e36
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.(*scavengerState).park(0x191d2e0)
        runtime/mgcscavenge.go:400 +0x53 fp=0xc00005bfa0 sp=0xc00005bf70 pc=0x421cf3
runtime.bgscavenge(0x0?)
        runtime/mgcscavenge.go:628 +0x45 fp=0xc00005bfc8 sp=0xc00005bfa0 pc=0x4222a5
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x26 fp=0xc00005bfe0 sp=0xc00005bfc8 pc=0x4190e6
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x46b281
created by runtime.gcenable
        runtime/mgc.go:179 +0xaa

goroutine 17 [finalizer wait]:
runtime.gopark(0x4391b2?, 0x828c42b88?, 0x0?, 0x0?, 0xc00005a770?)
        runtime/proc.go:381 +0xd6 fp=0xc00005a628 sp=0xc00005a608 pc=0x438e36
runtime.runfinq()
        runtime/mfinal.go:193 +0x107 fp=0xc00005a7e0 sp=0xc00005a628 pc=0x418187
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc00005a7e8 sp=0xc00005a7e0 pc=0x46b281
created by runtime.createfing
        runtime/mfinal.go:163 +0x45

goroutine 18 [syscall]:
syscall.Syscall6(0x16b, 0x3, 0x0, 0x0, 0xc000056718, 0x1, 0x0)
        syscall/asm_unix_amd64.s:39 +0x5 fp=0xc000056608 sp=0xc000056600 pc=0x4c2085
syscall.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        syscall/zsyscall_freebsd_amd64.go:202 +0x5c fp=0xc000056688 sp=0xc000056608 pc=0x4bed1c
syscall.Kevent(0x0?, {0x0?, 0x0?, 0x0?}, {0xc000056718?, 0x0?, 0x0?}, 0x0?)
        syscall/syscall_bsd.go:432 +0x3c fp=0xc0000566c8 sp=0xc000056688 pc=0x4bc0fc
github.com/syncthing/notify.(*kq).Wait(0x0?)
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/watcher_kqueue.go:139 +0x4c fp=0xc000056748 sp=0xc0000566c8 pc=0x8b4a0c
github.com/syncthing/notify.(*trg).monitor(0xc000097dd0)
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/watcher_trigger.go:404 +0x3b fp=0xc0000567c8 sp=0xc000056748 pc=0x8b73db
github.com/syncthing/notify.newWatcher.func1()
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/watcher_trigger.go:112 +0x26 fp=0xc0000567e0 sp=0xc0000567c8 pc=0x8b5346
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x46b281
created by github.com/syncthing/notify.newWatcher
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/watcher_trigger.go:112 +0x20d

goroutine 19 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc000056e80 sp=0xc000056e60 pc=0x438e36
runtime.chanrecv(0xc0000ac3c0, 0xc000056fa0, 0x1)
        runtime/chan.go:583 +0x49d fp=0xc000056f10 sp=0xc000056e80 pc=0x406e9d
runtime.chanrecv2(0x0?, 0x0?)
        runtime/chan.go:447 +0x18 fp=0xc000056f38 sp=0xc000056f10 pc=0x4069d8
github.com/syncthing/notify.(*nonrecursiveTree).dispatch(0xc0000ac480, 0x0?)
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/tree_nonrecursive.go:36 +0x45 fp=0xc000056fc0 sp=0xc000056f38 pc=0x8ae565
github.com/syncthing/notify.newNonrecursiveTree.func1()
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/tree_nonrecursive.go:29 +0x2a fp=0xc000056fe0 sp=0xc000056fc0 pc=0x8ae4ea
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc000056fe8 sp=0xc000056fe0 pc=0x46b281
created by github.com/syncthing/notify.newNonrecursiveTree
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/tree_nonrecursive.go:29 +0x16a

goroutine 20 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc000057638 sp=0xc000057618 pc=0x438e36
runtime.chanrecv(0xc0000ac420, 0xc000057750, 0x1)
        runtime/chan.go:583 +0x49d fp=0xc0000576c8 sp=0xc000057638 pc=0x406e9d
runtime.chanrecv2(0x0?, 0x0?)
        runtime/chan.go:447 +0x18 fp=0xc0000576f0 sp=0xc0000576c8 pc=0x4069d8
github.com/syncthing/notify.(*nonrecursiveTree).internal(0xc0000ac480, 0xc0000ac420)
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/tree_nonrecursive.go:81 +0x53 fp=0xc0000577c0 sp=0xc0000576f0 pc=0x8aed93
github.com/syncthing/notify.newNonrecursiveTree.func2()
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/tree_nonrecursive.go:30 +0x2a fp=0xc0000577e0 sp=0xc0000577c0 pc=0x8ae48a
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc0000577e8 sp=0xc0000577e0 pc=0x46b281
created by github.com/syncthing/notify.newNonrecursiveTree
        github.com/syncthing/notify@v0.0.0-20210616190510-c6b7342338d2/tree_nonrecursive.go:30 +0x1be

goroutine 21 [sleep]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xd6 fp=0xc000057f70 sp=0xc000057f50 pc=0x438e36
time.Sleep(0x1dcd6500)
        runtime/time.go:195 +0x125 fp=0xc000057fb0 sp=0xc000057f70 pc=0x4681e5
github.com/syncthing/syncthing/lib/dialer.init.1.func2()
        github.com/syncthing/syncthing/lib/dialer/internal.go:43 +0x1e fp=0xc000057fe0 sp=0xc000057fb0 pc=0x905e1e
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x46b281
created by github.com/syncthing/syncthing/lib/dialer.init.1
        github.com/syncthing/syncthing/lib/dialer/internal.go:42 +0x136
```

Success Output from the prior version, v1.23.1
---
```
## wget https://github.com/syncthing/syncthing/releases/download/v1.23.1/syncthing-freebsd-amd64-v1.23.1.tar.gz
## tar xzvf syncthing-freebsd-amd64-v1.23.1.tar.gz
$ syncthing-freebsd-amd64-v1.23.1/syncthing --version
syncthing v1.23.1 "Fermium Flea" (go1.19.5 freebsd-amd64) teamcity@build.syncthing.net 2023-01-16 03:48:02 UTC
```

**Comment by calmh** [comment]
Yeah, FreeBSD 10.x has been unsupported since Go 1.13 was released back in 2019. I guess it finally stopped working now with Go 1.20. Sorry about that.

**Comment by brycied00d** [comment]
Thanks @calmh that's quite reasonable and fair. I've set `STNOUPGRADE` and the NAS will continue to tick along until it *finally* gets replaced. If nothing else, at least I was able to provide a "yep, this ancient FreeBSD version stopped working with this Syncthing release" data point.

Cheers!

**Comment by acolomb** [comment]
You could still try to cross-build Syncthing yourself using Go 1.19 for a few more releases. Syncthing's code will stay buildable with that at least until Go 1.21 will be released.
