### ISSUE TITLE
Nil deref in connection lan check

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#8882]
On nightlies syncthing is crashing:

```
goroutine 72 [running]:
github.com/thejerf/suture/v4.(*Supervisor).runService.func2.2()
        github.com/thejerf/suture/v4@v4.0.2/supervisor.go:561 +0xbc
panic({0xe59f80, 0x1938d20})
        runtime/panic.go:884 +0x213
github.com/syncthing/syncthing/lib/connections.(*lanChecker).isLAN(0x0, {0x12f12f8?, 0xc014099230?})
        github.com/syncthing/syncthing/lib/connections/service.go:742 +0xd1
github.com/syncthing/syncthing/lib/connections.(*lanChecker).isLANHost(0x0?, {0xc013f200c8, 0x13})
        github.com/syncthing/syncthing/lib/connections/service.go:712 +0xa8
github.com/syncthing/syncthing/lib/connections.(*commonDialer).Priority(...)
        github.com/syncthing/syncthing/lib/connections/structs.go:170
github.com/syncthing/syncthing/lib/connections.(*service).resolveDialTargets(_, {_, _}, {_, _, _}, {0x25, {0xc00459c000, 0x11, 0x11}, ...}, ...)
        github.com/syncthing/syncthing/lib/connections/service.go:668 +0x903
github.com/syncthing/syncthing/lib/connections.(*service).dialDevices(_, {_, _}, {_, _, _}, {0x25, {0xc00459c000, 0x11, 0x11}, ...}, ...)
        github.com/syncthing/syncthing/lib/connections/service.go:562 +0x47c
github.com/syncthing/syncthing/lib/connections.(*service).connect(0xc00014e7e0, {0x12f4fe0, 0xc00008d360})
        github.com/syncthing/syncthing/lib/connections/service.go:456 +0x277
github.com/syncthing/syncthing/lib/svcutil.(*service).Serve(0xc000034a80, {0x12f4fe0, 0xc00008d360})
        github.com/syncthing/syncthing/lib/svcutil/svcutil.go:130 +0x9d
github.com/thejerf/suture/v4.(*Supervisor).runService.func2()
        github.com/thejerf/suture/v4@v4.0.2/supervisor.go:565 +0xec
created by github.com/thejerf/suture/v4.(*Supervisor).runService
        github.com/thejerf/suture/v4@v4.0.2/supervisor.go:539 +0x1d5
```

I am not looking into it tonight anymore, will tomorrow. Most likely the new conn prio stuff, thus skip-changelog.

**Comment by calmh** [comment]
I think I fixed that in a followup commit the day after, however we may not be publishing new nightlies right now because the builders are in flux... I'll look into it

**Comment by calmh** [comment]
I published a new nightly for the platforms that still build on the old builder (!windows, !darwin). The newer GH Actions builds all the stuff and signs it, I just need to make it publish a nightly as well...

**Comment by calmh** [comment]
There, brand new nightlies produced and published from GHA, including the fix for this. (I'm 99% sure, but you can verify. ;)

**Comment by imsodin** [comment]
Indeed it's working - thank you!

I was actually kinda doubting myself as I couldn't imagine this flying under the radar, but wasn't awake enough anymore to check further (just needed that one doc from my mobile, thus noticed the panic :) ).
