### ISSUE TITLE
Syncthing crashes on OpenBSD due to fatal error - out of memory

### ISSUE THREAD

**Issue by lpvm** [syncthing/syncthing#9054]
### Does your log mention database corruption?

No

### Include required information

- OpenBSD 7.3 GENERIC.MP#1125 amd64
- syncthing v1.23.2 "Fermium Flea" (go1.20.1 openbsd-amd64) _pbuild@amd64-2.ports.openbsd.org 2023-03-25 02:02:12 UTC [noupgrade]
- There were already three folders shared and I tried to share another one, in fact, the first residing on a spinning disk.
The three folders in SSDs had 553MB, 310MB and 4.9GB of size.
The new folder, the one where the fatal error happened, has about 107GB.

As can be seen below, there's a **fatal error: runtime: out of memory**.
The fact is that the server is only using about 500MB out of 64GB of available RAM!
So, for sure, the server is not short of RAM.

```
[start] 2023/08/26 23:37:21 INFO: syncthing v1.23.2 "Fermium Flea" (go1.20.1 openbsd-amd64) _pbuild@amd64-2.ports.openbsd.org 2023-03-25 02:02:12 UTC [noupgrade]
[B2OJD] 2023/08/26 23:37:21 INFO: My ID: B2OJDOT-34RTHE5-COV7SDO-E7PSQR7-B2PUBAU-QXTCWKF-L6UNLK7-BTHAMQB
[B2OJD] 2023/08/26 23:37:22 INFO: Single thread SHA256 performance is 1589 MB/s using minio/sha256-simd (353 MB/s using crypto/sha256).
[B2OJD] 2023/08/26 23:37:22 INFO: Hashing performance is 931.79 MB/s
[B2OJD] 2023/08/26 23:37:22 INFO: Overall send rate is unlimited, receive rate is unlimited
[B2OJD] 2023/08/26 23:37:22 INFO: Ready to synchronize "Default Folder-Sync" (default) (sendreceive)
[B2OJD] 2023/08/26 23:37:22 INFO: TCP listener (0.0.0.0:22100) starting
[B2OJD] 2023/08/26 23:37:22 INFO: Ready to synchronize "scripts" (l2kgg-shytp) (sendreceive)
[B2OJD] 2023/08/26 23:37:22 INFO: GUI and API listening on 127.0.0.1:8384
[B2OJD] 2023/08/26 23:37:22 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
...
[B2OJD] 2023/08/26 23:37:22 INFO: Ready to synchronize "Documents" (msx3a-pv5hp) (sendreceive)
[B2OJD] 2023/08/26 23:37:22 INFO: My name is "silent.home.lan"
[B2OJD] 2023/08/26 23:37:22 INFO: Device ERD4APK-6KKZHOF-FAFUVQ4-TK3SNSV-D4U2RAD-WAHS2J4-7QRYQ4S-3257QQH is "asas" at [tcp://192.168.1.30:22101]
[B2OJD] 2023/08/26 23:37:22 INFO: Device Z3AW663-XVX5GS7-KQFCFJ3-WSBV63M-MU73HAW-EEQK5QW-S2V73C6-SC6LIAJ is "dell" at [tcp://192.168.1.194:22102]
[B2OJD] 2023/08/26 23:37:22 INFO: Ready to synchronize "home_lupe_master" (z9s4x-fxrx2) (sendreceive)
[B2OJD] 2023/08/26 23:37:22 INFO: Established secure connection to ERD4APK-6KKZHOF-FAFUVQ4-TK3SNSV-D4U2RAD-WAHS2J4-7QRYQ4S-3257QQH at 192.168.1.223:22100-192.168.1.30:22101/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256
[B2OJD] 2023/08/26 23:37:22 INFO: Device ERD4APK-6KKZHOF-FAFUVQ4-TK3SNSV-D4U2RAD-WAHS2J4-7QRYQ4S-3257QQH client is "syncthing v1.23.4" named "asas" at 192.168.1.223:22100-192.168.1.30:22101/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256
[B2OJD] 2023/08/26 23:37:25 INFO: Completed initial scan of sendreceive folder "Default Folder-Sync" (default)
[B2OJD] 2023/08/26 23:37:26 INFO: Completed initial scan of sendreceive folder "Documents" (msx3a-pv5hp)
[B2OJD] 2023/08/26 23:37:27 INFO: Completed initial scan of sendreceive folder "scripts" (l2kgg-shytp)
Panic at 2023-08-26T23:37:30+01:00
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xf62b4b?, 0x0?})
	runtime/panic.go:1047 +0x5d fp=0x25d7bd138 sp=0x25d7bd108 pc=0x435c3d
runtime.sysMapOS(0xc00c400000, 0x1c00000?)
	runtime/mem_bsd.go:75 +0x11b fp=0x25d7bd180 sp=0x25d7bd138 pc=0x4179bb
runtime.sysMap(0xc000000000?, 0xc3ffffffff?, 0x2ebdf0000?)
	runtime/mem.go:142 +0x35 fp=0x25d7bd1b0 sp=0x25d7bd180 pc=0x417755
runtime.(*mheap).grow(0x19889e0, 0xd04?)
	runtime/mheap.go:1522 +0x245 fp=0x25d7bd228 sp=0x25d7bd1b0 pc=0x427ae5
runtime.(*mheap).allocSpan(0x19889e0, 0xd04, 0x0, 0xeb?)
	runtime/mheap.go:1243 +0x2e9 fp=0x25d7bd2d0 sp=0x25d7bd228 pc=0x427269
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:961 +0x65 fp=0x25d7bd318 sp=0x25d7bd2d0 pc=0x426be5
runtime.systemstack()
	runtime/asm_amd64.s:496 +0x49 fp=0x25d7bd320 sp=0x25d7bd318 pc=0x469409

goroutine 124 [running]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:463 fp=0xc00027c910 sp=0xc00027c908 pc=0x4693a0
runtime.(*mheap).alloc(0x1a08000?, 0xd04?, 0xa0?)
	runtime/mheap.go:955 +0x65 fp=0xc00027c958 sp=0xc00027c910 pc=0x426b25
runtime.(*mcache).allocLarge(0xc00027ca30?, 0x1a07f20, 0x0)
	runtime/mcache.go:234 +0x85 fp=0xc00027c9a0 sp=0xc00027c958 pc=0x4168c5
runtime.mallocgc(0x1a07f20, 0xf32620, 0x1)
	runtime/malloc.go:1053 +0x4f7 fp=0xc00027ca08 sp=0xc00027c9a0 pc=0x40d5f7
runtime.growslice(0xc00a500000, 0xc00b8532b0?, 0xc00027cc88?, 0x0?, 0xf32620)
	runtime/slice.go:274 +0x4e9 fp=0xc00027ca68 sp=0xc00027ca08 pc=0x44dbe9
github.com/syncthing/syncthing/lib/scanner.(*walker).walk.func1()
	github.com/syncthing/syncthing/lib/scanner/walk.go:158 +0x190 fp=0xc00027cfe0 sp=0xc00027ca68 pc=0xb5c5b0
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00027cfe8 sp=0xc00027cfe0 pc=0x46b4a1
created by github.com/syncthing/syncthing/lib/scanner.(*walker).walk
	github.com/syncthing/syncthing/lib/scanner/walk.go:153 +0x2d8

<snipped//calmh>
```

**Comment by calmh** [comment]
Openbsd by default has some quite tight memory limits for programs, you probably need to increase those. Run ulimit to see what they are.

**Comment by AudriusButkevicius** [comment]
Seems like this is more suitable for the forum, as its a support query. Closing.
