### ISSUE TITLE
Syncthing 1.26.0 crashes on NetBSD 9.3 amd64

### ISSUE THREAD

**Issue by silasdb** [syncthing/syncthing#9205]
Version: Syncthing 1.26.0
Operating system: NetBSD 9.3 amd64

(Syncthing 1.25.0 works just fine)

Both oficial 1.26.0 binary and compiled from source have the same problem.

Log beginning:

```
...
[BDL4N] 2023/11/08 21:50:42 INFO: QUIC listener ([::]:22000) starting
SIGSYS: bad system call
PC=0x470b83 m=9 sigcode=32767

goroutine 0 [idle]:
runtime.lwp_park()
	runtime/sys_netbsd_amd64.s:99 +0x23 fp=0xc000269d18 sp=0xc000269d10 pc=0x470b83
runtime.semasleep(0xffffffffffffffff)
	runtime/os_netbsd.go:183 +0x11f fp=0xc000269d78 sp=0xc000269d18 pc=0x43735f
runtime.notesleep(0x0?)
	runtime/lock_sema.go:181 +0x75 fp=0xc000269db8 sp=0xc000269d78 pc=0x40e7f5
runtime.mPark(...)
	runtime/proc.go:1632
runtime.stopm()
	runtime/proc.go:2536 +0x8c fp=0xc000269de8 sp=0xc000269db8 pc=0x440cec
runtime.findRunnable()
	runtime/proc.go:3229 +0xb9c fp=0xc000269ef8 sp=0xc000269de8 pc=0x44261c
runtime.schedule()
	runtime/proc.go:3582 +0xb1 fp=0xc000269f30 sp=0xc000269ef8 pc=0x443411
runtime.park_m(0xc000284b60?)
	runtime/proc.go:3745 +0x11f fp=0xc000269f78 sp=0xc000269f30 pc=0x44391f
traceback: unexpected SPWRITE function runtime.mcall
runtime.mcall()
	runtime/asm_amd64.s:458 +0x4e fp=0xc000269f90 sp=0xc000269f78 pc=0x46d58e

goroutine 1 [chan receive]:
runtime.gopark(0x1?, 0xc00086eff0?, 0x7?, 0x86?, 0xc0003ac000?)
	runtime/proc.go:398 +0xce fp=0xc00086ef40 sp=0xc00086ef20 pc=0x43cfee
runtime.chanrecv(0xc000111b00, 0x0, 0x1)
	runtime/chan.go:583 +0x3cd fp=0xc00086efb8 sp=0xc00086ef40 pc=0x4094ad
runtime.chanrecv1(0x18?, 0xc000111b60?)
	runtime/chan.go:442 +0x12 fp=0xc00086efe0 sp=0xc00086efb8 pc=0x4090b2
github.com/syncthing/syncthing/lib/api.(*service).WaitForStart(0xc000397400)
	github.com/syncthing/syncthing/lib/api/api.go:135 +0x25 fp=0xc00086f000 sp=0xc00086efe0 pc=0xd49345
github.com/syncthing/syncthing/lib/syncthing.(*App).setupGUI(0xc000428000, {0x1334078, 0xc000002000}, {0x131b670, 0xc000144230}, {0x131b670, 0xc0001442d0}, {0x13246b8, 0xc00032a000}, {0x1324670, ...}, ...)
	github.com/syncthing/syncthing/lib/syncthing/syncthing.go:434 +0x37e fp=0xc00086f1e0 sp=0xc00086f000 pc=0xd7031e
github.com/syncthing/syncthing/lib/syncthing.(*App).startup(0xc000428000)
	github.com/syncthing/syncthing/lib/syncthing/syncthing.go:315 +0x1d58 fp=0xc0008700c8 sp=0xc00086f1e0 pc=0xd6f1d8
github.com/syncthing/syncthing/lib/syncthing.(*App).Start(0xc000428000)
	github.com/syncthing/syncthing/lib/syncthing/syncthing.go:116 +0x1f3 fp=0xc000870158 sp=0xc0008700c8 pc=0xd6d2f3
...
```

There are more 6000+ lines of log. Should I paste the rest of them?

**Comment by calmh** [comment]
"Bad system call" indicates it's trying to do something the kernel doesn't support; I don't know if that means something is too old or new or some component not compiled in, but it's likely a Go issue and not Syncthing itself.

Assuming the problem is triggered by the QUIC code (that being the last log line), perhaps you can work around it by disabling the QUIC listener.

**Comment by silasdb** [comment]
Some more information:

I disabled QUIC (I set listen addresses to `dynamic+https://relays.syncthing.net/endpoint`, is it enough?). Now I get a different error message:

```
[D2FJK] 2023/11/21 10:55:32 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[D2FJK] 2023/11/21 10:55:32 INFO: GUI and API listening on 127.0.0.1:8384
[D2FJK] 2023/11/21 10:55:32 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[D2FJK] 2023/11/21 10:55:32 INFO: My name is "<redacted>"
[D2FJK] 2023/11/21 10:55:32 INFO: Device <redacted> is "<redacted>" at [dynamic]
[D2FJK] 2023/11/21 10:55:32 INFO: Device <redacted> is "<redacted>" at [dynamic]
[D2FJK] 2023/11/21 10:55:32 INFO: Device <redacted> is "<redacted>" at [dynamic]
[D2FJK] 2023/11/21 10:55:32 INFO: Ready to synchronize "<redacted>" (<redacted>) (sendreceive)
SIGSYS: bad system call
PC=0x471103 m=9 sigcode=32767

goroutine 0 [idle]:
runtime.kevent()
	runtime/sys_netbsd_amd64.s:429 +0x23 fp=0xc0004ad348 sp=0xc0004ad340 pc=0x471103
runtime.netpoll(0xc000046000?)
	runtime/netpoll_kqueue.go:141 +0xfb fp=0xc0004adde8 sp=0xc0004ad348 pc=0x436d7b
runtime.findRunnable()
	runtime/proc.go:3191 +0x825 fp=0xc0004adef8 sp=0xc0004adde8 pc=0x442285
runtime.schedule()
	runtime/proc.go:3582 +0xb1 fp=0xc0004adf30 sp=0xc0004adef8 pc=0x4433f1
runtime.park_m(0xc0001621a0?)
	runtime/proc.go:3745 +0x11f fp=0xc0004adf78 sp=0xc0004adf30 pc=0x4438ff
traceback: unexpected SPWRITE function runtime.mcall
runtime.mcall()
	runtime/asm_amd64.s:458 +0x4e fp=0xc0004adf90 sp=0xc0004adf78 pc=0x46d56e
```

The same happens with 1.27.0-rc.1

**Comment by chrisdebian** [comment]
Does anyone know if this is an issue with the current release?
