### ISSUE TITLE
Crashes with out of memory

### ISSUE THREAD

**Issue by vsespb** [syncthing/syncthing#9807]
### What happened?

Hello. It started crashing evey time and cannot start. Previously were working find and had no issues with memory

### Syncthing version

v1.23.4

### Platform & operating system

Linux debian

### Relevant log output

```shell
Nov 10 16:27:51 176-58-110-134 systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for syncthing.
Nov 10 16:27:52 176-58-110-134 syncthing[15493]: [start] INFO: syncthing v1.23.4 "Fermium Flea" (go1.20.2 linux-amd64) teamcity@build.syncthing.net 2023-04-05 13:25:55 UTC
Nov 10 16:27:52 176-58-110-134 syncthing[15493]: [SYASK] INFO: My ID: [CUT]
Nov 10 16:27:53 176-58-110-134 syncthing[15493]: [SYASK] INFO: Single thread SHA256 performance is 1420 MB/s using minio/sha256-simd (353 MB/s using crypto/sha256).
Nov 10 16:27:53 176-58-110-134 syncthing[15493]: [SYASK] INFO: Hashing performance is 409.03 MB/s
Nov 10 16:27:53 176-58-110-134 syncthing[15493]: [SYASK] INFO: Overall send rate is unlimited, receive rate is unlimited
Nov 10 16:27:53 176-58-110-134 syncthing[15493]: [SYASK] INFO: Ready to synchronize [CUT]
Nov 10 16:27:53 176-58-110-134 syncthing[15493]: [SYASK] INFO: TCP listener ([::]:22000) starting
Nov 10 16:27:53 176-58-110-134 syncthing[15493]: 2024/11/10 16:27:53 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See 
Nov 10 16:27:53 176-58-110-134 syncthing[15493]: [SYASK] INFO: QUIC listener ([::]:22000) starting
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Ready to synchronize [CUT] (receiveonly)
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Ready to synchronize [CUT] (sendreceive)
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: GUI and API listening on 127.0.0.1:8384
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: My name is [CUT]
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Device [CUT] is "[CUT]" at [CUT]
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Device [CUT]
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Device [CUT]
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Device [CUT]
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Cleaned away old file panic-20241103-144457.log
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Cleaned away old file panic-20241103-144615.log
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Cleaned away old file panic-20241103-144712.log
Nov 10 16:27:54 176-58-110-134 syncthing[15493]: [SYASK] INFO: Ready to synchronize [CUT] (sendreceive)
Nov 10 16:27:56 176-58-110-134 syncthing[15493]: [SYASK] INFO: Completed initial scan of sendreceive folder [CUT]
Nov 10 16:27:56 176-58-110-134 syncthing[15493]: [SYASK] INFO: Completed initial scan of receiveonly folder [CUT]
Nov 10 16:27:56 176-58-110-134 syncthing[15493]: [SYASK] INFO: Completed initial scan of sendreceive folder [CUT]
Nov 10 16:27:57 176-58-110-134 syncthing[15493]: [SYASK] INFO: Completed initial scan of sendreceive folder [CUT]
Nov 10 16:28:18 176-58-110-134 syncthing[15493]: fatal error: runtime: out of memory
Nov 10 16:28:18 176-58-110-134 syncthing[15493]: [monitor] WARNING: Panic detected, writing to "/home/syncthing/.config/syncthing/panic-20241110-162818.log"
Nov 10 16:28:18 176-58-110-134 syncthing[15493]: [monitor] WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/iss
Nov 10 16:28:18 176-58-110-134 syncthing[15493]: [monitor] WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
Nov 10 16:28:18 176-58-110-134 systemd[1]: syncthing@syncthing.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 10 16:28:18 176-58-110-134 systemd[1]: syncthing@syncthing.service: Unit entered failed state.
Nov 10 16:28:18 176-58-110-134 systemd[1]: syncthing@syncthing.service: Failed with result 'exit-code'.
Nov 10 16:28:18 176-58-110-134 systemd[1]: syncthing@syncthing.service: Service hold-off time over, scheduling restart.
Nov 10 16:28:18 176-58-110-134 systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for syncthing.
Nov 10 16:28:18 176-58-110-134 systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for syncthing.
Nov 10 16:28:18 176-58-110-134 syncthing[15521]: [start] INFO: syncthing v1.23.4 "Fermium Flea" (go1.20.2 linux-amd64) teamcity@build.syncthing.net 2023-04-05 13:25:55 UTC
```

and panic file:
```
Panic at 2024-11-10T16:28:18Z
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xfa5c1f?, 0x0?})
	runtime/panic.go:1047 +0x5d fp=0xc000063df8 sp=0xc000063dc8 pc=0x43705d
runtime.sysMapOS(0xc004000000, 0x400000?)
	runtime/mem_linux.go:187 +0x11b fp=0xc000063e40 sp=0xc000063df8 pc=0x41839b
runtime.sysMap(0x1972d00?, 0xc3ffffffff?, 0x1982e98?)
	runtime/mem.go:142 +0x35 fp=0xc000063e70 sp=0xc000063e40 pc=0x417d75
runtime.(*mheap).grow(0x1972d00, 0x100?)
	runtime/mheap.go:1522 +0x245 fp=0xc000063ee8 sp=0xc000063e70 pc=0x4284c5
runtime.(*mheap).allocSpan(0x1972d00, 0x100, 0x0, 0x1a?)
	runtime/mheap.go:1243 +0x1b7 fp=0xc000063f80 sp=0xc000063ee8 pc=0x427c17
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:961 +0x65 fp=0xc000063fc8 sp=0xc000063f80 pc=0x4276c5
runtime.systemstack()
	runtime/asm_amd64.s:496 +0x49 fp=0xc000063fd0 sp=0xc000063fc8 pc=0x46aae9

goroutine 99 [running]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:463 fp=0xc0013fc098 sp=0xc0013fc090 pc=0x46aa80
runtime.(*mheap).alloc(0x200000?, 0x100?, 0x0?)
	runtime/mheap.go:955 +0x65 fp=0xc0013fc0e0 sp=0xc0013fc098 pc=0x427605
runtime.(*mcache).allocLarge(0x0?, 0x200000, 0x1)
	runtime/mcache.go:234 +0x85 fp=0xc0013fc128 sp=0xc0013fc0e0 pc=0x416e05
runtime.mallocgc(0x200000, 0xe09e20, 0x1)
	runtime/malloc.go:1053 +0x4f7 fp=0xc0013fc190 sp=0xc0013fc128 pc=0x40db37
runtime.makeslice(0xb?, 0xc001399370?, 0x1?)
	runtime/slice.go:103 +0x52 fp=0xc0013fc1b8 sp=0xc0013fc190 pc=0x44f0d2
github.com/syncthing/syncthing/lib/ur.CpuBench({0x12ed708, 0xc000038058}, 0x5, 0xf8f8f8f8f8f8f8f8?, 0x59?)
	github.com/syncthing/syncthing/lib/ur/usage_report.go:418 +0xe5 fp=0xc0013fc2a8 sp=0xc0013fc1b8 pc=0xcc00c5
github.com/syncthing/syncthing/lib/ur.(*Service).reportData(0xc00028ed40, {0x12ed708, 0xc000038058}, 0x3, 0x1?)
	github.com/syncthing/syncthing/lib/ur/usage_report.go:117 +0x54e fp=0xc0013fee90 sp=0xc0013fc2a8 pc=0xcbe10e
github.com/syncthing/syncthing/lib/ur.(*Service).ReportDataPreview(...)
	github.com/syncthing/syncthing/lib/ur/usage_report.go:74
github.com/syncthing/syncthing/lib/api.(*service).getReport(0xc000273e00, {0x12ecca0, 0xc001364c40}, 0x44b114?)
	github.com/syncthing/syncthing/lib/api/api.go:1296 +0xab fp=0xc0013feec8 sp=0xc0013fee90 pc=0xd6142b
github.com/syncthing/syncthing/lib/api.(*service).getReport-fm({0x12ecca0?, 0xc001364c40?}, 0x44b5f5?)
	<autogenerated>:1 +0x3c fp=0xc0013feef8 sp=0xc0013feec8 pc=0xd73f3c
net/http.HandlerFunc.ServeHTTP(0x0?, {0x12ecca0?, 0xc001364c40?}, 0x19566c0?)
	net/http/server.go:2122 +0x2f fp=0xc0013fef20 sp=0xc0013feef8 pc=0x6ffa2f
github.com/julienschmidt/httprouter.(*Router).Handler.func1({0x12ecca0?, 0xc001364c40?}, 0xc00122bdc0?, {0x0?, 0x25fc543de24ab4e?, 0xc001212ff0?})
	github.com/julienschmidt/httprouter@v1.3.0/router.go:275 +0x196 fp=0xc0013fef98 sp=0xc0013fef20 pc=0xb98176
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00027dc80, {0x12ecca0, 0xc001364c40}, 0xc0013a8600)
	github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x81c fp=0xc0013ff0a8 sp=0xc0013fef98 pc=0xb9953c
github.com/syncthing/syncthing/lib/api.metricsMiddleware.func1({0x12ecca0, 0xc001364c40}, 0xc0013a8600)
	github.com/syncthing/syncthing/lib/api/api.go:580 +0xc6 fp=0xc0013ff118 sp=0xc0013ff0a8 pc=0xd57cc6
net/http.HandlerFunc.ServeHTTP(0xeed5c0?, {0x12ecca0?, 0xc001364c40?}, 0x6?)
	net/http/server.go:2122 +0x2f fp=0xc0013ff140 sp=0xc0013ff118 pc=0x6ffa2f
github.com/syncthing/syncthing/lib/api.noCacheMiddleware.func1({0x12ecca0, 0xc001364c40}, 0x0?)
	github.com/syncthing/syncthing/lib/api/api.go:603 +0x305 fp=0xc0013ff1f0 sp=0xc0013ff140 pc=0xd58285
net/http.HandlerFunc.ServeHTTP(0x100c0013aec50?, {0x12ecca0?, 0xc001364c40?}, 0xc0008fb520?)
	net/http/server.go:2122 +0x2f fp=0xc0013ff218 sp=0xc0013ff1f0 pc=0x6ffa2f
net/http.(*ServeMux).ServeHTTP(0xc0002e5e00?, {0x12ecca0, 0xc001364c40}, 0xc0013a8600)
	net/http/server.go:2500 +0x149 fp=0xc0013ff268 sp=0xc0013ff218 pc=0x7013c9
github.com/syncthing/syncthing/lib/api.(*csrfManager).ServeHTTP(0xc0002e5e00, {0x12ecca0, 0xc001364c40}, 0xc0013a8600)
	github.com/syncthing/syncthing/lib/api/api_csrf.go:107 +0x1b7 fp=0xc0013ff3c8 sp=0xc0013ff268 pc=0xd69597
github.com/syncthing/syncthing/lib/api.withDetailsMiddleware.func1({0x12ecca0, 0xc001364c40}, 0xc0001205a0?)
	github.com/syncthing/syncthing/lib/api/api.go:611 +0x23d fp=0xc0013ff468 sp=0xc0013ff3c8 pc=0xd585bd
net/http.HandlerFunc.ServeHTTP(0xe4f8e0?, {0x12ecca0?, 0xc001364c40?}, 0x20?)
	net/http/server.go:2122 +0x2f fp=0xc0013ff490 sp=0xc0013ff468 pc=0x6ffa2f
github.com/syncthing/syncthing/lib/api.basicAuthAndSessionMiddleware.func1({0x12ecca0, 0xc001364c40}, 0xc0013a8600)
	github.com/syncthing/syncthing/lib/api/api_auth.go:59 +0x4ef fp=0xc0013ff848 sp=0xc0013ff490 pc=0xd67f2f
net/http.HandlerFunc.ServeHTTP(0xeed5c0?, {0x12ecca0?, 0xc001364c40?}, 0x16?)
	net/http/server.go:2122 +0x2f fp=0xc0013ff870 sp=0xc0013ff848 pc=0x6ffa2f
github.com/syncthing/syncthing/lib/api.corsMiddleware.func1({0x12ecca0, 0xc001364c40}, 0xc0013a8600)
	github.com/syncthing/syncthing/lib/api/api.go:572 +0x60e fp=0xc0013ff948 sp=0xc0013ff870 pc=0xd57b0e
net/http.HandlerFunc.ServeHTTP(0xc0013596e0?, {0x12ecca0?, 0xc001364c40?}, 0x0?)
	net/http/server.go:2122 +0x2f fp=0xc0013ff970 sp=0xc0013ff948 pc=0x6ffa2f
github.com/syncthing/syncthing/lib/api.localhostMiddleware.func1({0x12ecca0, 0xc001364c40}, 0xc0013a8600)
	github.com/syncthing/syncthing/lib/api/api.go:618 +0x75 fp=0xc0013ff9b8 sp=0xc0013ff970 pc=0xd58715
net/http.HandlerFunc.ServeHTTP(0x416030?, {0x12ecca0?, 0xc001364c40?}, 0x12e60e0?)
	net/http/server.go:2122 +0x2f fp=0xc0013ff9e0 sp=0xc0013ff9b8 pc=0x6ffa2f
```
```

**Comment by vsespb** [comment]
hm, probably hosting issue. reboot helped.
